### ISSUE TITLE
can't start Leofs Gateway 

### ISSUE THREAD

**Issue by Abdelwaheb-Hnaien** [leo-project/leofs#1009]
Hello everyone, 
I'm trying to start Leofs Gateway, but I can't until now make it.
I run this command [ leo_gateway/bin/leo_gateway start ]
than I check the status : [ leofs-adm status ] : 

-------+--------------------------+--------------+----------------+----------------+----------------------------
 type  |           node           |    state     |  current ring  |   prev ring    |          updated at         
-------+--------------------------+--------------+----------------+----------------+----------------------------
  S    | storage_0@127.0.0.1      | running      | 433fe365       | 433fe365       | 2018-03-26 08:21:53 +0000
-------+--------------------------+--------------+----------------+----------------+----------------------------

any idea ! 

PS: I'm running leofs in a docker container.

**Comment by yosukehara** [comment]
@Abdelwaheb-Hnaien Thank you for your report. Let me/us check the environment of your LeoFS. Do you think you could answer following questions?

### [Questions]

* Network: Can LeoGateway connect LeoManager node(s)?
* LeoFS version
* Attach error log files if that exists.
* What operating system(uname -a) and processor architecture(cat /proc/cpuinfo) and memory(cat /proc/meminfo) are you using?

**Comment by Abdelwaheb-Hnaien** [comment]
Thank you for your fast reply.
I'll explain the situation, I'm using LeoFS in a production environment.
I'm using EC2 CentOS 7 server.
first I run a docker image [firejun/leofs/](https://hub.docker.com/r/firejun/leofs/), it turns out that Gateway won't start, then I run another docker image [touchcast/leofs/](https://hub.docker.com/r/touchcast/leofs/) and now the gateway works fine but not able to communicate with it from a php client. each time I get : 
Guzzle\Http\Exception\CurlException' with message '[curl] 7: Failed connect to mybucket.localhost:8080.
I'm sure everything is configured well because I had before tried this locally  and everything works fine yet on amazon EC2 server it's not the case.
I edited the /etc/hosts and I associated the container IP  with 'mybucket.localhost', I'm also sure about the private and public key.
until now I can't figure out why everything works fine locally but not on EC2.

**Comment by yosukehara** [comment]
@Abdelwaheb-Hnaien It seems Docker image's issue. If you would like to use Docker, I recommend you write a docker file for LeoGateway instread of `touchcast/leofs/` and others.

**Comment by Abdelwaheb-Hnaien** [comment]
@yosukehara I changed the server and everything works well now. 
I think LeoFS had a **minimum hardware requirements** (2 core cpu, 4 gb RAM), at first I was running a server with 1 core cpu and 1Gb RAM, I think that's the reason why it didn't work.

Thanks for confirming that or telling us what are the reasons that might occur LeoFS Gateway not to start.

Here is the new configuration : 
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
stepping        : 2
microcode       : 0x3b
cpu MHz         : 2400.162
cache size      : 30720 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
bogomips        : 4800.10
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
stepping        : 2
microcode       : 0x3b
cpu MHz         : 2400.162
cache size      : 30720 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
bogomips        : 4800.10
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
```
```
[root@ip-172-31-60-40 centos]# cat /proc/meminfo
MemTotal:        3880256 kB
MemFree:          343808 kB
MemAvailable:    2237212 kB
Buffers:            2068 kB
Cached:          2056964 kB
SwapCached:            0 kB
Active:          1695860 kB
Inactive:        1399388 kB
Active(anon):    1074460 kB
Inactive(anon):    44156 kB
Active(file):     621400 kB
Inactive(file):  1355232 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 8 kB
Writeback:             0 kB
AnonPages:       1036116 kB
Mapped:            95988 kB
Shmem:             82400 kB
Slab:             324668 kB
SReclaimable:     202916 kB
SUnreclaim:       121752 kB
KernelStack:       10448 kB
PageTables:        18088 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     1940128 kB
Committed_AS:    4302312 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       17668 kB
VmallocChunk:   34359713532 kB
HardwareCorrupted:     0 kB
AnonHugePages:    901120 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      114688 kB
DirectMap2M:     4079616 kB

```

**Comment by mocchira** [comment]
@Abdelwaheb-Hnaien Thanks for the additional info.

> I think LeoFS had a minimum hardware requirements (2 core cpu, 4 gb RAM), at first I was running a server with 1 core cpu and 1Gb RAM, I think that's the reason why it didn't work.

As fa as I know, there is no requirements for the number of cpu cores for the latest version.
However old versions used by https://hub.docker.com/r/firejun/leofs/ and https://hub.docker.com/r/touchcast/leofs/ have a problem which causes leo_gateway to fail to start so this might be the first problem you faced before.

As for memory requirements, on-memory cache settings enabled by default on leo_gateway may cause leo_gateway to fail to start so can you try to start leo_gateway with settings below.

https://github.com/leo-project/leofs/blob/1.4.0/apps/leo_gateway/priv/leo_gateway.conf#L168
```ini
cache.cache_ram_capacity = 0 ### 0 means disabling the on-memory cache
```
this might help you start leo_gateway with smaller memory environments.
I hope you find it helpful.

**Comment by vstax** [comment]
I'd like to add one thing from my experience. Leo_gateway can consume low amounts of memory (typically like 100 MB + cache.cache_ram.capacity) only when working in S3 mode with default chunk size for large objects (5 MB) and with low amount of clients. Right now when uploading large objects in REST mode, or when working in NFS mode gateway can consume a lot of memory under certain circumstances. Also, handling a lot of clients at once obviously requires more memory as well.

**Comment by Abdelwaheb-Hnaien** [comment]
Hi, 
I'd like to report two issues that I encountered with LeoFS recently: 
The first one is related to LeoFS v1.4.0 , I followed exactly the same installation steps mentioned in the official documentation and everything seems to be fine but when I come to run the following command 
`systemctl start leofs-manager-master leofs-manager-slave leofs-gateway leofs-storage`
it says :
**Job for leofs-manager-master.service failed because the control process exited with error code. See "systemctl status leofs-manager-master.service" and "journalctl -xe" for details.**
I tried the manual installation with two different environments, a Ubuntu VM  on a Mac, and another machine running CentOS 7. Each time I get exactly the same problem.
here is the output of **systemctl status leofs-manager-master.service**:
```
leofs-manager-master.service - LeoFS master management node
   Loaded: loaded (/usr/lib/systemd/system/leofs-manager-master.service; disabled; vendor preset: disabled)
   Active: inactive (dead) (Result: exit-code) since Sun 2018-04-29 09:46:21 WEST; 2s ago
  Process: 5542 ExecStop=/usr/local/leofs/current/leo_manager_0/bin/leo_manager stop (code=exited, status=127)
  Process: 5377 ExecStart=/usr/local/leofs/current/leo_manager_0/bin/leo_manager foreground_start (code=exited, status=1/FAILURE)
 Main PID: 5377 (code=exited, status=1/FAILURE)

Apr 29 09:46:01 192.168.0.115 systemd[1]: Failed to start LeoFS master management node.
Apr 29 09:46:01 192.168.0.115 systemd[1]: Unit leofs-manager-master.service entered failed state.
Apr 29 09:46:01 192.168.0.115 systemd[1]: leofs-manager-master.service failed.
Apr 29 09:46:21 192.168.0.115 systemd[1]: leofs-manager-master.service holdoff time over, scheduling restart.
```

When I try to install older version of leoFS(v 1.3.8) I don't face this issue and I can run 'leofs-adm start' successefully.

The second issue is that I tried to build a Docker file for LeoFS (v 1.3.8), This is the Dockerfile content : 
```
# Dockerfile
FROM ubuntu:16.04 

RUN apt-get update && apt-get install wget lsb-release -y

RUN wget https://github.com/leo-project/leofs/releases/download/1.4.0/leofs_1.4.0-1_erl-19.3_ubuntu-16.04_amd64.deb && chmod +x leofs_1.4.0-1_erl-19.3_ubuntu-16.04_amd64.deb

RUN sudo dpkg -i leofs_1.4.0-1_erl-19.3_ubuntu-16.04_amd64.deb && apt-get install -f

RUN sudo systemctl start leofs-manager-master leofs-manager-slave leofs-gateway leofs-storage

Expose 8080
```
when I run `docker build .` it stucks in : 
**Step 4/6 : RUN dpkg -i leofs_1.3.8-1_erl-19.3_ubuntu-16.04_amd64.deb**
 and I get : 
```
adduser: Warning: The home directory `/usr/local/leofs' does not belong to the user you are currently creating.
Created symlink /etc/systemd/system/sockets.target.wants/leofs-epmd.socket, pointing to /lib/systemd/system/leofs-epmd.socket.
Failed to connect to bus: No such file or directory
dpkg: error processing package leofs (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 leofs
The command '/bin/sh -c dpkg -i leofs_1.3.8-1_erl-19.3_ubuntu-16.04_amd64.deb' returned a non-zero code: 1
```

it seems that docker execute these comands with root user but in this step it tries to access the directory **/usr/local/leofs** which belongs to **leofs** user maybe.

I'm wondering if anyone can help, what prevents leo_manager from starting and what shall I add to the dockerfile in order to fix the second problem.

Thank you
