### ISSUE TITLE
[rack aware] doesn't work as expected

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#1046]
Now there are some cases that rack awareness doesn't work as expected.
For example, let's say that we try to create a cluster with

- 5 storage nodes (node[1-5])
- 2 physical racks (rack[1-2])
- 2 replicas (N=2) and each replica should belong to a different rack

then set the configurations as following

- replication.rack_awareness.rack_id on each leo_storage.conf
  - storage_0@127.0.0.1: replication.rack_awareness.rack_id = rack1
  - storage_1@127.0.0.1: replication.rack_awareness.rack_id = rack1
  - storage_2@127.0.0.1: replication.rack_awareness.rack_id = rack1
  - storage_3@127.0.0.1: replication.rack_awareness.rack_id = rack2
  - storage_4@127.0.0.1: replication.rack_awareness.rack_id = rack2
- consistency.rack_aware_replicas = 2 

however there are some objects that have replicas both belonging to a same rack like following.

```shell
leofs@cat2neat:leofs.1.3.5$ leofs-adm whereis "test/2"
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
 del?  |           node           |             ring address             |    size    |   checksum   |  has children  |  total chunks  |     clock      |             when
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------+----------------------------
       | storage_4@127.0.0.1      | 738e5b62350a5baebb0a619d9e44a91c     |         6K |   21f79de954 | false          |              0 | 56ce8ee93a199  | 2018-05-24 09:42:54 +0900
       | storage_3@127.0.0.1      | 738e5b62350a5baebb0a619d9e44a91c     |         6K |   21f79de954 | false          |              0 | 56ce8ee93a199  | 2018-05-24 09:42:54 +0900
```

storage_[3,4]@127.0.0.1 both belong to rack2.

* related link: leo-project/leofs/issues/1047

**Comment by yosukehara** [comment]
Fixed it by leo-project/leo_redundant_manager/pull/9
