### ISSUE TITLE
LeoFS Users and Leo_Gateway Logging

### ISSUE THREAD

**Issue by varuntanwar** [leo-project/leofs#1062]
How can I restrict users not to delete files from the leofs cluster or is there any other way to get the IP address of the users which are accessing the gateway for files.
and
What is the main difference between user role_id 1 and 9?

**Comment by yosukehara** [comment]
> How can I restrict users not to delete files from the leofs cluster

You can control users' access with using S3-API:
* See [S3-API Related Operations](https://leo-project.net/leofs/docs/admin/system_operations/s3/#s3-api-related-operations)

> or is there any other way to get the IP address of the users which are accessing the gateway for files.

We don't deliver this function but you can satisfy your request by placing HAProxy, etc in front of LeoFS.

> and What is the main difference between user role_id 1 and 9?

LeoFS' Web GUI, [LeoCenter](https://github.com/leo-project/leo_center) uses this configuration _(`leofs-adm` does not see it)_ :

* 1: General User
* 9: Administrator

**Comment by mocchira** [comment]
@varuntanwar 

> You can control users' access with using S3-API:

Just in case, I'd drop the more specific procedure below.

1. Create user A
2. Create a bucket with the owner A
3. Set the bucket's ACL to "public-read"
4. Create user B
5. Provide LeoFS users with B's credential (Accesskey and SecretKey)

then

Operations they can do with B's credential are limited to only GET/HEAD requests. I think this might work for you, however if you aim to allow users to issue GET/HEAD/PUT (only prohibit DELETE) then unfortunately it doesn't. if that is the case then only option which solves this requirement would be

As @yosukehara said on the prev comment,

> We don't deliver this function but you can satisfy your request by placing HAProxy, etc in front of LeoFS.

Put some http proxy software like HAProxy, Nginx or something else in front of LeoFS and set the rule to prohibit any DELETE requests from users.

I hope you find those helpful however Don't hesitate to ask me if you have any questions.

**Comment by mocchira** [comment]
I'll close as it's already answered and no replies for a long time.
