### ISSUE TITLE
Custom metadata support

### ISSUE THREAD

**Issue by zolazhou** [leo-project/leofs#107]
Is there a plan for custom metadata support?

I have noticed that there is a `meta` field on #object record but it is not used yet.

**Comment by mocchira** [comment]
## Spec
- https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata

## REST API to be modified
- http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html
- http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html
- http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectGET.html
- http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectHEAD.html

## Source files to be modified
### leo_gateway
- https://github.com/leo-project/leo_gateway/blob/develop/src/leo_gateway_rpc_handler.erl
- https://github.com/leo-project/leo_gateway/blob/develop/src/leo_gateway_http_commons.erl
- https://github.com/leo-project/leo_gateway/blob/develop/src/leo_gateway_s3_api.erl

### leo_storage
- https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_handler_object.erl
- https://github.com/leo-project/leo_storage/blob/develop/src/leo_sync_remote_cluster.erl

### leo_object_storage
- https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_transformer.erl
- https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_haystack.erl

## Cautions
- As the Multi DC feature has already used the custom meta data field, take care of that.

**Comment by yosukehara** [comment]
LeoFS' custom metadata feature depends on S3-API:

- Limitation of length of a custom-metadata (User-Defined Metadata):

```
Note:
The PUT request header is limited to 8 KB in size. Within the PUT request header, 
the user-defined metadata is limited to 2 KB in size. The size of user-defined metadata
is measured by taking the sum of the number of bytes in the UTF-8 encoding of each 
key and value.
```

**Comment by yosukehara** [comment]
Finished
