### ISSUE TITLE
Does leofs have storage quota management?

### ISSUE THREAD

**Issue by FunnyRyan** [leo-project/leofs#1099]
I didn't see the relevant commands in the documentation. Does anyone know?

**Comment by mocchira** [comment]
Unfortunately LeoFS has not supported the quota management yet.
However there are some related issues already filed on github.

- https://github.com/leo-project/leofs/issues/127
  - Keep tracking the size of a bucket
- https://github.com/leo-project/leofs/issues/557
  - Multi-Tenancy Support

That being said, we may implement the buckcet/user level multi-tenancy and limit the used disk space per bucket/user in the future (maybe version 2.0 or higher ones).

If you want this kind of features, let us know through comments or reactions on the above issues. we tend to prioritize the features many users would want than the others.

**Comment by mocchira** [comment]
I'll close this issue as it's already answered.
