### ISSUE TITLE
excuse me, how to change the default port 8080 to 80 ?

### ISSUE THREAD

**Issue by FunnyRyan** [leo-project/leofs#1100]

**Comment by mocchira** [comment]
As you can see at the below links,
- https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/priv/leo_gateway.conf#L56
- https://leo-project.net/leofs/docs/admin/settings/leo_gateway/#leogateway-configurations

You can change the port through http.port in leo_gateway.conf

**Comment by FunnyRyan** [comment]
thank u
