### ISSUE TITLE
There was an error when i useing ansible stop or start cluster

### ISSUE THREAD

**Issue by FunnyRyan** [leo-project/leofs#1102]
there is an error

TASK [leo_gateway : Stop LeoGateway] **********************************************************************************************************************************************************
fatal: [45.33.47.145]: FAILED! => {"changed": true, "cmd": ["bin/leo_gateway", "stop"], "delta": "0:00:00.356088", "end": "2018-08-07 15:42:06.928290", "msg": "non-zero return code", "rc": 1, "start": "2018-08-07 15:42:06.572202", "stderr": "", "stderr_lines": [], "stdout": "Cannot connect Node 'G0@45.33.47.145'", "stdout_lines": ["Cannot connect Node 'G0@45.33.47.145'"]}
...ignoring

**Comment by FunnyRyan** [comment]
Aug 07 15:50:54 li997-145.members.linode.com systemd[1]: Unit leofs-gateway.service entered failed state.
Aug 07 15:50:54 li997-145.members.linode.com systemd[1]: leofs-gateway.service failed.
Aug 07 15:50:54 li997-145.members.linode.com polkitd[453]: Registered Authentication Agent for unix-process:14963:1424017 (system bus name :1.116 [/usr/bin/pkttyagent --notify-fd 5 --fallback
Aug 07 15:51:14 li997-145.members.linode.com systemd[1]: leofs-gateway.service holdoff time over, scheduling restart.
Aug 07 15:51:14 li997-145.members.linode.com systemd[1]: Starting LeoFS gateway node...
-- Subject: Unit leofs-gateway.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit leofs-gateway.service has begun starting up.
Aug 07 15:51:15 li997-145.members.linode.com leo_gateway[14969]: Config path: /usr/local/leofs/current/leo_gateway/etc
Aug 07 15:51:15 li997-145.members.linode.com leo_gateway[14969]: Exec: /usr/local/leofs/current/leo_gateway/erts-8.3/bin/erlexec -noinput -boot /usr/local/leofs/current/leo_gateway/releases/1
Aug 07 15:51:15 li997-145.members.linode.com leo_gateway[14969]: Root: /usr/local/leofs/current/leo_gateway
Aug 07 15:51:17 li997-145.members.linode.com leo_gateway[14969]: =INFO REPORT==== 7-Aug-2018::15:51:17 ===
Aug 07 15:51:17 li997-145.members.linode.com leo_gateway[14969]: Setup Lager Logger API
Aug 07 15:51:20 li997-145.members.linode.com leo_gateway[14969]: [os_mon] memory supervisor port (memsup): Erlang has closed
Aug 07 15:51:20 li997-145.members.linode.com leo_gateway[14969]: [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
Aug 07 15:51:24 li997-145.members.linode.com leo_gateway[15199]: Cannot connect Node 'G0@45.33.47.145'
Aug 07 15:51:24 li997-145.members.linode.com systemd[1]: leofs-gateway.service: control process exited, code=exited status=1
Aug 07 15:51:24 li997-145.members.linode.com systemd[1]: Failed to start LeoFS gateway node.
-- Subject: Unit leofs-gateway.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit leofs-gateway.service has failed.
-- 
-- The result is failed.
Aug 07 15:51:24 li997-145.members.linode.com systemd[1]: Unit leofs-gateway.service entered failed state.
Aug 07 15:51:24 li997-145.members.linode.com systemd[1]: leofs-gateway.service failed.
Aug 07 15:51:24 li997-145.members.linode.com polkitd[453]: Unregistered Authentication Agent for unix-process:14963:1424017 (system bus name :1.116, object path /org/freedesktop/PolicyKit1/A

**Comment by FunnyRyan** [comment]
I rebuild it again and it also doesn't work

-- Unit leofs-gateway.service has begun starting up.
Aug 07 16:22:48 li997-145.members.linode.com leo_gateway[30616]: Config path: /usr/local/leofs/current/leo_gateway/etc
Aug 07 16:22:48 li997-145.members.linode.com leo_gateway[30616]: Exec: /usr/local/leofs/current/leo_gateway/erts-8.3/bin/erlexec -noinput -boot /usr/local/leofs/current/leo_gateway/releases/1
Aug 07 16:22:48 li997-145.members.linode.com leo_gateway[30616]: Root: /usr/local/leofs/current/leo_gateway
Aug 07 16:22:49 li997-145.members.linode.com leo_gateway[30616]: =INFO REPORT==== 7-Aug-2018::16:22:49 ===
Aug 07 16:22:49 li997-145.members.linode.com leo_gateway[30616]: alarm_handler: {set,{system_memory_high_watermark,[]}}
Aug 07 16:22:51 li997-145.members.linode.com leo_gateway[30616]: =INFO REPORT==== 7-Aug-2018::16:22:51 ===
Aug 07 16:22:51 li997-145.members.linode.com leo_gateway[30616]: Setup Lager Logger API
Aug 07 16:22:54 li997-145.members.linode.com leo_gateway[30616]: [os_mon] memory supervisor port (memsup): Erlang has closed
Aug 07 16:22:54 li997-145.members.linode.com leo_gateway[30616]: [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
Aug 07 16:22:58 li997-145.members.linode.com leo_gateway[30847]: Cannot connect Node 'G0@45.33.47.145'
Aug 07 16:22:58 li997-145.members.linode.com systemd[1]: leofs-gateway.service: control process exited, code=exited status=1
Aug 07 16:22:58 li997-145.members.linode.com systemd[1]: Failed to start LeoFS gateway node.

**Comment by mocchira** [comment]
@FunnyRyan You can't use leofs_ansible with the cluster managed by systemd because currently leofs_ansible is supposed to be used with the cluster started by the startup script of each component (leo_manager|leo_storage|leo_gateway). 

we will consider to make leofs_ansible compatible with the cluster managed by systemd. Until it comes out, please consider using leofs_ansible with the startup script directly. (OR patch leofs_ansible to make it compatible with systemd by yourself. PR are always welcome.)

**Comment by FunnyRyan** [comment]
i got it

thank u

**Comment by mocchira** [comment]
I'll close this issue as it's already answered and OP seems to get it.
