### ISSUE TITLE
Something about load balance(traffic balance) ,thanks everybody...

### ISSUE THREAD

**Issue by FunnyRyan** [leo-project/leofs#1105]
I build a leofs cluster and it works fine. It contains manager0, manager1, gateway0, storage0~3.

If I add a gateway1 or more to balance traffic, what is the solution for the front of the leased gateway?

Is there any other solution for the front of the gateway besides lvs? 

I mean to divert traffic, This does not seem to be the same concept as load balance on the leofs website image.

Otherwise the bandwidth of one gateway cannot meet the requirements of uploading and downloading concurrently.

I took a picture to illustrate
http://xiaohost.com/wp-content/uploads/newimg_20180808_021440_63.png

**Comment by mocchira** [comment]
> Is there any other solution for the front of the gateway besides lvs?

Have you read the document at https://leo-project.net/leofs/docs/admin/system_admin/load_balancing/ ? I think there is the answer to your question. so If not, please read it and ask me again if you have any questions after reading it.

**Comment by mocchira** [comment]
I'll close this issue as it's already answered and no replies for a long time. please reopen if you have more questions about this topic.
