### ISSUE TITLE
The bandwidth of leofs cluster is high.

### ISSUE THREAD

**Issue by NewDund** [leo-project/leofs#1121]
- mq.num_of_batch_process_max = 100
- mq.num_of_batch_process_regular = 50
- mq.interval_between_batch_procs_max = 5000
- mq.interval_between_batch_procs_regular = 3000

This is my configuration. This is the case.

> With the above settings, I run the recover-node command and the bandwidth is fairly stable, but after the cluster runs for a day, the bandwidth increases a lot.

I don't know why. And I want some help.

**Comment by mocchira** [comment]
> With the above settings, I run the recover-node command and the bandwidth is fairly stable, but after the cluster runs for a day, the bandwidth increases a lot.

Let me confirm a couple of things. 
- the bandwidth is fairly stable during the recover-node? 
- however after a day, the bandwidth increases a lot. Has this happened after the recover-node finished?
- What does mq-stats show on each storage node while the bandwidth increases?
- Can you share ops/bandwidth of the incoming requests from gateway nodes while the bandwidth increases?
- Are there any error logs on storage/gateway nodes? if so, please share with us.

**Comment by NewDund** [comment]
First thing, I only ran recover-node, and the gateway node did not any request during recovery.
But the storage node in the recovery process, because I did a limit the initial bandwidth is relatively stable, but about a day later, the node is still in the recovery process, bandwidth increased a lot.
I share the logs and bandwidth details.

> https://github.com/NewDund/my_leofs/tree/master/1.4.2/network_traffic_log

zabbix_network_traffic.png
As you can see in this picture, we want the Leo cluster to be stable below 100M bandwidth, even in special cases, as much as possible below 200M. And we did it, but the bandwidth will increase a lot after a little longer runtime, and I don't know why. During this period, only ran the recover-node without any other requests or operation execution.

**Comment by mocchira** [comment]
@NewDund Thanks for the info.

> As you can see in this picture, we want the Leo cluster to be stable below 100M bandwidth, even in special cases, as much as possible below 200M. And we did it, but the bandwidth will increase a lot after a little longer runtime, and I don't know why. During this period, only ran the recover-node without any other requests or operation execution.

I got what you want to do now. Since It's really difficult for LeoFS to limit(control) bandwidth in such a fine grained unit, I'd recommend you another way to limit bandwidth using linux tc command (https://linux.die.net/man/8/tc) with qdisc which enables you to limit/control bandwidth in very flexible ways. (tbf or HTB Qdisc seem to great fit for limiting the bandwidth)

**Comment by NewDund** [comment]
Hello, now I want to know.
If the number of copies of the storage nodes is guaranteed to work properly, even if multiple other nodes fail. Is it possible to confirm that data loss will not occur?

**Comment by mocchira** [comment]
@NewDund 

> If the number of copies of the storage nodes is guaranteed to work properly, even if multiple other nodes fail. Is it possible to confirm that data loss will not occur?

It depends on what "fail" means and what nodes "fail".
Let's say "fail" means that a node completely get broken (never be able to get back to the cluster) then

- replicas of an object "A" are stored on node01, node02, node03
- those three nodes "failed" at the same time

then an object "A" got lost.
That being said, it's impossible to confirm that in such catastrophic failure cases.

The only thing we can do is to decrease the possibility of data loss by setting a large N, W, D in the consistency setting.

**Comment by NewDund** [comment]
I have five storage nodes "node01, node02, node03, node04, node05" and have three copies.

replicas of an object "A" are stored on node01, node02, node03

If there are two nodes randomness fails in cluster, like "node1,node3" failes, does it guarantee that data will not be lost?

**Comment by mocchira** [comment]
> If there are two nodes randomness fails in cluster, like "node1,node3" failes, does it guarantee that data will not be lost?

Not lost as long as node02 is alive.

**Comment by NewDund** [comment]
In this case, is the maximum number of n-1 machines allowed to be down?

If my cluster is already running, is there any way to change the number of copies?

**Comment by mocchira** [comment]
> In this case, is the maximum number of n-1 machines allowed to be down?

Yes.

> If my cluster is already running, is there any way to change the number of copies?

Unfortunately there are no easy ways to do so. However there are two workarounds.

1. Build a new cluster with the number of copies increased and copy all objects stored in the old cluster to the new one (you should have the list of all objects in this way)
2. Build a new cluster with the number of copies increased and use the Multi DC replication feature to copy all objects stored in the old cluster to the new one

Both workarounds require you to have one more cluster during the data migration.

**Comment by mocchira** [comment]
@NewDund Is there any unanswered problems here? if not, then please close the issue.
