### ISSUE TITLE
[leofs] Make it work with OTP 21

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#1130]
The TODO list which should be done for OTP 21.

- error_logger has no longer started by default according to http://erlang.org/doc/man/error_logger.html so we have to start it explicitly

As we find something new to be added into the list, we'll add.

**Comment by yosukehara** [comment]
I've done to be able to build LeoFS with [Erlang/OTP 21.0](http://www.erlang.org/news/123). Its commits are as below:

- https://github.com/leo-project/leofs/commit/ce4b24627acd35853b0a07af3e59176378149c65
- https://github.com/leo-project/leofs/commit/cf8ee18c831aac5d1136bd6d803bc87c81842791
- https://github.com/leo-project/leofs/commit/fd946438016965893ca77a92972e40d6e1b16806
- https://github.com/leo-project/leofs/commit/034e5453376f4320b3cf3f4b72de40b3529c8dd8
- https://github.com/leo-project/leofs/commit/26d908fbba53a3b3b3aeb8bbc16a863ac3525237

### The version of the libraries
#### Leo Project

* [leo_backend_db v1.2.31](https://github.com/leo-project/leo_backend_db/releases/tag/1.2.31)
* [leo_cache v0.8.12](https://github.com/leo-project/leo_cache/releases/tag/0.8.12)
* [leo_commons v1.2.1](https://github.com/leo-project/leo_commons/releases/tag/1.2.1)
* [leo_dcerl v0.4.11](https://github.com/leo-project/leo_dcerl/releases/tag/0.4.11)
* [leo_logger v1.3.8](https://github.com/leo-project/leo_logger/releases/tag/1.3.8)
* [leo_mcerl v0.6.9](https://github.com/leo-project/leo_mcerl/releases/tag/0.6.9)
* [leo_mq v1.5.19](https://github.com/leo-project/leo_mq/releases/tag/1.5.19)
* [leo_object_storage v1.3.37](https://github.com/leo-project/leo_object_storage/releases/tag/1.3.37)
* [leo_ordning_reda v1.2.11](https://github.com/leo-project/leo_ordning_reda/releases/tag/1.2.11)
* [leo_pod v0.6.10](https://github.com/leo-project/leo_pod/releases/tag/0.6.10)
* [leo_redundant_manager 1.9.64](https://github.com/leo-project/leo_redundant_manager/releases/tag/1.9.64)
* [leo_rpc v0.10.18](https://github.com/leo-project/leo_rpc/releases/tag/0.10.18)
* [leo_s3_libs v1.2.21](https://github.com/leo-project/leo_s3_libs/releases/tag/1.2.21)
* [leo_statistics v1.1.23](https://github.com/leo-project/leo_statistics/releases/tag/1.1.23)
* [leo_tran v0.2.14](https://github.com/leo-project/leo_tran/releases/tag/0.2.14)
* [leo_watchdog v1.0.7](https://github.com/leo-project/leo_watchdog/releases/tag/1.0.7)
* [savanna_agent v0.4.26](https://github.com/leo-project/savanna_agent/releases/tag/0.4.26)
* [savanna_commons v0.10.12](https://github.com/leo-project/savanna_commons/releases/tag/0.10.12)
* [erpcgen v0.2.7](https://github.com/leo-project/erpcgen/releases/tag/0.2.7)
* [nfs_rpc_server v0.2.7](https://github.com/leo-project/nfs_rpc_server/releases/tag/0.2.7)

#### Others

* [folsom v0.8.2.3](https://github.com/leo-project/folsom/releases/tag/0.8.2.3)

**Comment by mocchira** [comment]
@yosukehara It's not unclear whether those changes have affected but Circle CI tests keep failing after those changes.

**Comment by yosukehara** [comment]
I recognized that. I’ve been checking this cause from yesterday. I’ll fix that today or tomorrow.

**Comment by yosukehara** [comment]
I've just recognized `mp_upload_abort` test of leofs-test2's 1st scenario failed on my environment.

```erlang
   * mp_upload_abort (abort multipart upload)
        #1
            * 'storage_0@127.0.0.1':[{leo_delete_dir_queue_1,2}]
            * 'storage_1@127.0.0.1':[{leo_delete_dir_queue_1,2}]
            * 'storage_2@127.0.0.1':[{leo_delete_dir_queue_1,2}]
            * 'storage_3@127.0.0.1':[{leo_delete_dir_queue_1,3}]
        #2
            * 'storage_0@127.0.0.1':[{leo_delete_dir_queue_1,1}]
            * 'storage_1@127.0.0.1':[{leo_delete_dir_queue_1,1}]
            * 'storage_2@127.0.0.1':[{leo_delete_dir_queue_1,2}]
            * 'storage_3@127.0.0.1':[{leo_delete_dir_queue_1,1}]
        #3
            * 'storage_0@127.0.0.1':[N/A]
            * 'storage_1@127.0.0.1':[{leo_delete_dir_queue_1,1}]
            * 'storage_2@127.0.0.1':[N/A]
            * 'storage_3@127.0.0.1':[N/A]
        #4
            * 'storage_0@127.0.0.1':[N/A]
            * 'storage_1@127.0.0.1':[N/A]
            * 'storage_2@127.0.0.1':[N/A]
            * 'storage_3@127.0.0.1':[N/A][ERROR] Multipart Upload some part objects left. key:["backup/test/mp/abort"]
```

It's a same situation with [circleci.com/gh/leo-project/leofs/272](https://circleci.com/gh/leo-project/leofs/272). I'm going to check this issue again.

**Comment by mocchira** [comment]
It turns out that https://github.com/leo-project/leo_object_storage/commit/e13f61338dde444164ea032bd5af4a26252fca70 causes leo_storage to crash randomly on Docker environment so I'm going to rollback the commit and check if it works on Circle CI.

**Comment by mocchira** [comment]
Recovered as shown on https://circleci.com/workflow-run/a26131fe-0c0f-4bb0-9b2e-743b90afd56f so I'll close the issue.
