### ISSUE TITLE
Content-Type not being stored / returned properly

### ISSUE THREAD

**Issue by asphytotalxtc** [leo-project/leofs#1135]
Hey Guys, 

Something I've just noticed, the Content-Type header does not appear to be correct when getting objects (using s3), see the following PUT and subsequent get requests:

```
PUT /1409e9ac5e55877d47ea.mobileforms.mf-attachments.binfile/49/58186877.dat HTTP/1.1
User-Agent: aws-sdk-nodejs/2.313.0 linux/v8.10.0 callback
x-amz-acl: private
Content-Type: image/jpeg
x-amz-meta-createdby: MFS FUSE Wrapper
x-amz-meta-mime-type: image/jpeg
Content-MD5: sYH/xNW5vYIv1ZADolapTA==
Content-Length: 44089
Host: leofs-2.dc2.dmz.aeromark.co.uk:8080
X-Amz-Date: Thu, 27 Sep 2018 14:01:48 GMT
Authorization: AWS 1409e9ac5e55877d47ea:YxQyeaFrdQz4OUv709J4oZMSVuU=
Connection: close

......JFIF.............C........................... [snip]
```

And then when retrieving the object

```
GET /1409e9ac5e55877d47ea.mobileforms.mf-attachments.binfile/49/58186877.dat HTTP/1.1
User-Agent: aws-sdk-nodejs/2.313.0 linux/v8.10.0 callback
Content-Length: 0
Host: leofs-2.dc2.dmz.aeromark.co.uk:8080
X-Amz-Date: Thu, 27 Sep 2018 14:01:52 GMT
Authorization: AWS 1409e9ac5e55877d47ea:DLxlGiV19Tk7cp0SmS/iOf320Xk=
Connection: close

HTTP/1.1 200 OK
Connection: close
Date: Thu, 27 Sep 2018 14:01:51 GMT
Content-Length: 44089
x-amz-meta-mime-type: image/jpeg
x-amz-meta-createdby: MFS FUSE Wrapper
Server: LeoFS
Content-Type: application/octet-stream
ETag: "b181ffc4d5b9bd822fd59003a256a94c"
Last-Modified: Thu, 27 Sep 2018 14:01:48 GMT
x-amz-meta-leofs-from-cache: True/via memory
X-From-Cache: True/via memory

......JFIF.............C........................... [snip]
```

Everything seems to be given the content-type of application/octet-stream, am I doing something wrong? Or perhaps content-types aren't supported maybe?

This is using latest v1.4.2 at the moment :) Currently I'm working around this by setting a custom mime-type metadata header so it's not a showstopper.

Dan

edit: markdown

**Comment by mocchira** [comment]
@asphytotalxtc You are right. Now LeoFS behaves differently from aws s3 in case handling the Content-Type header in request. When responding a GET request, LeoFS set the Content-Type header to a MIME type deduced by the suffix of the object (in your case, "dat") so that if the object name was 58186877.jpg or 58186877.jpeg then LeoFS set the Content-Type to "image/jpeg" as you intended.

We'd like to consider to comply with aws s3 spec in this case.

**Comment by yosukehara** [comment]
@mocchira I've remembered we discussed that few months ago.

When LeoGateway received PUT request which include "Content-Type" in the http-header, it'll register "Content-Type" into its user-defined metadata to set expected "Content-Type" when requesting GET/HEAD of the object.

**Comment by mocchira** [comment]
@asphytotalxtc We've come to the conclusion that we will comply with the s3 spec so that the fix will be included in 1.4.3. Anyway, thanks for reporting the issue as always.

**Comment by asphytotalxtc** [comment]
Thanks guys! Awesome support as always :) 👍 

Unfortunately, I'm implementing LeoFS into a very legacy application here and need to maintain the original filenames. The old system used to store everything as [numbers].dat regardless of what the original filename was so the content type header was pretty important for us lol.

**Comment by mocchira** [comment]
IMPL details for devs

- Add the Content-Type to Headers here: https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/src/leo_gateway_s3_api.erl#L1479
- Replace leo_mime:guess_mime with something new like `retrieve_mime_and_udm_from_cmeta` at
  - https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/src/leo_gateway_http_commons.erl#L375
  - https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/src/leo_gateway_http_commons.erl#L421
  - https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/src/leo_gateway_http_commons.erl#L582
  - https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/src/leo_gateway_http_commons.erl#L621
  - https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/src/leo_gateway_http_commons.erl#L1079
  - https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/src/leo_gateway_http_commons.erl#L1135
  - except https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/src/leo_gateway_http_commons.erl#L840 . At this point, we have the custom metadata in a different format ([{?PROP_CMETA_UDM, CMeta}]), take another approach to retrieve those info as shown lines below
    - https://github.com/leo-project/leofs/blob/v1/apps/leo_gateway/src/leo_gateway_http_commons.erl#L841-L868

**Comment by mocchira** [comment]
Close as the fix got merged into the v1 branch.
