### ISSUE TITLE
LeoFS - what is it best for?

### ISSUE THREAD

**Issue by mrPsycho** [leo-project/leofs#1180]
Hello,

its hard to understand, what it suits.
for example, i see NFS support... but cant find on site - how it is did? 

for example - is it possible to use LeoFS for hosting git repositories?
Idea is deploy git server on AWS Fargate... but, there is problem with persistent data... and one of solutions - using ec2 and docker in it. Where it is possible to mount NFS.

So, main question: Is it possible to use LeoFS in docker to access NFS? 
And second: what are best practices for it? What scenarios fit best?

**Comment by yosukehara** [comment]
We provide NFS v3 on LeoGateway of LeoFS as a complement to S3-API and Rest-API. Read [FAQ: LeoFS Limits / NFS Support](https://leo-project.net/leofs/docs/faq/limits/#nfs-support) and consider where/how to use its protocol.

**Comment by mrPsycho** [comment]
i see, thanks... re-read it several times, and understood... thanks!
