### ISSUE TITLE
[Question] Suitability for clustered production filesystem

### ISSUE THREAD

**Issue by zicklag** [leo-project/leofs#1183]
Hi, I was evaluating LeoFS and was wondering whether or not you would suggest it to back production applications as a generic filesystem using the NFS api. I'm trying to find a clustered, highly available filesystem that I can integrate with my Docker Swarm cluster to provide Docker volumes. The volumes will be used for anything from website attachment storage to MySQL/Postgres/etc. database storage.

I got a single node instance running and I tested out the NFS mount, but I noticed that none of the filesystem permissions ( mode, owner, and group ) were being persisted. Is this a known limitation or have I got something configured incorrectly?

I would also need a way to cluster the gateway for high availability and I'm not sure if it is possible to accomplish that when using NFS because of the need to automatically fail-over to the other gateway if one fails.

I appreciate any insight. Thanks!

**Comment by mocchira** [comment]
> I got a single node instance running and I tested out the NFS mount, but I noticed that none of the filesystem permissions ( mode, owner, and group ) were being persisted. Is this a known limitation or have I got something configured incorrectly?

Unfortunately It's a known limitation (still not implemented yet and there is no plan to do so for now).

> I would also need a way to cluster the gateway for high availability and I'm not sure if it is possible to accomplish that when using NFS because of the need to automatically fail-over to the other gateway if one fails.

Since LeoFS don't have built-in fail-over feature for NFS mount, you would have to build something fail-over architecture out of LeoFS(ex. monitoring whether or not a mount point works and fail-over(mount) to another healthy gateway once the monitoring detect a certain time failure)

**Comment by zicklag** [comment]
OK, thanks, that helps. :slightly_smiling_face: :+1:
