### ISSUE TITLE
Question: How LeoFS communicate between storage nodes?

### ISSUE THREAD

**Issue by tnatanael** [leo-project/leofs#1186]
I have seen other distributed file projects that uses Http API to communicate between nodes, i am trying to understand what is the strategy LeoFS uses to replicate the files between storage nodes? Is there a persistent network connection and specific data transmission protocol? Or it uses HTTP requests to replicate the data?

**Comment by yosukehara** [comment]
We’ve been publishing LeoFS’ documentation, which includes [LeoFS Documentation / LeoFS’ Architecture](https://leo-project.net/leofs/docs/architecture/README/).

**Comment by tnatanael** [comment]
Really thanks for your quick reply, i see in the docs that inter node communication uses Erlang EPC module, is it true for the "files data" transmission part also?

**Comment by yosukehara** [comment]
> is it true for the "files data" transmission part also?

Exactly

**Comment by tnatanael** [comment]
Thanks man!
