### ISSUE TITLE
mdc_replication.max_targets for 3-way replication

### ISSUE THREAD

**Issue by bernardx** [leo-project/leofs#1203]
I'm trying to add a three datacenter replication using the "join-cluster" command. The mdc_replication.max_targets was set to 3. 

The first dc is added without any problem. However,  while I'm trying to add the second one, it shows: "Over max number of clusters".
 
Maybe MaxTargets should be larger than length(Rows) to allow add more replication?
https://github.com/leo-project/leofs/blob/c1ea6859294cf6f31e831d407a8600bf2afc3f73/apps/leo_manager/src/leo_manager_console.erl#L1242
```
-----------------------------------+----------
 [mdcr] max number of joinable DCs | 3
 [mdcr] total replicas per a DC    | 1
 [mdcr] number of successes of R   | 1
 [mdcr] number of successes of W   | 1
 [mdcr] number of successes of D   | 1

cluster id |   dc id    |    status    | # of storages  |          updated at         
-----------+------------+--------------+----------------+-----------------------------
leofs_cn0  | dc_cn0     | running      |              1 | 2020-07-05 04:20:18 +0000
```

**Comment by yosukehara** [comment]
I'm sorry it took me a while to get back to you.
The current version of LeoFS only supports one remote cluster replication.
