### ISSUE TITLE
[leo_rpc]Performance degradation due to leaking tcp connections

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#141]
Under very high load, there are some possibilities that a LeoFS throughput degrades due to leaking tcp connections corresponding with Erlang processes.
But since leo_rpc will be used under a relatively low load, this is not critical for now.

**Comment by mocchira** [comment]
Since it turned out that bulk-loading 10,000 objects with the mdc default settings can easily reproduce this issue, so we've looked into now.

Not using tcp connection pool might be most easiest solution.(in my local env, this works)

**Comment by mocchira** [comment]
This feature branch have fixed this issue by disabling tcp connection pool.
https://github.com/leo-project/leo_rpc/tree/feature/disable_connection_pool

**Comment by yosukehara** [comment]
I've fixed this issue https://github.com/leo-project/leo_rpc/commit/92e28ee1af9e62cb254071eb1b9762d47d033585 then we need to check the mdc-replication mechanism through stress-tests and benchmarks more and more.

**Comment by mocchira** [comment]
@yosukehara We still have tcp leaking issues on the latest develop branch.
The below error continue to generate on leo_storage(s).
```
 [W] storage_0@127.0.0.1 2015-03-31 01:46:45.543806 +0000    1427766405  leo_sync_remote_cluster:defer_stack/1        82  key:test/1662, cause:sending_data_to_remote
```

**Comment by yosukehara** [comment]
@mocchira Thank you for sharing the info. I'll try to check this issue again.

**Comment by yosukehara** [comment]
I've benchmarked leo_pc with large files, the result of which is as follows.
I could not face the issues then I'll check behavior of LeoFS Storage as the next step.

#### leo_rpc's benchmark result:
![leo_rpc_bench_result_32mb](https://cloud.githubusercontent.com/assets/148770/6912701/5c29296a-d7b0-11e4-821f-8a42b38bc30c.png)

#### basho_bench configuration file:
```erlang
{mode, max}.
{duration, 10}.
{concurrent, 64}.
{remote_node_ip,   "127.0.0.1"}.
{remote_node_port, 13076}.
{driver, basho_bench_driver_leo_rpc}.
{key_generator, {int_to_bin_bigendian, {uniform_int, 1}}}.
{value_generator, {fixed_bin, 33554432}}. %% 32MB
```

**Comment by mocchira** [comment]
I found out  the root causes of this issue.
There are two problems.

## Process leak
Processes for rpc connections manged by leo_pod coudn't stop properly.
https://github.com/leo-project/leo_pod/commit/391607c8be12652925fd12920f8db7b0bf9f9030 have fixed part of this issue.

## Erlang's accept(connect) behaviour
If the number of active tcp connections exceed the rpc.num_of_acceptor, 
leo_rpc_client_conns can succeed in connecting to a server but can't send/recv any data on this socket.
To solve this problem, 
Quick fix is to set a sufficient large value to rpc.num_of_acceptor which depends on the number of storage nodes.

**Comment by yosukehara** [comment]
I've understood that. As your mentioned, we should adopt "not use connection pool" in the next LeoFS's version.

**Comment by yosukehara** [comment]
In this solution, I've found errors and performance degradation as below. So I'll consider better/best solution of this issue.

```
17:40:55.749 [error] gen_server leo_rpc_client_manager terminated with reason: {{timeout,{gen_server,call,[<0.235.0>,stop]}},{gen_server,call,[<0.230.0>,raw_status]}} in gen_server:call/2 line 182
17:40:55.749 [error] CRASH REPORT Process leo_rpc_client_manager with 0 neighbours exited with reason: {{timeout,{gen_server,call,[<0.235.0>,stop]}},{gen_server,call,[<0.230.0>,raw_status]}} in gen_server:terminate/7 line 804
17:40:55.750 [error] Supervisor leo_rpc_client_sup had child leo_rpc_client_manager started with leo_rpc_client_manager:start_link(5000) at <0.99.0> exit with reason {{timeout,{gen_server,call,[<0.235.0>,stop]}},{gen_server,call,[<0.230.0>,raw_status]}} in context child_terminated
```

**Comment by yosukehara** [comment]
I've provided an another solution, which disconnect a connection when reach *[rpc.client.max_requests_for_reconnection](https://github.com/leo-project/leo_storage/blob/develop/priv/leo_storage.conf#L337)*.

```bash
## RPC-Client's max number of requests for reconnection to a remote-node
## * 1..<integer>: specialized value
rpc.client.max_requests_for_reconnection = 64
```

**Comment by yosukehara** [comment]
Also, I've taken a measure of the rpc-server - https://github.com/leo-project/leo_rpc/commit/2decc072c402a1fa89bca7aae55a34f41af548f8 ,which close unnecessary connections when reached timeout.

**Comment by mocchira** [comment]
We finally have fixed this issue by https://github.com/leo-project/leo_rpc/commit/3be4287522597003e0261444653dcd71d7c2e32e.

**Comment by yosukehara** [comment]
I've checked this issue again and then recognized this issues was fixed.

* Server configuration:
```erlang
{num_of_acceptors, 2}. %% default:128
{listen_port,    13076}.
{listen_timeout,  5000}.
{max_requests_for_reconnection, 64}.
```

* Client(bench marker) configuration:
```erlang
{mode, max}.
{duration, 10}.
{concurrent, 8}.
{remote_node_ip,   "127.0.0.1"}.
{remote_node_port, 13076}.
{driver, basho_bench_driver_leo_rpc}.
{key_generator, {int_to_bin_bigendian, {uniform_int, 1}}}.
{value_generator, {fixed_bin, 1024}}.
```

* Result:
![leo_rpc_benchmark_1kb_20150402_1](https://cloud.githubusercontent.com/assets/148770/6957136/13f44a88-d933-11e4-89ff-9a75041dbb6a.png)
