### ISSUE TITLE
content type is not set when using ruby aws-sdk

### ISSUE THREAD

**Issue by necrodome** [leo-project/leofs#179]
I am using leofs from master with aws-sdk (1.39.0) gem on 
$ uname -a
Linux ubuntu 3.11.0-20-generic #34-Ubuntu SMP Tue Apr 1 20:40:25 UTC 2014 x86_64 x86_64 x86_64

When I try to set content_type for file uploads, content-type is always saved as "application/octet-stream" regardless of what I submit

snippet from the ruby code I am using:

``` ruby
 bucket = @s3.buckets["docs"]
 o = bucket.objects[SecureRandom.hex].write(file: file, content_type: "plain/text")
 o.head # {:meta=>{}, :restore_in_progress=>false, :content_type=>"application/octet-stream", :etag=>"\"66dd95700a074704cb6caf7b2eedbc10\"", :last_modified=>2014-04-29 06:22:38 -0400, :content_length=>992}
```

**Comment by mocchira** [comment]
We've recently complied with the aws-s3 spec as described on https://mocchira.github.io/leofs/admin/protocols/s3/#how-to-deal-with-content-type-request-header-on-put (the above document will be published on the official document once 1.4.3 comes out) so I'll close the issue.
