### ISSUE TITLE
[leo_s3_libs]Authenticating requests(AWS Signature version4) to be implemented

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#283]
In future, probably v2 requests will be banned...
http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

**Comment by mocchira** [comment]
@windkit Thank you for coming to here!

Since this feature will be included in 1.4pre2, 
please work on 1.4 branch.
you can build 1.4 as below.

```
cd $LEO_ROOT_DIR
rm -rf deps
git checkout 1.4
make
make release
```

We already have 4 repos which branch are 1.4.
 - leo_manager
 - leo_storage
 - leo_gateway
 - leo_object_storage

If you modify those 4 repos, please PR to 1.4 branch.
If you need to modify other repos to realise this feature, please let us know. we will make 1.4 branch for that.

**Comment by windkit** [comment]
@mocchira Thanks for the information.

`leo_s3_libs` would also need changes, please also help to make a branch for that

**Comment by yosukehara** [comment]
@windkit leo_s3_libs is also ``1.4`` branch. I'll create it soon.

**Comment by yosukehara** [comment]
We've almost fixed this ticket. Our remain tasks are to check the aws-signature-v4 support with [s3-cliensts](https://github.com/leo-project/leofs_client_tests).

* reference: [a benchmark result for the aws-signature-v4 support](https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/aws_signature_v4/20150714_cluster_r49w1)
