### ISSUE TITLE
[leo_backend_db]No need to compact metadatas when using LevelDB

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#289]
Since `LevelDB`|`RocksDB` does compaction itself as necessary, 
LeoFS doesn't need to reconstruct the metadata when doing compaction.

**Comment by yosukehara** [comment]
I agree with your opinion. So I'll fix this issue soon.

**Comment by yosukehara** [comment]
Actually, I've recognized ``leo_object_storage`` needs to be able to **rollback operation**. So ``leo_object_storage`` makes the necessary to create a new metadata file. 

In conclusion, I've decided still keep the current code.
