### ISSUE TITLE
Does Leofs provide disk-level fault tolerance?

### ISSUE THREAD

**Issue by ZhaoX** [leo-project/leofs#291]
If I use more than one disks on single leo_storage node and one of them failure, what would be happen? Can I hot-plug/hot-unplug the disks on the fly?

Related configuration is like this:
obj_containers.path = [/path/to/disk1, /path/to/disk2, ...]

**Comment by yosukehara** [comment]
We does not support ``disk-level fault tolerance`` but we provide  the [recover-node](http://leo-project.net/leofs/docs/admin_guide/admin_guide_4.html#recover-node-command) command. You're able to repair data(objects) of the node with it.

**Comment by ZhaoX** [comment]
Thank you for your reply. When one of disks in a running storage node is broken, what's the correct repair workflow? 

Another related question. Should a redundant array of independent disks (RAID) be used, and if so, how?

**Comment by yosukehara** [comment]
The correct repair workflow is as follows:

* Suspend a target node with [the suspend-command](http://leo-project.net/leofs/docs/admin_guide/admin_guide_3.html#suspend-command) with ``leofs-adm command``
* Stop the node with ``$ path/to/leo_storage/bin/leo_storage stop``
* Confirm the cluster status with [the status-command](http://leo-project.net/leofs/docs/admin_guide/admin_guide_2.html#status-command) with leofs-adm command
    * You need to check the node whether state of  which is ``suspend`` or not.
* **Change the disk(s) (rebuild the array when using RAID)  and the configuration of the target node**
* Restart the node with ``$ path/to/leo_storage/bin/leo_storage start``
* Resume a target node with [the resume-command](http://leo-project.net/leofs/docs/admin_guide/admin_guide_3.html#resume-command) with leofs-adm command
* Execute [the recover-node-command](http://leo-project.net/leofs/docs/admin_guide/admin_guide_4.html#recover-node-command) with leofs-adm command
    * Like this: ``$ leofs-adm recover-node <target-node>``
* Also, you're able to check the progress of the recover with [the mq-stats-command](http://leo-project.net/leofs/docs/admin_guide/admin_guide_3.html#mq-stats-command) with leofs-adm command
    * Like this (exclude the target node): 
        * ``$ leofs-adm mq-stats <storage-node-1>``
        * ...
        * ``$ leofs-adm mq-stats <storage-node-N>``

> Another related question. Should a redundant array of independent disks (RAID) be used, and if so, how?

The workflow is similar to the above flow. And also, LeoFS handles files/objects regardless of local file systems (EXT4, XFS and others) or RAID.

See also:
* [LeoFS documentation](http://leo-project.net/leofs/docs/index.html)
* [leofs-adm command](https://github.com/leo-project/leofs/blob/master/leofs-adm)

**Comment by ZhaoX** [comment]
Great answers! Thank you very much.
