### ISSUE TITLE
[All] Some error handling are not existant

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#295]
As follows.

- leo_cache
  - https://github.com/leo-project/leo_cache/blob/develop/src/leo_cache_api.erl#L73
  - https://github.com/leo-project/leo_cache/blob/develop/src/leo_cache_api.erl#L74
  - https://github.com/leo-project/leo_cache/blob/develop/src/leo_cache_api.erl#L75

- leo_commons
  - https://github.com/leo-project/leo_commons/blob/develop/src/leo_misc.erl#L100

- leo_manager
  - https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_cluster_monitor.erl#L283
  - https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_cluster_monitor.erl#L288
  - https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_ring_sync.erl#L146
  - https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_table_sync.erl#L346
  - https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_table_sync.erl#L349
  - https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_table_sync.erl#L352
  - https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_table_sync.erl#L355

- leo_object_storage
  - https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_api.erl#L458
  - https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_api.erl#L460
  - https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_sup.erl#L103
  - https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_sup.erl#L105

- leo_ordning_reda
  - https://github.com/leo-project/leo_ordning_reda/blob/develop/src/leo_ordning_reda_api.erl#L105
  - https://github.com/leo-project/leo_ordning_reda/blob/develop/src/leo_ordning_reda_api.erl#L106

- leo_redundant_manager
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_cluster_local.erl#L227
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_cluster_local.erl#L228
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_cluster_local.erl#L230
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_cluster_local.erl#L234
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_cluster_local.erl#L251
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_cluster_local.erl#L296
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_cluster_remote.erl#L119
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_cluster_remote.erl#L171
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_cluster_remote.erl#L204
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_membership_mq_client.erl#L220
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_cluster_tbl_member.erl#L69
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_worker.erl#L246
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_worker.erl#L305
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_sup.erl#L262
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_sup.erl#L263
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_sup.erl#L264
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_sup.erl#L265
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_api.erl#L551
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_api.erl#L552
  - https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_api.erl#L553

- leo_rpc
  - https://github.com/leo-project/leo_rpc/blob/develop/src/leo_rpc_sup.erl#L70

- leo_s3_libs
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_auth.erl#L63
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_auth.erl#L64
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_auth.erl#L74
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_auth.erl#L95
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_bucket.erl#L66
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_bucket.erl#L67
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_bucket.erl#L78
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_bucket.erl#L826
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_bucket.erl#L832
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_endpoint.erl#L50
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_endpoint.erl#L51
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_endpoint.erl#L61
  - https://github.com/leo-project/leo_s3_libs/blob/develop/src/leo_s3_endpoint.erl#L83

- leo_statistics
  - https://github.com/leo-project/leo_statistics/blob/develop/src/leo_statistics_snmpm.erl#L43
  - https://github.com/leo-project/leo_statistics/blob/develop/src/leo_statistics_sampler.erl#L95

- leo_storage
  - https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_mq.erl#L460
  - https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_mq.erl#L461
  - https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_mq.erl#L806
  - https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_mq.erl#L812
  - https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_api.erl#L474

- leo_watchdog
  - https://github.com/leo-project/leo_watchdog/blob/develop/src/leo_watchdog.erl#L133
  - https://github.com/leo-project/leo_watchdog/blob/develop/src/leo_watchdog_sub.erl#L136
  - https://github.com/leo-project/leo_watchdog/blob/develop/src/leo_watchdog_sub.erl#L146
  

Those points must be added  appropriate error handlings or output error logs.
(This work still in progress)

**Comment by yosukehara** [comment]
In 1st step, we check them whether they need to take measure of error handling or NOT.

**Comment by yosukehara** [comment]
I've checked this issue from all of current Leo's libs. All of object of code don't be critical.
To this day, we fixed all of critical code.
