### ISSUE TITLE
[docs] Firewall rules for ports used by distributed Erlang missing

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#298]
The port range between `inet_dist_listen_min`  AND `inet_dist_listen_max`  need to be added in this  page (http://leo-project.net/leofs/docs/installation/install_4.html).

**Comment by yosukehara** [comment]
@mocchira It is great if you modify this page.

**Comment by mocchira** [comment]
Looks like this.
http://ec2-54-178-53-107.ap-northeast-1.compute.amazonaws.com/docs/installation/install_4.html
