### ISSUE TITLE
[leo_storage]Replication messages could be lost in some edge cases

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#301]
https://github.com/leo-project/leo_storage/commit/22a1287c052e6b5dda6760d31e46d1971c4a7d3c this commit shoud fix this issue.

**Comment by yosukehara** [comment]
I've fixed this issue as follows:

https://github.com/leo-project/leo_storage/commit/350b7167125f45bbe551648a3e7cb7ba2cdd1ab9
https://github.com/leo-project/leo_storage/commit/3fd6bf5a36a85350c4d6dd33d0885dff86ba63a2
https://github.com/leo-project/leo_storage/commit/22a1287c052e6b5dda6760d31e46d1971c4a7d3c

And also, I've check it with [leofs_test2](https://github.com/leo-project/leofs_test2)

**Comment by mocchira** [comment]
I've confirmed on my envs.
