### ISSUE TITLE
[All] Calling error_logger directly should be relaced with leo_logger for safe

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#303]
Calling error_logger directly might cause a problem when the system load is getting too high.

**Comment by yosukehara** [comment]
Actually, we already support this issue. ``error_logger`` call leo_logger's function via [gen_event](http://www.erlang.org/doc/man/gen_event.html), which calls [leo_logger_error_logger_h.erl](https://github.com/leo-project/leo_logger/blob/develop/src/leo_logger_error_logger_h.erl).

So I've closed this issue.
