### ISSUE TITLE
[All] infinity should be replaced with an appropriate value

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#304]
infinity might cause a dead lock in some edge cases.

**Comment by mocchira** [comment]
- https://github.com/leo-project/leo_gateway/blob/develop/src/leo_large_object_put_handler.erl#L101
- https://github.com/leo-project/leo_gateway/blob/develop/src/leo_large_object_get_handler.erl#L95
- https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_api.erl#L725
- https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_api.erl#L985
- https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_server.erl#L298
- https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager.erl#L80
- https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_worker.erl#L142

**Comment by yosukehara** [comment]
Here is the current code, v1.2.18's dev:
```bash
$ grep infinity leo*/src/*.erl -n
## Gateway
leo_gateway/src/leo_gateway_http_commons.erl:814:get_body_length([{Start, infinity}|Rest], ObjectSize, Acc) ->
leo_gateway/src/leo_gateway_http_commons.erl:832:get_range_object_1(Req, Bucket, Key, [{Start, infinity}|Rest], _, TransportRec) ->
leo_gateway/src/leo_large_object_get_handler.erl:97:  gen_server:call(Pid, {get, TotalOfChunkedObjs, Req, Meta}, infinity).
leo_gateway/src/leo_large_object_put_handler.erl:101: gen_server:call(Pid, result, infinity).

## Others
leo_object_storage/src/leo_object_storage_server.erl:300: NumOfActiveObjs, SizeOfActiveObjs}, infinity).
leo_redundant_manager/src/leo_redundant_manager.erl:62:-define(DEF_TIMEOUT_LONG, infinity).
leo_redundant_manager/src/leo_redundant_manager_worker.erl:63:-define(DEF_TIMEOUT_LONG,  infinity).
leo_redundant_manager/src/leo_redundant_manager.erl:81:    gen_server:call(?MODULE, {create, Ver}, ?DEF_TIMEOUT_LONG).
leo_redundant_manager/src/leo_redundant_manager_worker.erl:143:    gen_server:call(?MODULE, {force_sync, Table}, ?DEF_TIMEOUT_LONG).
```
