### ISSUE TITLE
[leo_storage][leo_gateway] Could not synchronize 'suspend' status at each gateway and storage nodes

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#308]
* the error log is as follows:
```
=ERROR REPORT==== 17-Feb-2015::13:21:34 ===
Error in process <0.270.0> on node 'test@127.0.0.1' with exit value: 
{{{aws_error,{http_error,500,"Internal Server Error",
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <Error><Code>InternalError</Code>
    <Message>We encountered an internal error. Please try again.</Message><Resource>...
```

**Comment by mocchira** [comment]
https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager.erl#L574 
This is where suspend status overwrites running status.

**Comment by yosukehara** [comment]
here is related issue - https://github.com/leo-project/leofs/issues/309

**Comment by yosukehara** [comment]
We've fixed this issue.

Commit log:
* https://github.com/leo-project/leo_redundant_manager/commit/d657fcf5e5e530bbb03e8a8b7bed5975cf813e09
* https://github.com/leo-project/leo_redundant_manager/commit/93bf43740760a8a28e9f1d68c1f6bdb4fbd88211
* https://github.com/leo-project/leo_manager/commit/c28d379522324f01219f9a6a8b08f8a96e5d08b3
* https://github.com/leo-project/leo_manager/commit/8cb2a1b69455417246fc14b9129fd1b834a9c21c
