### ISSUE TITLE
[leo_redundant_manager] ring status to be synced between mnesia and worker state

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#309]
`mnesia:subscribe` enable us to implement this feature.
http://www.erlang.org/doc/apps/mnesia/Mnesia_chap5.html#id76669

**Comment by yosukehara** [comment]
I've fixed this issue and implemented two ways of synchronization of a ring status.
* Handling ``mnesia`` events to synchronize a ring state immediately
* Monitoring a ring state with leo_manager's node to fix inconsistent a ring state

Commit logs:
* https://github.com/leo-project/leo_manager/commit/cd353e28fef82ba34e8f9fe01b77c42fa61f7f0b
* https://github.com/leo-project/leo_redundant_manager/commit/6be1eed5bf1fcf44a46a5b6a674dc949bf73f8e9
* https://github.com/leo-project/leo_redundant_manager/commit/77ab99d296a7a1b56af6f43cf7aa12130d850a71
