### ISSUE TITLE
Couldn't access by Ruby Client(aws-sdk v2)

### ISSUE THREAD

**Issue by firejun** [leo-project/leofs#312]
I couldn't access to LeoFS cluster by new ruby client(v2).
Maybe new client’s request of 'access_key_id' enclose double quotation.

v2 result:
```
GET http://dummy.com:8080/ HTTP/1.1
Content-Type:
Accept-Encoding:
User-Agent: aws-sdk-ruby2/2.0.26 ruby/2.1.2 x86_64-linux
Date: Fri, 20 Feb 2015 07:20:48 GMT
Authorization: AWS "f0bdd44a4a10ef53f7d2":+9BgAUk1JoHQUXEPIGrrPZI1qZQ=
Content-Length: 0
Accept: */*
Host: dummy.com:8080
```
v1 result:
```
GET / HTTP/1.1
Content-Type:
Accept-Encoding:
User-Agent: aws-sdk-ruby/1.63.0 ruby/2.1.2 x86_64-linux
Date: Fri, 20 Feb 2015 07:21:25 GMT
Authorization: AWS f0bdd44a4a10ef53f7d2:xb2GgxaeDCAUVCsKnmhihAt5RbM=
Accept: */*
Host: dummy.com:8080
```

**Comment by yosukehara** [comment]
Thank you for posting this issue. We'll check it soon.

**Comment by firejun** [comment]
New version(2.0.27) was released 21 Feb.
I tried to test it. Result is good.
This issue has resolved.

**Comment by yosukehara** [comment]
Thank you for testing this issue, again.
If we could not face the same situation, we'll close this.

**Comment by mocchira** [comment]
We've confirmed that the latest aws-sdk-ruby(2.0.27) with the latest leofs(1.2.6) works as expected.
