### ISSUE TITLE
[leo_manager] Calling leo_manager_api:get_members_of_all_versions get timeout on leo_gateway

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#317]
https://github.com/leo-project/leo_gateway/blob/develop/src/leo_gateway_app.erl#L412

```leo_manager_api:get_members_of_all_versions``` return ```{error, timeout}```  for a while.
After several timeouts happened, 
```leo_manager_api:get_members_of_all_versions``` did work.

Due to this problem, 
Getting leo_gateway's status running take too much time more than previous versions.

**Comment by mocchira** [comment]
https://github.com/leo-project/leo_redundant_manager/blob/develop/src/leo_redundant_manager_worker.erl#L286
in the above function
```erlang
timer:apply_after(100, leo_redundant_manager_api, create, [])
``` 
 are called many times, 
this makes `leo_redundant_manager` very high load and cause {error, timeout}.

We need to reduce this call as little as possible.

**Comment by yosukehara** [comment]
We'll consider leo_redundant_manager supports mnesia's transaction for updating cluster's members.

**Comment by mocchira** [comment]
Confirmed.
