### ISSUE TITLE
[test] Add a test case for listing Objects with pagination

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#321]
[X] aws-sdk-java https://github.com/leo-project/leofs_client_tests/commit/f8a80776451263e0daf306283c3a8fb60de750dc
[X] aws-sdk-php
[X] aws-sdk-ruby
[X] boto
[X] erlcloud

**Comment by windkit** [comment]
Tests has been added for aws-sdk-* and boto,

For Erlcloud, it would be enable through PR https://github.com/leo-project/leofs_client_tests/pull/11

**Comment by mocchira** [comment]
@windkit Thanks. Merged and updated.

**Comment by mocchira** [comment]
Since s3cmd has not exposed I/F to use pagination, 
I got rid of it from the targets.
