### ISSUE TITLE
[leo_cache]Set wrong value to disk cache capacity

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#322]
Originally filed at https://github.com/leo-project/leo_gateway/issues/14.

https://github.com/leo-project/leo_cache/blob/develop/src/leo_cache_server_dcerl.erl#L56
set wrong value to disk cache capacity.

s/PROP_RAM_CACHE_SIZE/PROP_DISK_CACHE_SIZE/

**Comment by yosukehara** [comment]
* LeoFS Gateway's disk cache configuration: http://leo-project.net/leofs/docs/configuration/configuration_3.html?v=1.2.7
