### ISSUE TITLE
Question about Comment-out in each conf files.

### ISSUE THREAD

**Issue by kentarosasaki** [leo-project/leofs#324]
I found 3 type form for default value line which are "# ", "## ", "##".

```
# sasl.error_logger_mf_dir = ./log/sasl               <= found only in leo_manager_1.conf, other conf uses "## " style.
## sasl.error_logger_mf_maxbytes = 10485760
##snmp_conf = ./snmp/snmpa_storage_0/leo_storage_snmp <= non-space stle, But, only leo_manager_1.conf doesn't use "##" style.
```

Almost all value lines use "## " style.
But this style is same as comment-out line.
It's hard to understand which is comment-out line and which is default value line.

If you have some recommendation, I want to make default value line even style.

As references, OpenStack conf file uses following style.
Comment-out: <- use 1 space between "#" and comment

```
# some comment
```

Default value: <- non-space style

```
#XXX = YYY
```

**Comment by yosukehara** [comment]
We unify format of configuration with "## " but which is no reason.
You can write comment-out line start with "#" on your LeoFS's configuration.

**Comment by yosukehara** [comment]
We are prior to easily reading the configuration we've adopted that format. A last line of a block is a configuration's line. It's a very simple. So we does not want to change this style.

And also, the configuration files are the template files. You can update them easily.

```
## SASL error log path
## sasl.sasl_error_log = ./log/sasl/sasl-error.log

## Restricts the error logging performed by the specified sasl_error_logger
## to error reports, progress reports, or both.
## errlog_type = [error | progress | all]
## sasl.errlog_type = error

## Specifies in which directory the files are stored.
## If this parameter is undefined or false, the error_logger_mf_h is not installed.
## sasl.error_logger_mf_dir = ./log/sasl

## Specifies how large each individual file can be.
## If this parameter is undefined, the error_logger_mf_h is not installed.
## sasl.error_logger_mf_maxbytes = 10485760

## Specifies how many files are used.
## If this parameter is undefined, the error_logger_mf_h is not installed.
## sasl.error_logger_mf_maxfiles = 5
```
