### ISSUE TITLE
[NFS] Returning file attributes on every operation

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#327]
## Problem

Copying lots of small files take time more than necessary with LeoFS v1.2.7 .
## Why

Current version’s NFS packets flow for copying one file is like this.

```
Client - << create file packet >> -> leo_gateway
Client - << getattr packet >> -> leo_gateway
Client - << setattr packet >> -> leo_gateway
Client - << getattr packet >> -> leo_gateway
Client - << write packet >> -> leo_gateway   * a write packet can be issued multiple times if the file size is larger than 1MB.
Client - << commit packet >> -> leo_gateway
Client - << getattr packet >> -> leo_gateway
```

7 round trips will happen per one file.
## Solution

But the number of round trips could be decreased to 4 if we implement _returning file attributes on every operation_.

The above packets flow will be optimized to

```
Client - << create file packet >> -> leo_gateway
Client - << setattr packet >> -> leo_gateway
Client - << write packet >> -> leo_gateway
Client - << commit packet >> -> leo_gateway
```

Since reply packets of every operations include the latest file attributes,
There is no need to issue getattr calls anymore.

**Comment by mocchira** [comment]
this will be solved with #227

**Comment by mocchira** [comment]
It turned out that solving this issue have a little effect,
On the contrary, it might have a bad effect in some cases.
So we will postpone this issue.

**Comment by windkit** [comment]
### Description
Here is a tcpdump to compare the differences between LeoFS and Ubuntu (nfs-kernel-server) NFS Servers, both are backed by ramdisk (`/dev/shm/`)

#### Test Case:
```bash
$ sudo mount -t nfs -o vers=3,nolock 192.168.100.35:/test /mnt/leofs
$ cp /mnt/leofs/dir1/obj1 dl
$ sudo umount /mnt/leofs
```

#### TCPDump
[leofs-write.zip](https://github.com/leo-project/leofs/files/154158/leofs-write.zip)
[linux-write.zip](https://github.com/leo-project/leofs/files/154159/linux-write.zip)

**Comment by mocchira** [comment]
A possible fix without any performance degradation(avoid additional communications between leo_gateway and leo_storages) is to return at least
- dsize
- timestamp

When calling `leo_nfs_file_handler:write`(for write_3) and `leo_gateway_rpc_handler:put`(for create_3).

@yosukehara I think we can get this into v1.3.3 with this solution since it looks tiny and harmless to me.

**Comment by yosukehara** [comment]
@mocchira I agree with your opinion. Let's start fix this issue on v1.3.3's development.

**Comment by mocchira** [comment]
WIP

**Comment by mocchira** [comment]
2 Round Trips(RTs) have been reduced as the following.
There is still room to reduce RTs by respondig to setattr3 with post_attr but it require leo_gataway to access leo_storage for getting the latest meta so seems not to give us the additional performance boost.
let me close for now.
maybe reopen if we come up with the another solution without any drawback.

### TCPDump

[leofs-write-new.zip](https://github.com/leo-project/leofs/files/815663/leofs-write-new.zip)

**Comment by yosukehara** [comment]
FIXED
