### ISSUE TITLE
[leo_storage] Make read_repair configurable

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#330]
There are some use cases that the performance is high priority more than consistency.
If this will be implemented, LeoFS read performance will be increased up to around 20%.

https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_handler_object.erl#L923

**Comment by yosukehara** [comment]
We're planning to implement it to both [a system configuration](http://leo-project.net/leofs/docs/configuration/configuration_1.html) and each user's bucket option as *enable_read_and_repair*.

**Comment by yosukehara** [comment]
The read repair feature need to fix inconsistent object. So we cannot remove this feature. I've closed this issue. If we need it, we will open it.
