### ISSUE TITLE
[leo_object_storage] Massive amount of backend tasks could degrade the performance of processing requests from leo_gateway

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#334]
## Problem
Since a leo_object_storage process have processed Erlang messages as their tasks in the mailbox in order,
If there are already lots of backend tasks(generated by leo_mq mechanism) in the mailbox,
Online tasks generated by leo_gateway could block until those backend tasks will be processed completely.

## How to solve in short term
Configure the number of batch process as minimum as possible.
Details are described [here](http://leo-project.net/leofs/docs/configuration/configuration_2.html#configuration-related-to-mq).

## How to solve in long term
We consider whether implementing priority queue for leo_object_storage( still not decided ).

- http://stackoverflow.com/questions/12248111/how-to-give-different-priorities-to-erlang-messages

**Comment by yosukehara** [comment]
According to improvement of object_storage performance, LeoFS' performance also increased, So I've closed this.
- leo-project/leofs/issues/450
- leo-project/leofs/issues/467
