### ISSUE TITLE
[leofs_docs] lots of dead links

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#341]
# Pages which have dead links
- http://leo-project.net/leofs/docs/introduction/intro.html
- http://leo-project.net/leofs/docs/configuration/configuration_5.html
- http://leo-project.net/leofs/docs/configuration/configuration_6.html
- http://leo-project.net/leofs/docs/admin_guide/admin_guide_9.html
- http://leo-project.net/leofs/docs/architecture/architecture.html
- http://leo-project.net/leofs/docs/architecture/leofs-manager-detail.html
- http://leo-project.net/leofs/docs/faq/faq_1.html
- http://leo-project.net/leofs/docs/faq/faq_2.html

**Comment by yosukehara** [comment]
I've checked them and published them on the website.
