### ISSUE TITLE
[leo_storage][mdc] Replication messages coudn't be consumed at all

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#343]
Since there is a possibility that the target object record to be replicated over the clusters doesn't be initialized `method` field, int this case, 
case_clause could occur on a remote cluster and retried forever.

https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_handler_object.erl#L1013

Must do initialize the method field(put|delete) explicitly at caller.

**Comment by yosukehara** [comment]
I've included this issue in https://github.com/leo-project/leo_storage/commit/c64214eccb7b94ef31c43a4359b46c4ff98a6635?diff=split.

**Comment by mocchira** [comment]
We still have this issue.
