### ISSUE TITLE
Delete Multiple Objects method of S3 API support

### ISSUE THREAD

**Issue by assam212** [leo-project/leofs#347]
Does Leofs support delete multiple objects method of S3 API ?

If we want to delete a lot of objects, this method is useful and will be able to avoid high load.

We want to upgrade  OwnCloud V8, it uses this method.
https://github.com/owncloud/core/blob/master/apps/files_external/lib/amazons3.php#L235

Please consider it.

**Comment by yosukehara** [comment]
Thank you for your request. Actually, we does not support that, yet.
We will consider your request positively. Please wait for our decision.

**Comment by yosukehara** [comment]
@mocchira  There are two references on AWS's website.
* [Delete Multiple Objects](http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html)
* [Deleting Multiple Objects Per Request](http://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingMultipleObjects.html)

**Comment by mocchira** [comment]
@yosukehara got it.
I think it's relatively easy to implement.

**Comment by mocchira** [comment]
@yosukehara 
* Estimate
 * IMPL(0.5d)
 * UT(0.5d)
 * IT with aws-sdk (1d)

**Comment by yosukehara** [comment]
@assam212 We've decide we support **the delete Multiple Objects method** with [LeoFS v1.2.8](https://github.com/leo-project/leofs/milestones/1.2.8).

**Comment by assam212** [comment]
@yosukehara 
Thank you for your decision.

**Comment by yosukehara** [comment]
@mocchira I've checked your implementation and test code. it's LGTM.
Thank you for your contribution.

**Comment by yosukehara** [comment]
@assam212 We've implemented test cases for checking this API with Java, Ruby and PHP as below.
We will include this in [LeoFS v1.2.8](https://github.com/leo-project/leofs/milestones/1.2.8). So I've closed this issue. Thank you for your request.

* for Java: https://github.com/leo-project/leofs_client_tests/commit/fa44b6b0030c266c75f410333d9f09a5e88625e4
* for Ruby: https://github.com/leo-project/leofs_client_tests/commit/98c9c3e59bfec2eba233d41264782d80d821a646
* for PHP: https://github.com/leo-project/leofs_client_tests/commit/8b6c159f41b9397f368fd2f05de566569220e0ab
