### ISSUE TITLE
[leo_object_storage] Logging slow I/O operations

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#356]
The purpose is same with MySQL's [slow query log](https://dev.mysql.com/doc/refman/5.1/en/slow-query-log.html).
Since there are some cases Disk I/O operations could take very long time for some reason in production,
In order to make it easy to identify the root cause, 
we need to collect this kind of information.

**Comment by yosukehara** [comment]
In addition, we're planning to implement handling response time of object_storage - put and get operation at leo_watchdog to be one of judge elements for decreasing or increasing background performance.

**Comment by yosukehara** [comment]
I've implemented this ticket as follows:

* https://github.com/leo-project/leo_object_storage/commit/3b0b3c3977f695110300d0eb0be2ce4295d32d57
* https://github.com/leo-project/leo_storage/commit/e9be922625b1734de0fa352c02d9bbd25da3496f?diff=unified
