### ISSUE TITLE
[leo_storage][auto-compaction] Each storage node's data-compaction happened at almost same time

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#365]
I've recognized an issue by a benchmark of LeoFS. The data-compaction of Leo's storage does not affect the front processing.
* Test Result: https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/recover_with_front/20150519_recover_node_1.2.9

**Comment by yosukehara** [comment]
I've fixed this issue that each storage's data-compaction is executed step by step.
A number of nodes to be executed at the same time is one in case of a small storage-cluster. On the other hand, in case of a large storage-cluster, LeoStorage depends on the rule of execution of the auto-compaction as below:

```
<a number of data-compaction nodes at the same time> = 
        round(<total number of active nodes> / <a number of replicas>) - 1
ex)
* Total number of active nodes = 15
* A number of replicas = 3
* A number of data-compaction nodes at the same time = 4

(note: minimum value: 1)
```

![screen shot 2015-06-25 at 18 37 34](https://cloud.githubusercontent.com/assets/148770/8351582/7254132e-1b69-11e5-9cef-ecb32ac18e1e.png)

![screen shot 2015-06-25 at 18 37 44](https://cloud.githubusercontent.com/assets/148770/8351587/7cbac6c8-1b69-11e5-9e40-e90ba4163165.png)

I've been considering calculation of ``a number of data-compaction nodes at the same time``.

**Comment by yosukehara** [comment]
I've reached the most suitable rule is as below:
```
<a number of data-compaction nodes at the same time> = 
        round(<total number of active nodes> x <coefficient>)

* coefficient:
    * High: 0.1
    * Middle: 0.075
    * Low: 0.05
```

I've considered that an auto-compaction processing needs to not affect front-end operations as much as possible.

![chart-num-of-execution-nodes](https://cloud.githubusercontent.com/assets/148770/8355933/2cc802e2-1b8d-11e5-80d5-0dc45ab1ed4b.png)
* coefficient = 0.075

**Comment by yosukehara** [comment]
According to [a benchmark report](https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/recover_with_front/20150626_recover_node_1.2.11-dev10#compaction-report-summary), I/we have recognized we need to more improve the auto-compaction mechanism. I've been considering I implement a negotiation(consensus) mechanism w/candidate nodes of execution of a data-compaction.

**Comment by yosukehara** [comment]
We've finally taken a good result - https://github.com/leo-project/notes/blob/master/leofs/benchmark/leofs/recover_with_front/20150629_recover_node_1.2.11-dev11/README.md

![benchmark-summary](https://cloud.githubusercontent.com/assets/148770/8403587/06dcb00e-1e81-11e5-8fd1-ee6ae29cb101.png)

**Comment by mocchira** [comment]
@yosukehara 
This result seems that compaction only happened at leofs17 and leofs18 ( not happend at leofs1[4-6] ).
Is it OK?

**Comment by yosukehara** [comment]
@mocchira I've recognized that. But leo_storage was little bit old develop version. The latest version is works fine.

**Comment by yosukehara** [comment]
Today, we've taken [a benchmark - recover-node + front-operations w/watchdog and auto-compaction](https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/recover_with_front/20150630_recover_node_1.2.11-dev12), which is good result for us.

![summary 20150630 benchmark](https://cloud.githubusercontent.com/assets/148770/8425309/671767e8-1f3f-11e5-8c58-737f3a59177f.png)
