### ISSUE TITLE
Support aws-sdk-go

### ISSUE THREAD

**Issue by kentarosasaki** [leo-project/leofs#373]
Current aws-sdk-go only support v4 credentials. We could not use LeoFS via Golang application.
https://github.com/aws/aws-sdk-go/blob/ea83c25c44525da47e8044bbd21e4045758ea39b/service/s3/service.go#L32

Now we are using terraform.tfstate.
http://qiita.com/dtan4/items/04632f1c2f35388a3283

In order to use with leofs, we would fork Terraform. (e.g. change endpoint from s3.awsamazoncom to leofs endpoint.)
But terraform uses aws-sdk-go internally, and we should access via v4 authentication.
We can use leofs if we change alc to public-read-write. But it's not good for security.

If possible, please consider to support aws-sdk-go.

**Comment by yosukehara** [comment]
Actually, we recognized this improvement and we posted a ticket - #283 .
But you can use other Go-lang clients, which are [s3gof3r](http://godoc.org/github.com/rlmcpherson/s3gof3r) and [goamz](https://github.com/crowdmob/goamz)

**Comment by yosukehara** [comment]
In addition, you can see an example of Go-lang client on our website:
* http://leo-project.net/leofs/docs/s3api_client/s3_client_golang.html

**Comment by kentarosasaki** [comment]
I know the other sdk could use.
But Terraform uses aws-sdk-go...

**Comment by mocchira** [comment]
@kentarosasaki As you may know, we released 1.4.0-pre1 which includes AWS Signature V4 Support and aws-sdk-go works well ( https://github.com/leo-project/leofs_client_tests/blob/develop/aws-sdk-go/LeoFSTest.go ) so I' ll close this ticket.

Please file a new issue if you faced with some troubles when using terraform with LeoFS 1.4.0-pre1.
