### ISSUE TITLE
[NFS] Reduce unnecessary round trips between nfs client and leo_gateway

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#375]
To make NFS clients cache work properly,
We need to manage ctime of directories properly.

- `ctime` is the time when the attributes of the file were last changed

When handling a directory, 
- the attributes of a direcotry are its metadatas (ex. timestamp, name, ...).
- when a directory's entries were changed, its timestamp should be chnaged.

For example,

- If `bucket/path/to/file2` was added then the ctime of `bucket/path/to` should be updated.

**Comment by mocchira** [comment]
A part of this task already done which will be included in 1.4.0-pre1.
In case copying lots of direcotries recursively , 
the throughput will be around 50 - 100 times higher than 1.2.12.

**Comment by yosukehara** [comment]
DONE
