### ISSUE TITLE
[leo_object_storage] file:pread/3 could return {ok, Data} which size less than the Number argument

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#378]
http://www.erlang.org/doc/man/file.html#pread-3 could return `{ok, Data}` which size less than the `Number` argument.

We need to handle this kind of return values.

**Comment by yosukehara** [comment]
I've implemented a wrapper function of ``file:pread/3`` as follows:
* https://github.com/leo-project/leo_commons/blob/develop/src/leo_file.erl#L216-L273
* Eralng docs - [file:pread/3](http://www.erlang.org/doc/man/file.html#pread-3)

**Comment by mocchira** [comment]
@yosukehara LGTM.

**Comment by mocchira** [comment]
Anyway, 
It seems that functions using `efile_read`|`efile_pread` in the file module like 

 - file:read
 - file:read_file
 - file:pread

could return a object which size less than we expcted.

https://github.com/erlang/otp/blob/OTP-17.5.6/erts/emulator/drivers/common/efile_drv.c#L1144
https://github.com/erlang/otp/blob/OTP-17.5.6/erts/emulator/drivers/common/efile_drv.c#L1322
https://github.com/erlang/otp/blob/OTP-17.5.6/erts/emulator/drivers/common/efile_drv.c#L1370

https://github.com/erlang/otp/blob/OTP-17.5.6/erts/emulator/drivers/unix/unix_efile.c#L667
https://github.com/erlang/otp/blob/OTP-17.5.6/erts/emulator/drivers/unix/unix_efile.c#L700
