### ISSUE TITLE
[leo_storage][leo_mq] Decreased a performance of read and write operation during rebalance/recover-node

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#379]
We took some benchmarks for LeoFS v1.2.10 and then we found performance degradation as follows:
* [benchmark report (4th June, 2015)](https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/recover_with_front/20150604_recover_node_1.2.10_default2)

![benchmark-report](https://cloud.githubusercontent.com/assets/148770/8079846/59054c8a-0fa2-11e5-9a40-3af53aaaf9c7.png)

**Comment by windkit** [comment]
I think it would be better if we could sort out two sets of parameters. (Under reference system configurations)
One for aggressive recovery, that is utilizing all resources (or most, e.g. 80%)
One for conservative recovery, that is utilizing minimal resources (e.g. <20%)

Administrators could then choose which one they want, either full-speed recovery during maintenance or auto-triggered recovery without affecting foreground tasks much.

On top of it, dynamic configuration would be great to have.

**Comment by yosukehara** [comment]
@windkit Thank you for your comment. From last night, I've been checking MQ's consumption mechanism because it seems MQ is not able to handle mq-consumption's interval parameter correctly.

**Comment by mocchira** [comment]
@windkit +1.
From administrator's point of view, 
The current configurations related to MQ|Watchdog might be difficult to set appropriate values corresponding to their own environment.
So wrapping those difficult configurations by what you suggest would make sense and 
needless to say, dynamic configuration great.

After @yosukehara finish to fix this issue, 
We will discuss how configurations should be exposed for admins.

**Comment by yosukehara** [comment]
Regarding  the dynamic configuration, we only implement the watchdog mechanism, as you mentioned, we need to provide the mq and other mechanism similar to the watchdog.

**Comment by yosukehara** [comment]
We've taken [a benchmark of recover-node w/front operations](https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/recover_with_front/20150612_recover_node_1.2.11-dev) as below:
![benchmark-result-recover-node](https://cloud.githubusercontent.com/assets/148770/8124292/40fd1b2c-1114-11e5-904b-a15bf0d791e7.png)
