### ISSUE TITLE
[leo_gateway] Does not respond to "List Multipart Uploads" Operation

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#381]
#### Issue
`leo_gateway` does not respond to `List Multipart Uploads` which reports on-going multipart upload in the server
http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListMPUpload.html

#### Outcome
`boto` (S3 Client in Python) cannot complete multipart upload as it would check if the corresponding multipart upload exists in the server

##### Comment
Among the clients tested, it is the only one doing such check in multipart upload ...

##### Test & Traceback
Test with `leo-project/leofs_client_tests/boto/leo.py`
```
Traceback (most recent call last):
  File "leo.py", line 82, in <module>
    multi_part.complete_upload()
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 317, in complete_upload
    xml = self.to_xml()
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 156, in to_xml
    for part in self:
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/multipart.py", line 122, in part_lister
    for part in parts:
TypeError: 'NoneType' object is not iterable
```

**Comment by yosukehara** [comment]
Thank you for your report. We'll implement this API w/the next version - v1.4.0 and list this API on [LeoFS's documentation](http://leo-project.net/leofs/docs/s3api_interface/s3_api_1.html).

**Comment by windkit** [comment]
Turn out this is a duplicate to #145

**Comment by windkit** [comment]
To clarify, `boto` uses `List Parts` to find out parts being uploaded to server
http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListParts.html

Further Discussion would be conducted at #145
