### ISSUE TITLE
[leo_storage] Incorrect handling of range get the first byte

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#382]
#### Issue
When requesting the first byte from leo_storage, the whole object would be returned instead of one byte

#### Test
Range get Byte Range (1048576-10485760) [zero-based, inclusive] from a large object with 5MB Chunk Size

##### Expected Output
Read 4194304 bytes from 1st chunk
Read 5242880 bytes from 2nd chunk
Read 1 byte from 3rd chunk

##### Observed Output
Read 4194304 bytes from 1st chunk
Read 5242880 bytes from 2nd chunk
Read 5242880 bytes from 3rd chunk

#### Possbile Cause
EndPos = 0 is used to represent a read object till end request, while it crashed with the case of requesting the first byte
```
leo_object_storage_haystack:calc_pos/3

calc_pos(StartPos, 0, DSize) ->
    {StartPos, DSize - 1};
```
https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_haystack.erl#L478
... Use Cases (To represent a whole object request) ...
https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_handler_object.erl#L164
https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_haystack.erl#L183
https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_haystack.erl#L247
https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_haystack.erl#L436

**Comment by windkit** [comment]
Update with a more accurate description of the issue

**Comment by yosukehara** [comment]
I've briefly checked this issue as below:

* Requested range: 1048576 - 10485760
* expected length: 9437184
* received length: 14680064
* diff length: 5242880

```bash
$ s3cmd put VirtualBox-4.3.28-100309-OSX.dmg s3://test/
VirtualBox-4.3.28-100309-OSX.dmg -> s3://test/VirtualBox-4.3.28-100309-OSX.dmg  [1 of 1]
 114102333 of 114102333   100% in    1s    58.14 MB/s  done
 
$ leofs-adm whereis test/VirtualBox-4.3.28-100309-OSX.dmg
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
 del?  |           node           |             ring address             |    size    |   checksum   |  # of chunks   |     clock      |             when
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
       | storage_1@127.0.0.1      | 9b0ea7bb197bc8bbc296698bb070fc4c     |    111428K |   5bd31266c4 |             22 | 518854b456111  | 2015-06-15 11:34:16 +0900
       | storage_2@127.0.0.1      | 9b0ea7bb197bc8bbc296698bb070fc4c     |    111428K |   5bd31266c4 |             22 | 518854b456111  | 2015-06-15 11:34:16 +0900
       
$ leofs-adm update-acl test 05236 public-read-write
OK

$ curl --range 1048576-10485760 http://localhost:8080/test/VirtualBox-4.3.28-100309-OSX.dmg   -o test_0.dump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.0M    0 14.0M    0     0   257M      0 --:--:-- --:--:-- --:--:--  259M

$ ls -l test_0.dump
-rw-r--r--  1 yosuke.hara admin  14680064 Jun 15 11:37 test_0.dump
```

Today, I'll fix this issue.
Thank you for your report.

**Comment by yosukehara** [comment]
I've recognized leo_gateway does not request range from 2nd request, which is the root cause.

```erlang
src/leo_object_storage_api.erl:144:<0.1393.0>: { AddrIdAndKey , StartPos , EndPos } = {{234201759449252846679772354721654614873,
                                         <<"test/VirtualBox-4.3.28-100309-OSX.dmg\n1">>},
                                        1048576,5242879}
src/leo_object_storage_api.erl:144:<0.1402.0>: { AddrIdAndKey , StartPos , EndPos } = {{64652752981655716211561146880053049672,
                                         <<"test/VirtualBox-4.3.28-100309-OSX.dmg\n2">>},
                                        0,0}
src/leo_object_storage_api.erl:144:<0.1406.0>: { AddrIdAndKey , StartPos , EndPos } = {{22804992153133645551863101930441073959,
                                         <<"test/VirtualBox-4.3.28-100309-OSX.dmg\n3">>},
                                        0,0}
```

**Comment by windkit** [comment]
The requests are actually "correct"
To request "test/VirtualBox-4.3.28-100309-OSX.dmg" from byte 1048576 to byte 10485760, it would read from three chunks

"test/VirtualBox-4.3.28-100309-OSX.dmg\n1" for byte 1048576 to byte 5242879
"test/VirtualBox-4.3.28-100309-OSX.dmg\n2" for the whole object
"test/VirtualBox-4.3.28-100309-OSX.dmg\n3" for byte 0 to byte 0 (first byte)

Here the problem is how to handle the whole object request.
In LeoFS (particularly `leo_storage_handler_object.erl:get_fun/2`), whole object request would be translated to request object for range [0, 0]. However this is actually the case for reading the first byte of object.

As a result, the three requests actually served are 
"test/VirtualBox-4.3.28-100309-OSX.dmg\n1" for byte 1048576 to byte 5242879
"test/VirtualBox-4.3.28-100309-OSX.dmg\n2" for whole object
"test/VirtualBox-4.3.28-100309-OSX.dmg\n3" for whole object

So the returned date length become 14680064 but not 9437185

**Comment by yosukehara** [comment]
My comment is wrong, in correct is as below:
I've recognized leo_gateway does not request correctly range from 2nd request, which is the root cause.

src/leo_object_storage_api.erl:144:<0.1393.0>: { AddrIdAndKey , StartPos , EndPos } = {{234201759449252846679772354721654614873,
                                         <<"test/VirtualBox-4.3.28-100309-OSX.dmg\n1">>},
                                        1048576,5242879}
src/leo_object_storage_api.erl:144:<0.1402.0>: { AddrIdAndKey , StartPos , EndPos } = {{64652752981655716211561146880053049672,
                                         <<"test/VirtualBox-4.3.28-100309-OSX.dmg\n2">>},
                                        0,0}
src/leo_object_storage_api.erl:144:<0.1406.0>: { AddrIdAndKey , StartPos , EndPos } = {{22804992153133645551863101930441073959,
                                         <<"test/VirtualBox-4.3.28-100309-OSX.dmg\n3">>},
                                        0,0}

**Comment by yosukehara** [comment]
I've misunderstood that I need to modify leo_object_storage_api:get/1 and related functions.
I'll continuously check this issue.

* Current
```erlang
-spec(get(AddrIdAndKey) ->
             {ok, list()} | not_found | {error, any()} when AddrIdAndKey::addrid_and_key()).
get(AddrIdAndKey) ->
    get(AddrIdAndKey, 0, 0).
```

* New
```erlang
-spec(get(AddrIdAndKey) ->
             {ok, list()} | not_found | {error, any()} when AddrIdAndKey::addrid_and_key()).
get(AddrIdAndKey) ->
    get(AddrIdAndKey, -1, -1).
```

**Comment by yosukehara** [comment]
I've fixed this issue and test log is as below:

```bash
$ s3cmd put VirtualBox-4.3.28-100309-OSX.dmg s3://test/
VirtualBox-4.3.28-100309-OSX.dmg -> s3://test/VirtualBox-4.3.28-100309-OSX.dmg  [1 of 1]
 114102333 of 114102333   100% in    1s    68.17 MB/s  done

$ leofs-adm whereis test/VirtualBox-4.3.28-100309-OSX.dmg
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
 del?  |           node           |             ring address             |    size    |   checksum   |  # of chunks   |     clock      |             when
-------+--------------------------+--------------------------------------+------------+--------------+----------------+----------------+----------------------------
       | storage_0@127.0.0.1      | 9b0ea7bb197bc8bbc296698bb070fc4c     |    111428K |   5bd31266c4 |             22 | 51889a467327e  | 2015-06-15 16:45:31 +0900

$ curl --range 1048576-10485760 http://localhost:8080/test/VirtualBox-4.3.28-100309-OSX.dmg   -o test_0.dump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9216k    0 9216k    0     0   173M      0 --:--:-- --:--:-- --:--:--  176M

$ ls -l test_0.dump
-rw-r--r--  1 yosuke.hara  admin  9437185 Jun 15 16:46 test_0.dump


$ curl --range 0-0 http://localhost:8080/test/VirtualBox-4.3.28-100309-OSX.dmg   -o test_0.dump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     1    0     1    0     0    120      0 --:--:-- --:--:-- --:--:--   125

$ ls -l test_0.dump
-rw-r--r--  1 yosuke.hara  admin  1 Jun 15 17:12 test_0.dump
```
