### ISSUE TITLE
[leo_ordning_reda] close should be executed when unexpected terminating

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#387]
should be executed here.
https://github.com/leo-project/leo_ordning_reda/blob/develop/src/leo_ordning_reda_server.erl#L280

**Comment by yosukehara** [comment]
Thank you for your report. I'll fix that soon.

**Comment by mocchira** [comment]
To be more precious,

The below lines should be executed.
https://github.com/leo-project/leo_ordning_reda/blob/develop/src/leo_ordning_reda_server.erl#L226-L232
