### ISSUE TITLE
[All] Add support for OTP 18

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#389]
Since some Non NameSpace Types like dict(), set() will be remove in OTP18,
But NameSpace Types like dict:dict() can NOT be compiled with under R16*,
So we need to do conditional compile.

This hack can be used to do that.
https://github.com/basho/riak_core/commit/00568d67b578b3f4a50a06a3fe8e1284e1c788be

**Comment by windkit** [comment]
With a simple go through the build processes, I have sorted out several modules need updates for OTP 18.

* leo_dcerl - set(), dict() [https://github.com/leo-project/leo_dcerl/pull/3]
* leo_cache - leo_dcerl and leo_mcerl version
* leo_ordning_reda - dict() [https://github.com/leo-project/leo_ordning_reda/pull/9]
* leo_object_storage - set() [https://github.com/leo-project/leo_object_storage/pull/5]
* leo_backend_db - proper update [https://github.com/leo-project/leo_backend_db/pull/5]
* leo_storage - dict(), proper update [https://github.com/leo-project/leo_storage/pull/16]
* leo_manager - dict() [https://github.com/leo-project/leo_manager/pull/15]
* erpcgen - erlang:now() [https://github.com/leo-project/erpcgen/pull/1]

Here are those need code changes / library update, there are some others but they would simply require adding 18 to `require_otp_vsn` and update of modules used

**Comment by yosukehara** [comment]
Done:
* [leo_backend-db v1.2.1](https://github.com/leo-project/leo_backend_db/releases/tag/1.2.1)
* [leo_cache v0.6.12 and 1.4-branch](https://github.com/leo-project/leo_cache/releases/tag/0.6.12)
* [leo_commons v1.1.6](https://github.com/leo-project/leo_commons/releases/tag/1.1.6)
* [leo_dcerl v0.4.2](https://github.com/leo-project/leo_dcerl/releases/tag/0.4.2)
* [leo_logger v1.2.2](https://github.com/leo-project/leo_logger/releases/tag/1.2.2)
* [leo_mcerl v0.6.2](https://github.com/leo-project/leo_mcerl/releases/tag/0.6.2)
* [leo_mq v1.4.2](https://github.com/leo-project/leo_mq/releases/tag/1.4.2)
* [leo_object_storage v1.2.21 and 1.4-branch](https://github.com/leo-project/leo_object_storage/releases/tag/1.2.21)
* [leo_ordning_reda v1.1.5](https://github.com/leo-project/leo_ordning_reda/releases/tag/1.1.5)
* [leo_redundant_manager 1.9.24](https://github.com/leo-project/leo_redundant_manager/releases/tag/1.9.24)
* [leo_rpc v0.10.7](https://github.com/leo-project/leo_rpc/releases/tag/0.10.7)
* [leo_pod v0.6.4](https://github.com/leo-project/leo_pod/releases/tag/0.6.4)
* [leo_s3_libs v1.1.12](https://github.com/leo-project/leo_s3_libs/releases/tag/1.1.12)
* [leo_statistics v1.1.11](https://github.com/leo-project/leo_statistics/releases/tag/1.1.11)
* [leo_tran v0.2.5](https://github.com/leo-project/leo_tran/releases/tag/0.2.5)
* [leo_watchdog v0.12.2](https://github.com/leo-project/leo_watchdog/releases/tag/0.12.2)
* [savanna_agent v0.4.13](https://github.com/leo-project/savanna_agent/releases/tag/0.4.13)
* [savanna_commons v0.10.0](https://github.com/leo-project/savanna_commons/releases/tag/0.10.0)
* [erpcgen v0.2.4](https://github.com/leo-project/erpcgen/releases/tag/0.2.4)
* [nfs_rpc_server v0.2.4](https://github.com/leo-project/nfs_rpc_server/releases/tag/0.2.4)
* [leo_storage develop and 1.4](https://github.com/leo-project/leo_storage)
* [leo_gateway develop and 1.4](https://github.com/leo-project/leo_gateway)
* [leo_manager develop and 1.4](https://github.com/leo-project/leo_manager)
