### ISSUE TITLE
[all] Use erlang:(max|min) if possible

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#400]
https://github.com/leo-project/leo_object_storage/blob/1.2.9/src/leo_compact_fsm_worker.erl#L1138
https://github.com/leo-project/leo_object_storage/blob/1.2.9/src/leo_compact_fsm_worker.erl#L1154
https://github.com/leo-project/leo_object_storage/blob/1.2.9/src/leo_compact_fsm_worker.erl#L1171
https://github.com/leo-project/leo_object_storage/blob/1.2.9/src/leo_compact_fsm_worker.erl#L1186

Those functions can be replaced with one liner as below.
```erlang
% for incr_interval_fun
erlang:min(Interval + StepInterval, MaxInterval)
% for decr_interval_fun
erlang:max(Interval - StepInterval, DEF_MIN_COMPACTION_WT)
```

**Comment by yosukehara** [comment]
@mocchira Thank you for your suggestion. I'll modify them soon.

**Comment by yosukehara** [comment]
I've refactored ``leo_object_storage`` and ``leo_mq`` for this ticket.
