### ISSUE TITLE
[leo_storage]500 error can occur under heavy load with N=1

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#401]
When R:W = 8:2 benchmarking on all-in-one env with N=1,
500 errors can occur due to failing the read repair process.

**Comment by yosukehara** [comment]
@mocchira Thanks for your report. I'll implement that ``leo_storage`` does not execute  ``read-repair`` in case of ``N=1``.

**Comment by yosukehara** [comment]
I've fixed this issue, which will be included in LeoFS v1.4.0-pre1.

**Comment by mocchira** [comment]
Confirm Degrade

**Comment by mocchira** [comment]
As get_fun return {ok, #metadata{}, #object{}} in normal case,
We need to convert it to {ok, #metadata, Binary}.
