### ISSUE TITLE
[leo_ordning_reda] add_container and remove_container can get into race condition

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#407]
Under heavy load, 
This insert to ets 
https://github.com/leo-project/leo_ordning_reda/blob/1.1.1/src/leo_ordning_reda_api.erl#L108 
can be deleted by this delete 
https://github.com/leo-project/leo_ordning_reda/blob/1.1.1/src/leo_ordning_reda_api.erl#L141.

If that happened,
We have a process but no corresponding record in ets so code written by the below manner can get into infinity loop.
https://github.com/leo-project/leo_storage/blob/1.4/src/leo_directory_sync.erl#L165-L180

We need to serialize oprations to containers.

**Comment by yosukehara** [comment]
@mocchira Thank you for your report. I/We need to implement the container manager to be able to an exclusive control for a processing of creating and removing a container.
