### ISSUE TITLE
[leo_storage] No need to link between leo_storage_replicator's parent and sub parent

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#413]
As there is a possibility that the parent process could exit when fulfilling the consistency while the sub parent keep waiting for child processes, `proc_lib:start_link` in https://github.com/leo-project/leo_storage/blob/1.2.12/src/leo_storage_replicator.erl#L90 shold be replaced with `proc_lib:start` ( no link version ) to prevent the sub parent from being terminated.

**Comment by yosukehara** [comment]
DONE
