### ISSUE TITLE
[leo_manager]leo_manager slave can't restart when detach was executed while the slave was down

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#418]
## How to reproduce
https://gist.github.com/mocchira/a51eaa31f03cb0b393ca

**Comment by mocchira** [comment]
Already fixed by @yosukehara .

**Comment by yosukehara** [comment]
I fixed this issue as below:
* https://github.com/leo-project/leo_redundant_manager/commit/627d034eac0bb1344aabae0951198e6443d9dc48
