### ISSUE TITLE
R18 clients causes gateway to crash the connections

### ISSUE THREAD

**Issue by Licenser** [leo-project/leofs#421]
This crash log is wrotten:

https://gist.github.com/Licenser/c5c86188aa00cdf2130d

an example program can be found here:

https://monosnap.com/file/0eHMsXule2YK37IvkZqTaQNuvnsvoJ

(compiled https://github.com/project-fifo/fifo_s3)

**Comment by yosukehara** [comment]
Thank you for your report.

I've briefly check the log then found the script output ``no function clause matching tls_v1:enum_to_oid(28) ``. I'll check the detail.

**Comment by mocchira** [comment]
This is similar to https://github.com/ruby-amqp/bunny/issues/303.
And 
From the crash log,
```erlang
no function clause matching tls_v1:enum_to_oid(28) line 404
```

also R16B03-1' source at https://github.com/erlang/otp/blob/OTP_R16B03-1/lib/ssl/src/tls_v1.erl#L404-L429

Indeed, enum_to_oid(28) clause is missing.

@Licenser 
To make sure, 
Could you check the Erlang version you used? 
If R16*, it's a VM bug.

**Comment by Licenser** [comment]
yes it was compiled with R16, guess that means upgrading is needed :(

**Comment by Licenser** [comment]
thanks!
