### ISSUE TITLE
[v1.2.11-][leo_watchdog] Not clear combination of for errors - "cpu_util" and "load_avg_1m"

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#423]
I found leo_watchdog did not clear combination of for errors - "cpu_util" and "load_avg_1m" after becoming low load of a storage-node, and also, this issue happened since [LeoFS v1.2.11](https://github.com/leo-project/leofs/releases/tag/1.2.11).

**Comment by yosukehara** [comment]
DONE: https://github.com/leo-project/leo_watchdog/commit/5dbddbed58d17f36304fcc8b5de0579697305867

**Comment by PatelParas** [comment]
Shouldn't we consider to categorize Alert, error and info in separate files ?

Some time leo_watchdog alert and error messages make confusion for SYS engineer.

**Comment by yosukehara** [comment]
@PatelParas Thanks for your comment. We'll consider that soon.
