### ISSUE TITLE
[S3-API][leo_gateway] Compatibility with Stream Wrapper in aws-sdk-php

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#429]
### Description
In `aws-sdk-php`, Stream Wrapper is provided to wrap S3 object as file stream
http://docs.aws.amazon.com/aws-sdk-php/v2/guide/feature-s3-stream-wrapper.html

There are some issues when using the stream together with `http_send_stream` and `http_throttle` in `pecl_http`

#### Test Code
```php
$s3client->registerStreamWrapper();
$stream = fopen('s3://testp/test.large' ,'r');
http_send_stream($stream);
```
#### Observation
`http_send_stream` assumes the underlying is seekable, by default `aws-sdk-php` does not open a seekable stream with above code

#### Solution
Open a stream with `seeakble` stream context
```php
$context = stream_context_create(array(
        's3' => array('seekable' => true)
                ));
$s3client->registerStreamWrapper();
$stream = fopen('s3://testp/test.large' ,'r', false, $context);
http_send_stream($stream);
```
(Please note that, it will keep previously read bytes in memory with the `seekable` context)

#### Test Code
```php
$stream = fopen('s3://testp/test.large' ,'r', false, $context);
http_throttle(0.1);
http_send_stream($stream);
```

#### Observation
When objects are sent with low speed, timeout would occur in various location.

#### Error Log (1.2)
```
[E]	gateway_0@127.0.0.1	2015-10-27 13:37:16.371354 +0900	1445920636	leo_large_object_get_handler:handle_loop/3	184	key:testp/test.large	2, index:1, cause:timeout
```
#### Error Log (1.4)
```
[E]	gateway_0@127.0.0.1	2015-10-26 10:39:47.842387 +0900	1445823587	null:null	0	gen_server <0.1482.0> terminated with reason: {timeout,{gen_server,call,[leo_tran_serializable_cntnr,{run,<<"testp/test.large">>,null,null,leo_large_object_get_handler,{10,{http_req,#Port<0.2133>,ranch_tcp,close,<0.1478.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},35888},<<"testp.localhost">>,undefined,8080,<<"/test.large">>,undefined,<<>>,[],[],[{<<"host">>,<<"testp.localhost:8080">>},{<<"user-agent">>,<<"aws-sdk-php2/2.8.14 Guzzle/3.9.3 curl/7.35.0 PHP/5.5.9-1ubuntu4.13">>},{<<"date">>,<<"Mon, 26 Oct 2015 01:39:17 +0000">>},{<<"authorization">>,...},...],...},...},...},...]}} in gen_server:call/3 line 190
[E]	gateway_0@127.0.0.1	2015-10-26 10:39:47.843176 +0900	1445823587	null:null	0	["CRASH REPORT ",[80,114,111,99,101,115,115,32,"<0.1482.0>",32,119,105,116,104,32,"1",32,110,101,105,103,104,98,111,117,114,115,32,"exited",32,119,105,116,104,32,114,101,97,115,111,110,58,32,[[123,["timeout",44,[123,["gen_server",44,"call",44,[91,["leo_tran_serializable_cntnr",44,[123,["run",44,["<<","\"testp/test.large\"",">>"],44,"null",44,"null",44,"leo_large_object_get_handler",44,[123,["10",44,[123,["http_req",44,"#Port<0.2133>",44,"ranch_tcp",44,"close",44,"<0.1478.0>",44,["<<","\"GET\"",">>"],44,"'HTTP/1.1'",44,[123,[[123,["127",44,"0",44,"0",44,"1"],125],44,"35888"],125],44,["<<","\"testp.localhost\"",">>"],44,"undefined",44,"8080",44,["<<","\"/test.large\"",">>"],44,"undefined",44,"<<>>",44,"[]",44,"[]",44,[91,[[123,[["<<","\"host\"",">>"],44,["<<","\"testp.localhost:8080\"",">>"]],125],44,[123,[["<<","\"user-agent\"",">>"],44,["<<","\"aws-sdk-php2/2.8.14 Guzzle/3.9.3 curl/7.35.0 PHP/5.5.9-1ubuntu4.13\"",">>"]],125],44,[123,[["<<","\"date\"",">>"],44,["<<","\"Mon, 26 Oct 2015 01:39:17 +0000\"",">>"]],125],44,[123,[["<<","\"authorization\"",">>"],44,46,46,46],125],44,46,46,46],93],44,46,46,46],125],44,46,46,46],125],44,46,46,46],125],44,46,46,46],93]],125]],125]," in ",[["gen_server",58,"terminate",47,"7"],[32,108,105,110,101,32,"804"]]]]]
```

**Comment by PatelParas** [comment]
Thank you for creating this issue, i am Waiting for this solution.

**Comment by windkit** [comment]
In general, this problem happens when the network speed slow.

In aws-sdk-php, stream wrapper would try to buffer the first 2MB in memory (in full speed).
Therefore, the test program would always stop around 2MB mark.

Behind the scene, LeoFS would close the TCP connection (because of the crash from leo_tran timeout)
However, aws-sdk-php seems not aware of this and keep holding...

**Comment by windkit** [comment]
In 1.4, leo_tran is used in leo_large_object_get_handler to prevent duplicate fetching of object.

However, the current implementation have an implicit assumption of the whole object would be delivered within default gen_sever timeout (which is 30 seconds)

leo_large_object_get_handler -> leo_tran:run -> gen_server:call -> run -> handle_loop

As the result, when the transfer takes longer than 30 seconds, the gen_server:call would timeout and the socket would be closed.

**Comment by windkit** [comment]
In 1.2, the socket would be timeout.

```
[E]	gateway_0@127.0.0.1	2015-10-27 13:37:16.371354 +0900	1445920636	leo_large_object_get_handler:handle_loop/3	184	key:testp/test.large	2, index:1, cause:timeout
```

**Comment by windkit** [comment]
In short, the (implicit) lower bound of the transfer speed is

- (1.2) chunked_obj_len / 30 seconds (5MB / 30s = 167Kbps)
- (1.4) total object length / 30 seconds (50MB / 30s = 1.67Mbps)

**Comment by windkit** [comment]
To solve the issue by providing a way to configure the lower bound for transfer rate.
Following PRs are created.
https://github.com/leo-project/leo_commons/pull/6
https://github.com/leo-project/leo_gateway/pull/30

In short, object transfer to clients is broken down to smaller units. Configuring different chunk size would imply different bound for transfer rate. With 128KB (default) send chunks, 30s (default) send_timeout the implied rate would be ~4KB/s

**Comment by yosukehara** [comment]
@windkit Thanks for your contribution. Tomorrow, we'll check all of your requests.

**Comment by PatelParas** [comment]
@windkit Thank you can you build share me ebin directory for V1.2.11 leo_gateway node ?.
So that we can use this feature without waiting next Release and Upgrade.

**Comment by yosukehara** [comment]
@PatelParas We're considering in which we're able to include this issue. Tomorrow, we'll discuss that, then comment on this page.

**Comment by PatelParas** [comment]
Thank you  :+1:

**Comment by PatelParas** [comment]
My Comment for point >> this problem happens when the network speed slow.

I noted this issue inside VM environment. which is consist of 1) all in one leofs-VM + 2) PHP-Web Server instance.

**Comment by windkit** [comment]
@PatelParas That refers to `http_throttle` in your case, but in general, it would happen if server -> client connection speed is slow.

The proposed solution has been merged to `develop` branch, please check if possible.

**Comment by windkit** [comment]
Issue with 1.4 is two-fold.

1. It sends objects as once, problem with the send timeout as in 1.2. Thus, similar fix with `chunked_send`
2. There is a 30 seconds timeout during Callbacks for `leo_tran_behaviour`.

While a quick fix for the second problem is to set the `gen_server` timeout at `leo_tran_serializable_cntnr:run` to infinity, I am not sure if it would be fine to do so. Any comment? @mocchira @yosukehara

**Comment by windkit** [comment]
Problem with 1.4 is related to the solution in https://github.com/leo-project/leofs/issues/325

**Comment by mocchira** [comment]
@windkit OK. go ahead with infinity.

**Comment by yosukehara** [comment]
@windkit You can use [leo_tran_serializable_cntnr:run/7](https://github.com/leo-project/leo_tran/blob/develop/src/leo_tran_serializable_cntnr.erl#L84-L93)

**Comment by windkit** [comment]
@yosukehara Thanks for providing the function, I will create a PR for 1.4
