### ISSUE TITLE
[leo_gateway] Spend much time on generating an xml object

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#432]
I've found its bottleneck, which is [leo_gateway_s3_api: generate_bucket_xml/4](https://github.com/leo-project/leo_gateway/blob/1.4/src/leo_gateway_s3_api.erl#L1392). LeoGateway spent much time on generating xml object as bellow:

```erlang
%% Total num of objects a dir: 500
%% a-1. Get metadata of objects under a dir
19.906ms
%% b-1. [a] + Generating an XML object
468.971ms

%% a-2. Get metadata of objects under a dir
15.271ms
%% b-2. [a] + Generating an XML object
447.335ms

%% Total num of objects a dir: 750
%% a-3. Get metadata of objects under a dir
22.585ms
%% b-3. [a] + Generating an XML object
927.6ms

%% a-4. Get metadata of objects under a dir
27.703ms
%% b-4. [a] + Generating an XML object
961.202ms

%% a-5. Get metadata of objects under a dir
26.102ms
%% b-5. [a] + Generating an XML object
951.484ms
```

**Comment by windkit** [comment]
To me, this is caused by the repetitive copy with `lists:append`

**Comment by yosukehara** [comment]
Performance of generating an XML object has been improved as below:

```erlang
%% Total num of objects = 500:
* 95.47ms
* 74.952ms
* 67.268ms

%% Total num of objects = 750:
* 117.526ms
* 113.954ms
* 110.392ms

%% Total num of objects = 1000:
* 197.871ms
* 192.354ms
* 184.356ms
```

**Comment by yosukehara** [comment]
Tomorrow, I'll check whether there are bugs or not, then I'll close this issue.

**Comment by windkit** [comment]
To me, a quick fix would be using a deep list instead of flat list as I think `lists:append` would incur list copy repetitively. `cowboy_req:reply` could accept an iolist as body content.

```erlang 
1.lists:append(Acc, "<Contents>", ...)
2.[Acc, lists:append(["<Contents>",....])]
```
As a side note, I want to ask if the performance difference of above codes is huge

**Comment by yosukehara** [comment]
DONE: https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/ls/20151112_1
