### ISSUE TITLE
[bitcask][leo_mq] Replace bitcask used by leo_mq behind the scene with an appropriate one

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#437]
As the number of elements  in a bitcask have increased,
Its performance can be degrade due to the fact it's unordered.

Creating a module wrapping leveldb is one of the solutions like the below.
https://github.com/wavii/darner/blob/master/src/queue/queue.cpp

**Comment by yosukehara** [comment]
I've considered we fix this issue. I'll replace ``leo_backend_db_bitcask`` with ``leo_backend_db_eleveldb`` because I only implement a feature of management of a # of keys.

**Comment by yosukehara** [comment]
I've fixed this issue.
