### ISSUE TITLE
[leo_s3_libs] Requests to leo_gateway take too much time when leo_manager is down

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#438]
The below link is a issue report from a user.
https://groups.google.com/d/msg/leoproject_leofs/p_DhiIz5WL8/h1bJjoamBgAJ

The reason why this happen is that 
If ACL records stored at leo_gateway got expired,
Since leo_gateway ask leo_manager to retrieve the latest ACL records,
This could happen.

**Comment by mocchira** [comment]
@windkit please fix.
let me know if you have any problem.

**Comment by windkit** [comment]
@mocchira 
I have created a PR for the develop branch at
https://github.com/leo-project/leo_s3_libs/pull/4

**Comment by mocchira** [comment]
@windkit Reviewed. Please check that on https://github.com/leo-project/leo_s3_libs/pull/4.
