### ISSUE TITLE
[leo_erasure] double free & memory leak and fragmentation

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#440]
## Problem
- double free
  - https://github.com/leo-project/leo_erasure/blob/develop/c_src/jerasure_mod.cpp#L148-L149
  - https://github.com/leo-project/leo_erasure/blob/develop/c_src/jerasure_mod.cpp#L263-L264

- `real_decoding_matrix` will leak at the below blocks
  - https://github.com/leo-project/leo_erasure/blob/develop/c_src/jerasure_mod.cpp#L517
  - https://github.com/leo-project/leo_erasure/blob/develop/c_src/jerasure_mod.cpp#L536
  - https://github.com/leo-project/leo_erasure/blob/develop/c_src/jerasure_mod.cpp#L640
  - https://github.com/leo-project/leo_erasure/blob/develop/c_src/jerasure_mod.cpp#L659

- fragmentation
  - Since there are lots of malloc/free calls over multiple threads under heavy load, Heap can be fragmented and that may result in failing malloc ( return NULL ) and may crash due to the above issues.

## Solution
dead simple.
Allocating on stack will solve all problems.

**Comment by mocchira** [comment]
and also scan-build found out the below problem.
http://ec2-54-168-172-221.ap-northeast-1.compute.amazonaws.com/leo_erasure/analysis/2015-12-24-013355-13186-1/report-afb5e5.html#EndPath

**Comment by mocchira** [comment]
@windkit Please fix this issue.

**Comment by windkit** [comment]
@mocchira nope, these issues are not the cause of the crash.

**Comment by mocchira** [comment]
@windkit please share the reason why nope since I don't know any test result.

**Comment by windkit** [comment]
@mocchira I tested it after the fixes with https://github.com/leo-project/leo_erasure/commit/d7f735732cf1c70278eebc5650ac1bc1d9b1a79e

**Comment by mocchira** [comment]
@windkit 

> If NOT, 
> you may need to replace other variables currently allocated on the heap with on the stack.

Can you try that?

and also I'd like you to share the core files and syslog when you faced crashes.

**Comment by windkit** [comment]
@mocchira currently i am testing another fix
https://github.com/leo-project/leo_erasure/tree/fix-jerasure
and seems it works...

below would be some error log with `dmesg`
```
beam.smp[30089]: segfault at 7f15e8023430 ip 00007f15e8023430 sp 00007f16d40b6e08 error 15
beam.smp[30088]: segfault at 7f15e8023430 ip 00007f15e8023430 sp 00007f16d4ab7e08 error 15
beam.smp[3409]: segfault at 0 ip (null) sp 00007faafc16a088 error 14 in beam.smp[400000+2ce000]
```

**Comment by mocchira** [comment]
Good to hear that :)

Anyway,
I'd recommend you to do the fix I mentioned the above to prevent memory from being fragmented as minimum as possible.

> If NOT, 
> you may need to replace other variables currently allocated on the heap with on the stack.

I think that all `talloced` variables  should be allocated on the stack.

**Comment by windkit** [comment]
@mocchira 
Ya, that is a big problem with JErasure. But it simply means a complete refactoring of the JErasure Code.
Probably work on it after 1.4.0-pre3

**Comment by mocchira** [comment]
@windkit OK. Got it.

**Comment by windkit** [comment]
I have implemented and tested a separate code path which avoid heap allocation with
https://github.com/windkit/leo_erasure/tree/no_alloc
https://github.com/windkit/jerasure/tree/no_alloc
and it seems stable now

I am working on rebasing the commits and few code refactoring. Afterwards I would create Pull Request of the two repositories.

**Comment by mocchira** [comment]
@windkit GJ!
Looking forward to seeing your PR.

**Comment by windkit** [comment]
PRs are created for JErasure and leo_jerasure at

https://github.com/leo-project/jerasure/pull/1
https://github.com/leo-project/leo_erasure/pull/1

Please help to review and comment them @mocchira

**Comment by yosukehara** [comment]
We recognised we fixed this issue:
* [20160126_vandrs_15m_r49w1_360min](https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.4/erasure_code/20160126_vandrs_15m_r49w1_360min)
