### ISSUE TITLE
[leo_storage] When removing a large size object, a high-latency issue can be happened

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#442]
I/we need to improve [delete_objects_under_dir/1 function](https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_handler_object.erl#L448-L477). After modifying this function, we'll be testing at our LeoFS environment.

**Comment by yosukehara** [comment]
I already fixed this issue two weeks ago, then we need to test this on our environment.

**Comment by mocchira** [comment]
Done tests.
