### ISSUE TITLE
[leo_backend_db] May take too much time when restarting leo_storage

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#445]
The code block at the below link may cause leo_storage taking too much time to restart.
https://github.com/leo-project/leo_backend_db/blob/1.1.8/src/leo_backend_db_eleveldb.erl#L83-L85

**Comment by yosukehara** [comment]
Re-launch of leo_backend_db is dramatically increased - [TEST for #445](https://gist.github.com/yosukehara/0dd81413916bafea946a)

#### Before
- version:
    - leo_backend_db ``v1.1.15``
- result:
    - duration of re-launch of the DBs: 68834ms
```erlang
> leo_backend_db_bench:benchmark('1.1', 'test', "test/db/").
{ok,68834}
```

#### After:
- version:
    - leo_backend_db ``develop-branch``
- result:
    - duration of re-launch of the DBs: 41ms
```erlang
> leo_backend_db_bench:benchmark('1.2', 'test', "test/db/").
{ok,41}
```
