### ISSUE TITLE
[leo_object_storage] Unnecessary a file:position call when opening a AVS file

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#446]
Since leo_object_storage_haystack open a AVS file with `append` option,
`file:position` call at https://github.com/leo-project/leo_object_storage/blob/1.2.7/src/leo_object_storage_haystack.erl#L318 seems to be unnecessary.

**Comment by yosukehara** [comment]
@mocchira Thanks for filing the issue. I've just modified the code, please check it.

**Comment by yosukehara** [comment]
Since I finished tests, I've closed this issue.

**Comment by mocchira** [comment]
@yosukehara thanks.
