### ISSUE TITLE
[all] there are some possibilities that some supervisours don't restart their child as we expect

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#447]
For example,
`leo_mq_sup` doesn't restart a `leo_mq_publisher` worker process properly.

**Comment by yosukehara** [comment]
Thanks for your report.
We need to implement and deliver **a system diagnosis feature for LeoFS**. I'll consider how we implement that with [v1.2.20](https://github.com/leo-project/leofs/milestones/1.2.20).

**Comment by yosukehara** [comment]
We've started developing [LeoFS Doctor](https://github.com/leo-project/leofs_doctor) to be able to investigate any LeoFS systems more easily and more quickly.

**Comment by yosukehara** [comment]
We can use [LeoFS Doctor](https://github.com/leo-project/leofs_doctor) and [Erlang Observer](http://erlang.org/doc/apps/observer/observer_ug.html) to find this issue. Actually, I could fix the issue.
