### ISSUE TITLE
[1.2][1.4] Read Performance is much lower when objects are spread across buckets

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#449]
### Description
During COSBench testing, read performance is significant lower in the case of 20 buckets than 1 bucket with 1 million objects in total (`20 x 50,000` v.s. `1 x 1,000,000`)

### Test Setup
 - Workers: `4` drivers x `25` workers
 - Object Size: `128 KB`
 - Number of Objects:
   1. `1` bucket x `1,000,000` objects
   2. `20` buckets x `50,000` objects

- Test Flow
  1. `prepare-write`: PUT 1,000,000 Objects into LeoFS
  2. `main`: read (`98%`), write (`2%`) Test across the objects (10 minutes)

### System Setup
- LeoFS Version: 1.4.0-dev (Erlang 17.5)
- LeoFS Setup: 1x Gateway, 5 x Storage
- LeoFS Configuration: [conf.tar.gz](https://github.com/leo-project/leofs/files/142042/conf.tar.gz)
- OS: Ubuntu 14.04.3 x64
- Hardware: Xeon E5-2630 v3, 32GB Ram, (Storage) 6x 15k sas HDD, RAID-0

#### `1` bucket x `1,000,000` objects
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
 prepare | 5398.91 | 691.06 MB/S  | 100% 
 main-read | 4390.42 | 561.97 MB/S | 100 % 
 main-write | 90.15 | 11.54 MB/S | 100% 

Timeline Status [c1_f1m_128k_timeline.xlsx](https://github.com/leo-project/leofs/files/142079/c1_f1m_128k_timeline.xlsx)

#### `20` buckets x `50,000` objects
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
 prepare | 6220.5 | 796.22 MB/S  | 100% 
 main-read | 1960.62 | 250.96 MB/S | 100 % 
 main-write | 37.55 | 4.81 MB/S | 94.63%

Timeline Status [c20_f50k_128k_timeline.xlsx](https://github.com/leo-project/leofs/files/142060/c20_f50k_128k_timeline.xlsx)

#### `1` bucket x `1,000,000` objects
![c1_f1m_128k](https://cloud.githubusercontent.com/assets/360884/13244713/afcf25ee-da4b-11e5-8583-ec31c7788ed5.png)

#### `20` buckets x `50,000` objects
![c20_f50k_128k](https://cloud.githubusercontent.com/assets/360884/13244748/1224a6ce-da4c-11e5-8406-54497e3e0ca8.png)

#### `20` buckets x `50,000` objects
Error Log (Gateway): [error.g0.txt](https://github.com/leo-project/leofs/files/142050/error.g0.txt)
Crash Dump (Gateway): [erl_crash.g0.zip](https://github.com/leo-project/leofs/files/142051/erl_crash.g0.zip)
(Crash Dump is force generated with SIGUSR1 from a seperate run)

**Comment by yosukehara** [comment]
@windkit Thanks for your report.
We need to also check LeoFS v1.2.20-dev with the same situation, I think.

**Comment by mocchira** [comment]
@windkit @yosukehara 
Since there are no errors on leo_gateway except `timeout` and `closed`,
I think something goes wrong at leo_storage(s).
```
$ cat ~/Downloads/error.g0.txt |grep -v timeout|grep -v closed
$ ## no output
```

- Notes
  - Obviously the increase of memory|process usages on leo_gateway was due to timeout and
  - error `closed` probably happened due to COSBench's timeout setting.

so could you check|share the storage error logs with us?

**Comment by windkit** [comment]
@mocchira There are no error logs at leo_storage....

Ya, I agree that some connections are timeout at COSBench side

**Comment by mocchira** [comment]
Also I noticed all timeout happended when the http method was `PUT`.
So there may be code block handling `PUT` which is blocked due to some reason.
I'm going to check that.

**Comment by yosukehara** [comment]
@windkit To recognise bottleneck of the put-operation, do you think you could use [entop](https://github.com/kato-im/entop) to monitor a Leo's storage-node, and share the results?

**Comment by windkit** [comment]
Here please find the screenshot of entop from S0 (others give similar results)
![s0](https://cloud.githubusercontent.com/assets/360884/13273034/f115e6e4-dae3-11e5-81c9-1a574ee60a71.png)
![s0_2](https://cloud.githubusercontent.com/assets/360884/13273035/f119804c-dae3-11e5-88c2-ed9e3b6c50ad.png)

**Comment by mocchira** [comment]
It seems that the screenshot was captured during idle (no benchmark running) right?
if so, please do entop during running benchmark.
I expect that entop show us a guilty function via the current function column while timeout happen on leo_gateway.

**Comment by windkit** [comment]
@yosukehara No, it is captured during the time of 98% Read 2%Write, where leo_gateway has many stuck processes

**Comment by windkit** [comment]
In case you want to check the whole process, below would be a video captured at S0
https://drive.google.com/file/d/0B26vAI5J5WrhbzZ1cGlrZjNwbHM/view?usp=sharing

The first 3 minutes would be the loading phase (write `1,000,000` objects)

**Comment by mocchira** [comment]
@windkit OK.
I'm waiting for getting the video available on my pc.

**Comment by mocchira** [comment]
@windkit @yosukehara 
I noticed from the entop result that 
some `leo_object_storage` processes got stuck with `prim_file:drv_get_response`.
This basically means erlang's port driver for file I/O is waiting for file I/O requests.
so writing to a AVS file OR writing to files managed by leveldb could be bottlenecked.

**Comment by mocchira** [comment]
@windkit @yosukehara 
so please watch the `iostats` and also leveldb's compaction status.
In order to retrieve the compaction status from leveldb, we need to call [eleveldb:status](https://github.com/basho/eleveldb/blob/develop/src/eleveldb.erl#L247) like the below.

``` erlang
eleveldb:status(Ref, "leveldb.stats").
``` 

So I think that some patches to leo_backend_db will be needed.

**Comment by yosukehara** [comment]
@windkit @mocchira 
It could be solved that you modify the LeoStorage's configuration, [obj_containers.num_of_containers](https://github.com/leo-project/leo_storage/blob/develop/priv/leo_storage.conf#L46) from *[8]* to *[32]* (or *[64]*) because LeoStorage is able to balance accessing object-containers.

**Comment by windkit** [comment]
Actually that's what I want to do at the beginning, "To sort out bottleneck, to guide parameters setting"

But in this case, what bothers me is why the number of containers have effect on the performance......

**Comment by windkit** [comment]
This would be a screenshot of `iostat -dx 1` from one storage node
![iostat](https://cloud.githubusercontent.com/assets/360884/13275034/ee553300-daf3-11e5-991c-299a772ae28c.png)
`/dev/sdc` is the 6x HDD RAID-0 served as the avs store

The video could be found at
https://drive.google.com/file/d/0B26vAI5J5WrhYlpmVnJHMWRWaEU/view?usp=sharing

Again, around the first 1 minute is the loading phase

**Comment by windkit** [comment]
I can now confirm the issue also happens with 1.2.20-dev.
Situation is similar, no log files at `leo_storage`, error log at `leo_gateway` is filled with closed connections

**Comment by windkit** [comment]
To clarify the situation, the same issue happens with **100% READ** Test
Write is faster with 20 buckets, but read is slower

### Observation
#### `1` bucket x `1,000,000` objects
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
 prepare | 5238.6 | 670.54 MB/S  | 100% 
 read | 4485.12 | 574.1 MB/S | 100 % 

#### `20` buckets x `50,000` objects
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
 prepare | 6035.35 | 772.53 MB/S  | 100% 
 read | 1657.36 | 212.14 MB/S | 100 % 

### Grafana 
#### `1` bucket x `1,000,000` objects
![r100_c1_f1m_128k](https://cloud.githubusercontent.com/assets/360884/13308115/033dd680-dbb4-11e5-8c87-4b77d1b01480.png)

#### `20` bucket x `50,000` objects
![r100_c20_f50k_128k](https://cloud.githubusercontent.com/assets/360884/13308342/dc5b7e44-dbb5-11e5-8313-0b6d6538ac1b.png)

### Entop/Iostat
#### `20` bucket x `50,000` objects
![r100_entop](https://cloud.githubusercontent.com/assets/360884/13308344/e0c5c61a-dbb5-11e5-8a05-bcab84f67922.png)
Entop Video: https://drive.google.com/file/d/0B26vAI5J5WrhaGRZSnU0TnpVNWs/view?usp=sharing

![r100_iostat](https://cloud.githubusercontent.com/assets/360884/13308348/e45121a8-dbb5-11e5-989b-738a7c81425a.png)
Iostat Video: https://drive.google.com/file/d/0B26vAI5J5WrhU3NwdURvQjJUYnc/view?usp=sharing

**Comment by yosukehara** [comment]
@windkit It seems that it is not apple-to-apple test because the write-operation of "20 bucket x 50,000 objects" was executed during the test as below:
![dc5b7e44-dbb5-11e5-8313-0b6d6538ac1b](https://cloud.githubusercontent.com/assets/148770/13309638/0178dd14-dbc2-11e5-8794-ae916e21280b.jpg)

**Comment by windkit** [comment]
@yosukehara At the client side, the script and flow are always the same. 
And there are no write request from client at all during the read phase. (which can be verified with iftop at client)
![iftop](https://cloud.githubusercontent.com/assets/360884/13309928/aab13eba-dbc4-11e5-986e-9cff607ac88f.png)

To me, there is some issues with the statistics reported from LeoFS SNMP
The test only last for 15 minutes (from 11:31 TO 11:47) but it keeps reporting the same number with snmp afterward
![untitled](https://cloud.githubusercontent.com/assets/360884/13309858/bb08bd16-dbc3-11e5-9be5-391ff4c4fa67.png)

**Comment by windkit** [comment]
### Test with bitcask instead of leveldb
(`obj_containers.metadata_storage = bitcask`)
#### `20` buckets x `50,000` objects
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
 prepare | 6839.46 | 875.45 MB/S  | 100% 
 read | 901.82 | 115.43 MB/S | 100 % 

![r100_c20_f50k_128k_bitcask](https://cloud.githubusercontent.com/assets/360884/13310694/9c081062-dbcb-11e5-924e-82f310a79af2.png)

iostat Video:
https://drive.google.com/file/d/0B26vAI5J5WrhRmFzcGhrSEJkakk/view?usp=sharing

entop Video:
https://drive.google.com/file/d/0B26vAI5J5WrhOGtFQ1JKNDFSdGc/view?usp=sharing

**Comment by windkit** [comment]
### Test with 32 Containers
(obj_containers.num_of_containers = [32])
#### `20` buckets x `50,000` objects
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
 prepare | 6409.3 | 820.39 MB/S  | 100% 
 read | 1509.43 | 193.21 MB/S | 100 % 

![r100_c20_f50k_128k_avs32](https://cloud.githubusercontent.com/assets/360884/13311173/86ef4476-dbcf-11e5-98d6-84dbbe9860de.png)

iostat Video:
https://drive.google.com/file/d/0B26vAI5J5WrhUkt0Tld6MDZKTE0/view?usp=sharing

entop Video:
https://drive.google.com/file/d/0B26vAI5J5WrhazdzcHdXMFdmYWc/view?usp=sharing

**Comment by windkit** [comment]
To test if the bottleneck is disk I/O related to metadata `leo_backend_db`, this test would move it to `ramdisk`

(Sorry that I forgot to change the configuration, this is also done with 32 containers, leveldb)

**Setup**
```bash
$ mkdir /dev/shm/metadata
$ ln -s /dev/shm/metadata /data/leofs/
```
**Verify ramdisk is used**
```bash
$ du -sh metadata/
123M    metadata/
```

### Test with 32 Containers + Ramdisk backed leveldb
(`obj_containers.num_of_containers = [32]`)
#### `20` buckets x `50,000` objects
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
 prepare | 6220.53 | 796.23 MB/S | 100% 
 read | 1377.69 | 176.34 MB/S | 100 % 

![r100_c20_f50k_128k_avs32_ramdisk](https://cloud.githubusercontent.com/assets/360884/13313347/96f0903a-dbe0-11e5-87b7-06a6845c0648.png)
1. (-16:16:10) Loading Phase (PUT 1,000,000 Objects)
2. (16:16:10 - 16:27:50) Read
3. (16:27:50-) Delete Phase

Cosbench Log: 
[workload-log.zip](https://github.com/leo-project/leofs/files/146137/workload-log.zip)

**Comment by windkit** [comment]
### `1` Bucket x `1,000,000` Objects (leveldb, 8 avs)

Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
prepare | 5771.23 | 738.72 MB/S | 100%
read | 4684.54 | 599.62 MB/S | 100%
![grafana-marked](https://cloud.githubusercontent.com/assets/360884/13314143/d844299c-dbe6-11e5-8049-05f783b33349.png)

Error Logs: (None)
Cosbench: [workload-log.zip](https://github.com/leo-project/leofs/files/146187/workload-log.zip)
entop Video: https://rak.box.com/s/zlmu82mywzdpx50w3i9zh3798s7fuy7l
iostat Video: https://rak.box.com/s/ltbfjm5m7tel643b0gm34wy6zjv7m6ad

**Comment by windkit** [comment]
### `20` Bucket x `50,000` Objects (leveldb (ramdisk), 8 avs)

Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
prepare | 6723.5 | 860.61 MB/S | 100%
read | 1778.76 | 227.68 MB/S | 100%
![grafana-marked](https://cloud.githubusercontent.com/assets/360884/13314938/2787274e-dbeb-11e5-821d-d0bd87122abc.png)

Error Logs: [g0.error.txt](https://github.com/leo-project/leofs/files/146230/g0.error.txt)
Cosbench: [workload-log.zip](https://github.com/leo-project/leofs/files/146231/workload-log.zip)
entop Video: (record crashed)
iostat Video: https://rak.box.com/s/6vo680yjcrzxc0hn1or13nqe2tdmsddi

**Comment by windkit** [comment]
### `20` Bucket x `50,000` Objects (bitcask (ramdisk), 8 avs)

Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
prepare-write | 6977.08 | 893.07 MB/S | 100%
read  | 769.71 | 98.52 MB/S | 100%
![grafana-marked](https://cloud.githubusercontent.com/assets/360884/13315482/440d2ec4-dbee-11e5-8007-981db8405f52.png)

Error Logs: [g0.error.txt](https://github.com/leo-project/leofs/files/146269/g0.error.txt)
Cosbench: [workload-log.zip](https://github.com/leo-project/leofs/files/146273/workload-log.zip)
entop Video: https://rak.box.com/s/2iwxpgctsufts72p369es8rcqiocnjfc
iostat Video: https://rak.box.com/s/pa58hij5c1nxa8b0bcwbgl7sw5y5k431

**Comment by windkit** [comment]
As suspect there would be similar problem with 4KB Objects
I carried a small test with small object, (1 x 1,000,000 and 20 x 50,000) with GW cache disabled

It shows similar problem between the two cases. For 1 bucket case, it delivers ~100MB/s while with 20 buckets, it delivers < 10MB/s

I will clean up this page tomorrow by moving cases to https://github.com/leo-project/notes

**Comment by windkit** [comment]
## Test with 4KB Objects (no GW Cache)

### `1` x `1,000,000`
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
prepare-write | 11176.92 | 44.71 MB/S | 100% 
read | 26203.84 | 104.82 MB/S | 100% 

### `20` x `50,000`
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
prepare-write | 21493.39 | 85.97 MB/S | 100%
read | 294.57 | 1.18 MB/S | 100%

**Comment by windkit** [comment]
## Test with 4KB Objects (no GW Cache, All data on ramdisk)
In short, it seems the I/O on storage is not the bottleneck

### `20` x `50,000`
Task | OPS | Bandwidth | Success Ratio |
-------|-------|---------------|--------------------|
prepare-write | 21090.04 | 84.36 MB/S | 100%
read | 290.86 | 1.16 MB/S | 100%

**Comment by windkit** [comment]
## The issue is related to CosBench
In the case of 20 Buckets, TCP Connections kept closed
(Ya, some FIN are even initialed from CosBench)

It may because they included a very old version of aws-sdk-java
(Probably hit by this https://github.com/aws/aws-sdk-java/blame/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1186)
```java
	    // Hold a reference to this client while the InputStream is still
	    // around - otherwise a finalizer in the HttpClient may reset the
	    // underlying TCP connection out from under us.
```

### Pcap for 1 Bucket (Normal)
[cosbench_c1_normal_filtered.zip](https://github.com/leo-project/leofs/files/147791/cosbench_c1_normal_filtered.zip)
### Pcap for 20 Buckets (Abnormal)
[cosbench_c20_filtered.zip](https://github.com/leo-project/leofs/files/147794/cosbench_c20_filtered.zip)
