### ISSUE TITLE
[leo_manager] manager may crash when # of histories is pretty large

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#453]
due to the below code.
https://github.com/leo-project/leo_manager/blob/develop/src/leo_manager_mnesia.erl#L548

We need to come up with the alternative to provide kind of auto increment id.

**Comment by yosukehara** [comment]
Link: leo-project/leofs/issues/441

**Comment by yosukehara** [comment]
Related Issue: leo-project/leofs/issues/444
