### ISSUE TITLE
[leo_storage] Compaction is not executed when some nodes are empty

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#455]
### Description
Put an object to LeoFS and then delete it, one would expect auto compaction will start and reclaim the disk space, but it won't happen

### Cause
 1. When some storage nodes are empty, Zero division error happens in checking candidates for compaction
  * https://github.com/leo-project/leo_storage/blob/develop/src/leo_storage_watchdog_sub.erl#L272

2. Errors are caught at `leo_storage_sub` but do not leave any error logs
 * https://github.com/leo-project/leo_watchdog/blob/develop/src/leo_watchdog_sub.erl#L139
 * https://github.com/leo-project/leo_watchdog/blob/develop/src/leo_watchdog_sub.erl#L150

**Comment by yosukehara** [comment]
@windkit I've fixed this issue. When you have time, please test it.

**Comment by windkit** [comment]
@yosukehara I can confirm this issue is fixed with the commits.
