### ISSUE TITLE
[leofs_docs] Compaction interval configuration is missing at Auto-compaction Section

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#457]
### Description
One of the configurations for auto compaction is missing in the documentation (Auto-compaction Section)
```
##[compaction] execution intarval time(sec) - default:3600(sec) (60min)
autonomic_op.compaction.interval = 3600
```
This is to limit the frequency for auto compaction check

http://leo-project.net/leofs/docs/configuration/configuration_8.html
(O.T. `interval` is misspelled as `intarval` in `leo_storage.conf` around the repo)

**Comment by yosukehara** [comment]
I've solved this issue, also fix a typo in ``leo_storage.conf``:
* https://github.com/leo-project/leo_storage/commit/63d7cdeb39aa7cbc0c0c5e51211b1d822e441df5
