### ISSUE TITLE
[leo_storage] Consider checking/reserving disk space for compaction

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#465]
### Description

When disk space is used up with many overwritten/deleted objects, compaction cannot reclaim the space as there would be no space for new avs file.

`leo_storage` may do the check before appending new objects, if there is insufficient space, reject the put request.

**Comment by mocchira** [comment]
Since https://github.com/leo-project/leofs/issues/592 has already solved the problem, I'll close the issue.
