### ISSUE TITLE
[leo_storage] Possibility to become imbalance of a total mq's msgs during a rebalance (detach-node)

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#472]
## Description
In the current version, v1.2.21, after executing ``detach`` and ``rebalance`` command, LeoStorage assigns consumption messages of a rebalance into a primary of a vnode(RING). According to that, there is a possibility to become imbalance of a total messages between storage-nodes.

## Solution
``LeoStorage`` adjusts a total number of assigned storage-nodes so that a storage-node is able to have same consumption messages with other nodes into a LeoFS' cluster.

**Comment by windkit** [comment]
![grafana](https://cloud.githubusercontent.com/assets/360884/14345031/d221cae0-fce5-11e5-8252-74014220bad5.png)

**Comment by yosukehara** [comment]
This issue seems to improve with a yesterday update. We're going to test the detach-feature for more several times.

[result]
- 1M objects rebalance *(detach)*
- Duration: approx 50 min

![screencapture-222-230-139-43-13000-dashboard-db-leofs-dashboard-yosuke-1463104849355](https://cloud.githubusercontent.com/assets/148770/15235926/b49252f2-18fa-11e6-9ded-f52ced87a7a7.png)

**Comment by yosukehara** [comment]
To be honest, I've found that there is one issue which is `imbalance remote access` during the data-rebalance like as below:

<img width="1895" alt="screen shot 2016-05-13 at 15 47 41" src="https://cloud.githubusercontent.com/assets/148770/15240171/b3890df6-1922-11e6-891d-0a7456981784.png">

In the next action, I need to fix `imbalance remote access` of the data-rebalance.

**Comment by yosukehara** [comment]
We've check the data-rebalance performance after executing a detach node **from 8 nodes to 7 nodes** as below:

[Result]
- **10M objects rebalance** (detach)
- Duration: **approx 11 hours**

![screencapture-222-230-139-43-13000-dashboard-db-leofs-dashboard-yosuke-1463227781349](https://cloud.githubusercontent.com/assets/148770/15268421/eacb7122-1a18-11e6-8983-e91da671eddb.png)

As I mentioned at the former comment, I'm going to improve the remote access processing as the next action.

**Comment by yosukehara** [comment]
We've checked the data-rebalance performance again, which is the same situation of [the previous test](https://github.com/leo-project/leofs/issues/472#issuecomment-219217280). The data-rebalance performance has been dramatically increased, the duration time **from 11 hours to 8.5 hours**.

![screencapture-222-230-139-43-13000-dashboard-db-leofs-dashboard-yosuke-rebalance-1463440448863](https://cloud.githubusercontent.com/assets/148770/15306817/dbeeb17c-1c08-11e6-95b5-38cd6d3e0b84.png)

In the next action, we will check the data-rebalance performance when turning on the watchdog feature.

**Comment by yosukehara** [comment]
Today, we've recognized this issue was fixed.
