### ISSUE TITLE
[leo_manager] Enforce -smp enabled by default

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#473]
for single core environments as well as leo_storage.
reported on https://github.com/leo-project/leo_storage/issues/9

**Comment by yosukehara** [comment]
Thanks for reporting. I've confirmed leo_storage, leo_gateway and leo_manager, then recognized leo_manager does not support that yet:

* leo_gateway:
    * [leo_gateway.con](https://github.com/leo-project/leo_gateway/blob/develop/priv/leo_gateway.conf#L321)
    * [leo_gateway.schema](https://github.com/leo-project/leo_gateway/blob/develop/priv/leo_gateway.schema#L1103)
* leo_storage:
    * [leo_storage.conf](https://github.com/leo-project/leo_storage/blob/develop/priv/leo_storage.conf#L393)
    * [leo_storage.schema](https://github.com/leo-project/leo_storage/blob/develop/priv/leo_storage.schema#L1215)

**Comment by yosukehara** [comment]
We can set smp mode as below:

- "smp enable"
```
-config ./snmp/snmpa_manager_0/leo_manager_snmp
-smp enable
-env ERL_MAX_ETS_TABLES 256000
-env ERL_CRASH_DUMP ./log/erl_crash.dump
-env ERL_FULLSWEEP_AFTER 0
-env ERL_MAX_PORTS 64000
+A 32
+K true
-setcookie 401321b4
-name manager_0@127.0.0.1
+P 1048576
```

- "smp disable"
```
-config ./snmp/snmpa_manager_0/leo_manager_snmp
-smp disable
-env ERL_MAX_ETS_TABLES 256000
-env ERL_CRASH_DUMP ./log/erl_crash.dump
-env ERL_FULLSWEEP_AFTER 0
-env ERL_MAX_PORTS 64000
+A 32
+K true
-setcookie 401321b4
-name manager_0@127.0.0.1
+P 1048576
```
