### ISSUE TITLE
[leo_storage] Improve the performance of the recover-node

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#474]
We've found the performance of the recover-node is not good so we need to improve its performance to immediately fix inconsistent objects.

In current LeoFS' version - v1.2.21, after executing the recover-node, ``leo_storage`` assigns recovery messages to all storage nodes to avoid lost inconsistent objects, which means a recovered object is duplicated which depends on a routing-table(ring).

I'll improve that ``leo_storage`` reduces recovery messages and is able to do consensus between storage-nodes to ensure solving inconsistency.

![screencapture-222-230-139-43-13000-dashboard-db-leofs-dashboard-yosuke-1460723660525](https://cloud.githubusercontent.com/assets/148770/14563761/80f586c8-035e-11e6-8094-2e1d3a3b4fbb.png)

**Comment by yosukehara** [comment]
I've improved the performance but there is still room for improvement.
Tomorrow, I'll improve [leo_mq's consumer](https://github.com/leo-project/leo_mq/blob/develop/src/leo_mq_consumer.erl) to be able to increase a number of consumption messages per a minute more and more.

![screencapture-222-230-139-43-13000-dashboard-db-leofs-dashboard-yosuke-1460986829452](https://cloud.githubusercontent.com/assets/148770/14606264/5988e84a-05b7-11e6-9b94-2c285568058c.png)

**Comment by windkit** [comment]
![grafana_recover6](https://cloud.githubusercontent.com/assets/360884/14707982/bf0fcdc6-0802-11e6-8b6b-eefae3dd5226.png)
Now the recovery process is more or less bound by disk I/O

**Comment by yosukehara** [comment]
The performance has dramatically increased from 12hours to 7.5hours, finally 20min.

**Comment by yosukehara** [comment]
In this morning, we've tested the recover-node again. There is no issue. So I've closed this.

**Comment by yosukehara** [comment]
We've found a leo_mq's issue as below:

```erlang
[E]	storage_1@127.0.0.1	2016-05-10 12:49:08.421060 +0900	1462852148	
        leo_mq_server:handle_call/3	203	
        {noproc,{gen_server,call,[mq_persistent_node_message_0,first,30000]}}
```
