### ISSUE TITLE
Node 'manager_0@127.0.0.1' not responding to pings

### ISSUE THREAD

**Issue by moisizz** [leo-project/leofs#477]
This happens in clean CentOS Linux 7.1.1503 which was created with vagrant in virtualbox vm with this base box:
https://atlas.hashicorp.com/ceph/boxes/centos7

I have installed leofs from this package:
https://github.com/leo-project/leofs/releases/download/1.2.21/leofs-1.2.21-1.el7.x86_64.rpm

Also i created user and group with name 'leofs' and changed owner and group to all files/directories in /usr/local/leofs/1.2.21 to this user

Now i'm trying to start master node:
[leofs@mon0 1.2.21]$ leo_manager_0/bin/leo_manager start

Then trying to ping it:
[leofs@mon0 1.2.21]$ leo_manager_0/bin/leo_manager ping
pong

And almost immediately it stops responding:
[leofs@mon0 1.2.21]$ leo_manager_0/bin/leo_manager ping
Node 'manager_0@127.0.0.1' not responding to pings.

**Comment by yosukehara** [comment]
Thanks for your report.
Let me know what happen LeoFS' manager on your environment. Do you think you could share two log-files,  ``<leo_manager_0>/log/erlang.log.1`` and ``<leo_manager_0>/log/app/error.<datetime>``?

**Comment by moisizz** [comment]
All log files in leo_manager_0/log/app/ are empty
Here's erlang.log.1 content:

=====
===== LOGGING STARTED Sat May  7 11:41:46 UTC 2016
=====
Exec: /usr/local/leofs/1.2.21/leo_manager_0/erts-6.4.1.5/bin/erlexec -boot /usr/local/leofs/1.2.21/leo_manager_0/releases/1/leo_manager -mode embedded -config /usr/local/leofs/1.2.21/leo_manager_0/etc/app.config -args_file /usr/local/leofs/1.2.21/leo_manager_0/etc/vm.args -- console start
Root: /usr/local/leofs/1.2.21/leo_manager_0
Erlang/OTP 17 [erts-6.4.1.5] [source] [64-bit halfword] [async-threads:32] [kernel-poll:true]

id:leo_logger_file_i, path:"./log/app", filename:"info"
* opening log file is /usr/local/leofs/1.2.21/leo_manager_0/log/app/info.20160507.11.1
id:leo_logger_file_e, path:"./log/app", filename:"error"
* opening log file is /usr/local/leofs/1.2.21/leo_manager_0/log/app/error.20160507.11.1
id:log_id_history_log, path:"./log/app", filename:"cmd_history"
* opening log file is /usr/local/leofs/1.2.21/leo_manager_0/log/app/cmd_history.20160507.11.1

----------------------------------------
If this would be somehow useful i can write instructions how to create exact same environment in virtualbox vm with vagrant in which problem is 100% reproducable.

**Comment by yosukehara** [comment]
I've just reproduced that on my environment, CentOS 7.1, and **one core CPU's machine**. It is related to #473 . You're able to fix this to apply [a patch](https://github.com/leo-project/leo_manager/commit/5376ce366901d4fbcf24ffb1ecc680569d37e710) to both ``leo_manager_0`` and ``leo_manager_1``.

- Need to change files:
    - leo_manager_0
        - leo_manager_0/etc/leo_manager.conf
        - leo_manager_0/etc/leo_manager.schema
    - leo_manager_1
        - leo_manager_1/etc/leo_manager.conf
        - leo_manager_1/etc/leo_manager.schema

**Comment by moisizz** [comment]
This solved the problem, thank you very much!
