### ISSUE TITLE
[leo_gateway] Output access-logs, retrieving object list and removing a directory

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#479]
In order to be able to check operations of **retrieving object list** and **removing a directory** from access-logs, we need to support that. In the current version of LeoFS, object and bucket operation is already covered.

**Comment by windkit** [comment]
For HTTP and S3 API, there is no delete directory operation
To workaround this, clients would retrieve the list of objects with prefix and then delete each objects

For example, to delete a sub directory `test` in bucket `test` with `s3cmd`
```bash
$ ./s3cmd ls s3://test/test
2016-07-20 08:04      1200   s3://test/test/1
$ ./s3cmd rm s3://test/test -r
delete: 's3://test/test/1'
```

Corresponding access log
```
[BUCKET-GET]    test/   test    0   0   2016-07-20 17:05:10.601187 +0900    1469001910601235    200
[BUCKET-GET]    test/   test    0   0   2016-07-20 17:05:13.307045 +0900    1469001913307093    200
[DELETE]    test    test/test/1 0   1200    2016-07-20 17:05:13.313069 +0900    1469001913313140    204
```

**Comment by yosukehara** [comment]
DONE
