### ISSUE TITLE
README has some dead links

### ISSUE THREAD

**Issue by satoryu** [leo-project/leofs#484]
I found two dead links to www.leofs.org in the following two sections of README.md: 

* [Configure LeoFS](https://github.com/leo-project/leofs/blob/master/README.md#configure-leofs)
* [Benchmarking](https://github.com/leo-project/leofs/blob/master/README.md#benchmarking)

**Comment by yosukehara** [comment]
Thank you for your report. I've just fix some dead links.

**Comment by yosukehara** [comment]
I've recognized this issue was fixed, So I closed it.

**Comment by satoryu** [comment]
Thanks 😸
