### ISSUE TITLE
do we have any forwarder for splunk ?

### ISSUE THREAD

**Issue by PatelParas** [leo-project/leofs#495]
do we have any scripts or forwarder which is compatible to splunk so splunk can show log data as well as system metrics related to leofs cluster? e.g. MQ messages, objects, access count, memory, cache, Active objects, total objects etc.....

**Comment by windkit** [comment]
One of our users is using splunk to monitor LeoFS cluster, basically a wrapper with `snmpwalk`

**Comment by yosukehara** [comment]
You're able to easily implement any LeoFS' monitoring agents/log forwarders using `snmp client`. Actually, we already deliver [LeoFS' agent of InfluDB/Telegraf](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/leofs/leofs.go), which is useful for us.

**Comment by yosukehara** [comment]
I'm going to close this issue because we answered.
