### ISSUE TITLE
Add mime type support for application/vnd.android.package-archive

### ISSUE THREAD

**Issue by pannon** [leo-project/leofs#497]
We are planning to serve Android application packages from LeoFS. This requires `application/vnd.android.package-archive` mime type set for the `*.apk` file to correctly function with phone installations.

Some background here https://en.wikipedia.org/wiki/Android_application_package

Please, could we add this to [leo_mime.erl](https://github.com/leo-project/leo_commons/blob/develop/src/leo_mime.erl) ?

Thanks

**Comment by yosukehara** [comment]
Thanks for your report. We're planning to fix this issue with [v1.3.1](https://github.com/leo-project/leofs/projects/1).

**Comment by pannon** [comment]
Greatly appreciated.

**Comment by pannon** [comment]
If it is of any help, I have rebuilt LeoFS 1.3.0 with these changes. Tested it and submitted a pull request https://github.com/leo-project/leo_commons/pull/7

**Comment by yosukehara** [comment]
@pannon It has been merged into `develop`:
https://github.com/leo-project/leo_commons/commit/2dd9946be011967161b7dbbaa54c6f6ea44a4ad5

**Comment by pannon** [comment]
Thanks again @yosukehara

**Comment by yosukehara** [comment]
@pannon This fix has been merged into [v1.3.1](https://github.com/leo-project/leofs/releases/tag/1.3.1).
