### ISSUE TITLE
[leofs_client_tests] Add the boto3

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#509]
https://github.com/boto/boto3

**Comment by mocchira** [comment]
- follow https://boto3.readthedocs.io/en/stable/guide/migrations3.html
- and also configurations|credentials should be retrieved from `~/.aws/{config,credentials}` formatted as described http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by windkit** [comment]
reference
http://boto3.readthedocs.io/en/latest/guide/s3.html

**Comment by windkit** [comment]
boto3.session.client(endpoint_url=)
http://boto3.readthedocs.io/en/latest/_modules/boto3/session.html

**Comment by windkit** [comment]
Added in https://github.com/leo-project/leofs_client_tests/commit/279576ebc7f8a3e83adb0df4c7799f49bcfdfa02

**Comment by mocchira** [comment]
@windkit thank you.
As there are lots of overlaps between boto and boto3,
It'd be great to have a common lib and reusing that from boto(3)
(or have a common business logic and call boto(3) specific logics as needed)
will reduce LOC.

**Comment by windkit** [comment]
Refactored at https://github.com/leo-project/leofs_client_tests/commit/a1e2b2c1348af7d0f43c3ca25d8c6cf27b46a5fe

**Comment by yosukehara** [comment]
@windkit I've reviewed it, and passed a client-test. Thanks.
