### ISSUE TITLE
deb should require netcat-openbsd instead of netcat

### ISSUE THREAD

**Issue by maltejk** [leo-project/leofs#519]
I encountered issues with leofs-adm and netcat-traditional (debian8 amd64, using ubuntu14 package): leofs-adm did not quit after issuing commands like leofs-status. After ^C it throws an error (Error: couldn't connect to LeoFS Manager). 

Installing netcat-openbsd solved the issue.

**Comment by yosukehara** [comment]
@maltejk Thanks for your report. Actually, I don't know different between `netcat-traditional` and `netcat-openbsd `, so I'll reproduce this situation on our environment and check `netcat-openbsd ` to fix this.

**Comment by yosukehara** [comment]
It is related to #500

**Comment by mocchira** [comment]
As @vstax suggested on https://github.com/leo-project/leofs_package/pull/9, we need to document about  netcat-openbsd is needed for leofs-adm.
