### ISSUE TITLE
[leo_object_storage] consume the cpu more than necessary during skipping a garbage block

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#520]
As the current 1.3.0 impl may cause lots of file:pread during skipping a garbage block,
this lead to memcpy(s) between gen_fsm and erlang i/o server so that consume the cpu as much.

**Comment by mocchira** [comment]
can be reduced by buffering data retrieved and reducing the number of calls of file:pread.

**Comment by yosukehara** [comment]
I've designed the new data-compaction feature, which is focusing on how to handle broken parts of an AVS as below:

![improve-data-compaction-1](https://cloud.githubusercontent.com/assets/148770/20337389/35acfdcc-ac14-11e6-985a-1de641de0773.jpg)

![improve-data-compaction-2](https://cloud.githubusercontent.com/assets/148770/20337399/434e1786-ac14-11e6-8f03-d0d8600a3829.jpg)

**Comment by windkit** [comment]
## Observation
The current size of buffer (512 Bytes) is too small to me, it would still take up much CPU time in issuing small size read.

Here is a test with injecting 400MB Random Bytes (from `/dev/urandom`) in a AVS file

## Read 512 Bytes
Took around 2 hours to process the 400MB garbage
![compact_skip_512b](https://cloud.githubusercontent.com/assets/360884/21167089/41bac56a-c1ed-11e6-993b-df1f61de7914.png)

## Read 10 MBytes
Took around 1 hour to process the 400MB garbage
![compact_skip_10mb](https://cloud.githubusercontent.com/assets/360884/21167112/6db0b2a6-c1ed-11e6-88c4-4cbc1ef8d95f.png)

## Summary
The current buffer size is too conservative, and a MB-order value should be used as it gives reasonable performance and not stressing server much.
The bottleneck would then shift to the byte-wise scanning, I wonder if it could be improved.

## Related PR (Configurable Buffer Size)
https://github.com/leo-project/leo_object_storage/pull/7
https://github.com/leo-project/leo_storage/pull/20
