### ISSUE TITLE
[leo_object_storage] elements in pid_pairs may leak when the exec time of a compaction|diagnose is too short

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#521]
https://github.com/leo-project/leo_object_storage/blob/1.3.0/src/leo_compact_fsm_controller.erl#L694
As erlang:monitor is called in async according to its document, 
so there is a possibility that a process which was supposed to be monitored died before getting to be monitored  so that the controller process couldn't get a 'DOWN' message and the leak happened.

I believe that erlang:spawn_monitor will solve but just in case also initialize pid_pairs to empty when starting a compaction|diagnose

**Comment by yosukehara** [comment]
LGTM, thanks.
