### ISSUE TITLE
[leo_object_storage] More strictly checking the header, less file:pread(s) for reading a body

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#527]
As there are only two checks (timestamp, dsize) for converting a binary to a header,
In many case unnecessary file:pread to retrieve its body happen during skipping a garbage.
These can be relaxed by checking the header more strictly ( like checking every fields ) .

**Comment by yosukehara** [comment]
I've recognized this issue, every item should be checked to avoid remaining a broken object in a container I think.

* [leo_object_storage_transformer:header_bin_to_metadata/1](https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_transformer.erl#L319-L369)
* [leo_object_storage_haystack:get_obj_for_new_cntnr/4](https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_haystack.erl#L787-L880)

**Comment by mocchira** [comment]
## check specification in details
- ksize
  - **2048** should be enough upper limit according to http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers since a key must be included in url
- ~~dsize (nop)~~
  - since already checked at leo_object_storage_haystack
- msize
  - **2048** should be enough upper limit according to http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html
- csize
  - should be same with **the limit of dsize** defined at  https://github.com/leo-project/leo_object_storage/blob/1.3.0/include/leo_object_storage.hrl#L202
- cnumber/cindex
  - there is no specification about the upper limit of a file|object stored in leofs though 1PB looks sufficient so that 1PB / 5MB(default chunk size) nealy -eq **2^32/2** should be enough
- offset
  - **16TB** should be enough according to https://kernelnewbies.org/Ext4/#head-4e13646f1961f41bf99152eaf137d309723ac524 (xfs's upper limit is 8EB)
- clock (microseconds unix timestamp)
  - **4102444800000** ( representing 2100/1/1 0:0:0 ) should be enough
- ~~timestamp (nop)~~
  - since already checked at leo_object_storage_transformer
- ~~checksum/ring_hash (nop)~~
  - since it's difficult to set the upper because of its characteristics
- del
  - must be **(0|1)**

@yosukehara could you check the above spec? 
I'll go ahead with this spec if no problem.

**Comment by yosukehara** [comment]
@mocchira Thanks for summarizing the check items.

We actually use `custom-metadata` as two kind of uses, **a metadata of the multi data center replication** and **user defined metadata(s)**. So we cannot fix length of the msize which is  2048 bytes but we can define the length, _( udf-metadata:2048 bytes + mdc-metadata.max_length)_

- [leo_sync_remote_cluster: stack_fun/2](https://github.com/leo-project/leo_storage/blob/develop/src/leo_sync_remote_cluster.erl#L344-L348)

> - msize
>     - 2048 should be enough upper limit according to http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html

**Comment by mocchira** [comment]
@yosukehara thanks.

https://github.com/leo-project/leo_storage/blob/develop/src/leo_sync_remote_cluster.erl#L349 with length(CMeta) == 2048 should be the upper limit.
I'd measure the actual value and use it as the upper limit for msize.

**Comment by mocchira** [comment]
```erlang
(storage_0@127.0.0.1)3> R = leo_object_storage_transformer:list_to_cmeta_bin([
(storage_0@127.0.0.1)3> {cluster_id, hoge},
(storage_0@127.0.0.1)3> {num_of_replicas, 3},
(storage_0@127.0.0.1)3> {udm, crypto:rand_bytes(2048)}
(storage_0@127.0.0.1)3> ]).
<<131,108,0,0,0,4,104,2,100,0,10,99,108,117,115,116,101,
  114,95,105,100,100,0,4,104,111,103,101,104,...>>
(storage_0@127.0.0.1)4> byte_size(R).
2122
(storage_0@127.0.0.1)5>
```

so I'd like to choose 4096 for safe.

**Comment by mocchira** [comment]
@yosukehara 
as it turned out that os:timestamp/0 used in leo_date:clock/1 is NOT unix timestamp/microsecs ( around 10^3 times bigger than that ),
I'd adjust a bit.

**Comment by mocchira** [comment]
Skipping time get around 2x faster than the current by this fix.
