### ISSUE TITLE
[leo_gateway][s3][rest] the last part of a large object can be broken with reading_chunked_obj_len > chunked_obj_len in leo_gateway.conf

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#531]
here is the issue report.
https://groups.google.com/forum/#!topic/leoproject_leofs/UZtQHe2YjMU

## background
the default setting is 
```erlang
reading_chunked_obj_len % the size used with gen_tcp:recv ( reading from a network socket only used in s3|rest )
=
chunked_obj_len % the chunk size used for storing a part of large object
= 5242880
```
in leo_gateway.

As we have tested (also run in production) only with the default setting or ( reading_chunked_obj_len < chunked_obj_len in some narrow bandwidth envs ) for those values,
we couldn't find.

## cause
because we assumed the size of a bin passed to leo_large_object_put_handler:put function is <= chunked_obj_len.
https://github.com/leo-project/leo_gateway/blob/1.3.0/src/leo_large_object_put_handler.erl#L132-L178
as a result,
when leo_large_object_put_handler:result function called we may have a stacked binary which size > chunked_obj_len,
https://github.com/leo-project/leo_gateway/blob/1.3.0/src/leo_large_object_put_handler.erl#L203-L212
so that the last leo_gateway_rpc_handler:put will be called with a chunk size > chunked_obj_len.
this cause leo_object_storage generate invalid header fields(inconsistent dsize, cindex) and will be detected as a invalid block later compaction|diagnose and **LOST** in case of compaction.

## how to solve
- detect in cuttlefish https://github.com/leo-project/leo_gateway/blob/1.3.0/priv/leo_gateway.schema when **`reading_chunked_obj_len` > `chunked_obj_len`**.

or

- dividing a stacked binary into appropriate chunks and call leo_large_object_put_handler:put # of chunks times in leo_large_object_put_handler:result

## recovery for production users
we aggressively have to advertise **DON'T RUN COMPACTION** if you use leofs in production with  **reading_chunked_obj_len > chunked_obj_len** as it may cause **DATALOSS**.
although raw files has been alive if you don't run compaction, part of metadata has been broken as described above so that we need to provide a tool which recover files affected by this issue.

**Comment by yosukehara** [comment]
@mocchira Thanks for your report. This issue is very serious. So I've checked `reading_chunked_obj_len` which was added with [v0.16.8](https://github.com/leo-project/leo_gateway/commit/490399c270d900ad25b6e2975c3a46aa4a7119f6).

We need to announce this issue to LeoFS' users to avoid data loss.

**Comment by mocchira** [comment]
@yosukehara 
As this kind of issues ( may cause data-loss ) should be kept tracking strictly especially for storage products,
I'd suggest add a new label `data-loss`.

**Comment by pannon** [comment]
@mocchira @yosukehara maybe worth adding a best practices page to the docs and list this amongst other things like safe operational recommendations. You might have this already scattered trough the docs but having it at one place could make a difference.

**Comment by yosukehara** [comment]
@pannon Thank you for your suggestion. We're actually planning to improve LeoFS' documentation to be able to more easily understand LeoFS' administration, which will be started from this month.

**Comment by mocchira** [comment]
Candidates for the name of the doc describing safe operational recommendations.

- https://docs.mongodb.com/manual/administration/production-notes/
- http://docs.datastax.com/en/landing_page/doc/landing_page/recommendedSettingsLinux.html
- http://docs.openstack.org/developer/swift/#administrator-documentation
- http://docs.ceph.com/docs/master/rados/troubleshooting/
- http://docs.basho.com/riak/kv/2.2.0/using/repair-recovery/failure-recovery/
- https://www.cockroachlabs.com/docs/troubleshoot.html
- http://docs.couchdb.org/en/2.0.0/maintenance/index.html
- https://www.rabbitmq.com/production-checklist.html

IMHO, production xxx looks suitable as it make me feel they really take care of production users and have lots of production experiences.

For now, I'd go with production-checklist.
please let me know if you find more suitable one.

**Comment by yosukehara** [comment]
@mocchira I'm with you, "production-checklist"

**Comment by mocchira** [comment]
@yosukehara thanks.
please check https://github.com/leo-project/leofs_docs/commit/4167bdc83fbd544824b8dea13e87bdd90e2fd660 that make a new page "Production Checklist" also modify the page describing about "leo_gateway.conf" to call user's attention to check whether the constraint to prevent this issue is applied in their leo_gateway.conf.

**Comment by yosukehara** [comment]
@mocchira I've reviewed them. There is no issue, thanks.
