### ISSUE TITLE
leo_gateway timeout 30s for HTTP get

### ISSUE THREAD

**Issue by pannon** [leo-project/leofs#534]
We have a file roughly 25M in size stored. When the download takes longer than 30-35s the connection is terminated which results in a 500 code in the access log.

Is there some tunable for the gateway to raise this limit?

Have tried to raise `timeout.get` from 30s to 180s but getting the same result.

**Comment by mocchira** [comment]
@pannon timeout.get is used to control timeout between leo_gateway and leo_storage.

https://github.com/leo-project/leo_gateway/blob/1.3.0/priv/leo_gateway.conf#L83 

Setting http.sending_chunked_obj_len to less value (default: 5M) may solve your problem if timeout happened between leo_gateway and client.

**Comment by pannon** [comment]
I have put Nginx (rev. proxy) in front of the gateways and that solved the problem.
