### ISSUE TITLE
[leo_storage][log] Not found error logged as error on leo_storage

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#541]
@yosukehara @windkit 

AFAIK not found has not been logged before.
Is this a spec ?

now if I request a file that actually doesn't exist,
an error will appear in error.log
```erlang
[E]     storage_0@127.0.0.1     2016-12-14 06:14:59.887593 +0000        1481696099      leo_storage_handler_object:get/3        138     [{from,gateway},{method,get},{key,<<"test/README">>},{req_id,106261956},{cause,not_found}]
```

**Comment by windkit** [comment]
It is added when I make sure any errors happened when `leo_storage` handles requests from gateway/storage would emit an error logs.

Do we want to handle `{error, not_found}` separately?

**Comment by mocchira** [comment]
at least its error level is not error but warn as this error can happen under normal.
IMHO no error should be.
@yosukehara thoughts?

**Comment by windkit** [comment]
We may have to separate `{error, not_found}` then.

It can happen both under normal (no such file, really) and abnormal (failed replication) condition

so the warning logs is for "Something wrong, no big deal, it may be fine, please check back though"?

**Comment by yosukehara** [comment]
@mocchira Thanks for your comment. We need to handle `{error, not_found}` to not out put it on error-log as below:

```erlang
get(AddrId, Key, ReqId) ->
    BeginTime = leo_date:clock(),
    ?debug("get/3", [{from, gateway}, {method, get}, {key, Key}, {req_id, ReqId}]),
    Ret = get(#read_parameter{ref = make_ref(),
                              addr_id = AddrId,
                              key = Key,
                              req_id = ReqId}, []),
    case Ret of
        {ok, _, Bin} ->
            ?access_log_get(Key, byte_size(Bin), ReqId, BeginTime, ok);
        {error, not_found} ->
            ?access_log_get(Key, byte_size(Bin), ReqId, BeginTime, not_found);
        {error, Cause} ->
            ?access_log_get(Key, 0, ReqId, BeginTime, error),
            ?error("get/3", [{from, gateway}, {method, get},
                             {key, Key}, {req_id, ReqId}, {cause, Cause}])
    end,
    Ret.
```

**Comment by mocchira** [comment]
@yosukehara thank you.

@windkit 
> It can happen both under normal (no such file, really) and abnormal (failed replication) condition

I think failed replication cases should be caught on other execution paths like put/read_repair/replication and so on.

also it's important to know that 
adding logs into hot paths ( frequently executed code ) may cause considerable load against leofs ( imagine that one user have a leofs cluster that receive tremendous get requests and those almost doesn't exist. one day he upgrade leofs and what will happen to him is burst logging on leo_storage(s) and may cause disk full in worse case.
The specs of logging should be taken care with backward compatible manner.
