### ISSUE TITLE
Some Left-over regarding domain change

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#550]
## Description
Domain name for LeoFS once changed from `www.leofs.org` to `leo-project.net/leofs` and there are some unchanged link in shipped configuration file.

Especially in [leo_manager/priv/leo_manager_0.conf](https://github.com/leo-project/leo_manager/blob/develop/priv/leo_manager_0.conf)

## Search Result
https://github.com/leo-project/leo_manager/search?utf8=%E2%9C%93&q=%22leofs.org%22
https://github.com/leo-project/leo_storage/search?utf8=%E2%9C%93&q=%22leofs.org%22
https://github.com/leo-project/leo_gateway/search?utf8=%E2%9C%93&q=%22leofs.org%22
https://github.com/leo-project/leo_object_storage/search?utf8=%E2%9C%93&q=%22leofs.org%22

**Comment by yosukehara** [comment]
@windkit I've fixed them, thanks
