### ISSUE TITLE
[leo_object_storage] [leo_backend_db] LeoFS's LevelDB settings are hard-coded and conservative

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#555]
### Description
It seems compaction process in `leveldb` makes `leo_storage` unresponsive, probably caused the issue https://github.com/leo-project/leofs/issues/503

### Observation
`leo_backend_db_eleveldb` sets several parameters at `eleveldb:open`
(https://github.com/leo-project/leo_backend_db/blob/develop/src/leo_backend_db_eleveldb.erl#L58)
1. Write Buffer Size: 256KB ~ 3MB [random(?!)]
2. Max Open Files: 32
3. Cache Size: 64MB *(Such Option Not Found)*
4. Block Size: 10KB *(Deprecated, sst_block_size Instead)*

defaults for `basho/leveldb`
(https://github.com/basho/leveldb/blob/develop/util/options.cc#L28)
1. Write Buffer Size: 60MB
2. Max Open File: 1000
3. SST Block Size: 4KB

#### Testing
Load Image Set, (4.000,000 Files, ~32KB Average)

#### `leo_backend_db_eleveldb` defaults
![grafana_leofs](https://cloud.githubusercontent.com/assets/360884/21255104/2bf8f8ac-c3ad-11e6-8f4b-5180cf9f7ed2.png)

#### `eleveldb` (`leveldb`) defaults
![grafana_def](https://cloud.githubusercontent.com/assets/360884/21255103/2bf46fbc-c3ad-11e6-9ff5-9fba442d7639.png)

**Comment by windkit** [comment]
## Attempt to Fix, Pass Options with app configuration, Update defaults
https://github.com/leo-project/leo_backend_db/pull/6
https://github.com/leo-project/leo_storage/pull/21

## Result
1. Old LeoFS Defaults (32 Max Open Files, 3MB Write Buffer)
2. New Defaults (1000 Max Open Files, 60MB Write Buffer)
![eleveldb](https://cloud.githubusercontent.com/assets/360884/21410573/f97268e2-c824-11e6-955e-8e1b73bb27fd.png)

**Comment by yosukehara** [comment]
DONE
