### ISSUE TITLE
[1.3.1] [leo_gateway] Large Object Put Handler could halt infinitely

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#564]
## Description
When doing a large object put benchmark, `leo_gateway` would eventually stop responding. Every subsequent requests would get time out.

## Observation
```
~/s3cmd-1.6.1$ parallel -P 16 "./s3cmd put /dev/shm/testfile_0 s3://test/{} &>> log/put{}.log" ::: $(seq 1 256)
```
![large_object_halt](https://cloud.githubusercontent.com/assets/360884/21632930/519acc58-d28e-11e6-93af-0cdf6d28fe19.png)

**Interpretation**
1. High bumps come from s3cmd calculating md5sum of the ~1GB file
2. low bumps with 30-second interval comes from timeout

## Root Cause
`leo_pod:checkin` is not be executed when the `gen_server:call` failed after `leo_pod:checkout`.
The worker is not returned and the error is not handled for restart.

## Related PR
https://github.com/leo-project/leo_gateway/pull/60

**Comment by yosukehara** [comment]
Fixed this issue by leo-project/leo_gateway/pull/60
