### ISSUE TITLE
Small correction in the project info page?

### ISSUE THREAD

**Issue by hetzbh** [leo-project/leofs#565]
The project info states:

LeoFS can handle files with more than GB

Care to share how much more than GB? 1GB? 4GB?

**Comment by mocchira** [comment]
@hetzbh thank you for pointing that out.
We'd like to be explicit about the max size LeoFS can store as following.
In theory, the max size depends on the system configuration in leo_gateway https://github.com/leo-project/leo_gateway/blob/1.3.1/priv/leo_gateway.conf#L113-L117 .
5GB is the current default but you can raise the upper limit as much as you like by tweaking the above params. so yes it's unlimited.

**Comment by mocchira** [comment]
Close as the sentence no longer exists in the project info page.
