### ISSUE TITLE
Upgrading to 1.3.1 breaks bucket file listing (empty list)

### ISSUE THREAD

**Issue by pannon** [leo-project/leofs#566]
Upgraded two of our testing clusters, one from 1.3.0 to 1.3.1 and the other from 1.2.21 to 1.3.1 by following the procedure outlined here: http://leo-project.net/leofs/docs/admin_guide/admin_guide_10.html

In both cases after the upgrade none of the objects/files are visible using `s3cmd ls` anymore.
Only bucket names are listed but no content.

Retrieving previously known files with both `s3cmd` and `curl` works as expected.
Also `leofs-adm whereis <path/filename>` shows the files on the storage nodes.

Once a new file is uploaded it shows correctly. Only existing files are missing from the listing.

**Comment by yosukehara** [comment]
@pannon Thank you for your report. We'll check this issue soon, and need to recognize whether #558 affects `s3cmd ls` or not.

**Comment by yosukehara** [comment]
Fixed this issue by leo-project/leo_storage/pull/22 and leo-project/leo_gateway/pull/61
