### ISSUE TITLE
[config][all] re-consider the default setting policy

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#580]
The current system default tend to be set in respect to performance for historical reason.
but it might be time to re-consider the default policy taking into considerations more durability|security than performance.

**Comment by mocchira** [comment]
I checked the whole default settings in leo_(manager|storage|gateway).conf and I've come to the conclusion that only `object_storage.is_strict_check` https://github.com/leo-project/leofs/blob/1.3.2.1/apps/leo_storage/priv/leo_storage.conf#L58-L60 might need to be revised.

However while I'd respect the opinion at https://groups.google.com/forum/#!topic/leoproject_leofs/QsxY2wNWhYg suggested by Vladimir and also respect the current default for the existing users who have used LeoFS on the zfs native platforms and regard the zfs as the sufficient solution to provide the data integrity without is_strict_check on LeoFS.

So I'd like to take the middle between two.
- keep the default setting of `object_storage.is_strict_check` `false`
- Add the strong caution on the comment that
  - Without setting is_strict_check to true, there is a little possibility your data could be broken even if your LeoFS is running on a filesystem that protect both the metadata and the data blocks through the checksum like zfs when any unexpected|unknown software bug got avs files broken.

@yosukehara please check.
if no problem, I will add the above comment into leo_storage.conf.

**Comment by yosukehara** [comment]
@mocchira I've just read your opinion, there is no prob. Thanks.
