### ISSUE TITLE
[leo_storage][read_repair] may not satisfy the read consistency

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#589]
### Problem
The read consisntency(R) may not be satisfied when flowing the exec path through  https://github.com/leo-project/leo_storage/blob/1.3.1/src/leo_storage_read_repairer.erl#L89-L90 in case R >= 2 && failed to retrieve the data on erlang:node() for some reason because leo_storage_read_repairer:repair do not check the metadata if a redundancy node is erlang:node().

### How to reproduce (The behavior to be is different from the below.) 
The most easiest way to reproduce this issue is
- get cluster up with N=2, R=2 and set is_strict_check to true in leo_storage.conf
- put an object
- break the primary object somehow (ex. edit an avs manually and restart a storage node
- get the object
  - expected: 500
  - actual: 200

### Solution
Take another look at leo_storage_read_repairer:repair.

- Don't pass a redundancy that already succeeded on leo_storage_handler_object and start (ReadQuorum -1) at https://github.com/leo-project/leo_storage/blob/1.3.1/src/leo_storage_read_repairer.erl#L92 because we are sure that one attempt already succeeded here.
- Check the metadata on every node (currently no check happen on erlang:node()

[Edit]
  - Remove strikethroughed sentences to makes it concise.
  - Makes sentences that stated what the problem is more explicit

**Comment by yosukehara** [comment]
@mocchira We need to implement this situation in a LeoFS' CI test. We're going to consider that soon. Thanks.

**Comment by mocchira** [comment]
@yosukehara updated while leaving(Strikethroughed) the previous wrong comment for the record.
as stated the above, the problem is that **leo_storage_read_repairer:repair regard the operation on node() as success regardless of the result of the actual operation.**

**Comment by mocchira** [comment]
works as expected with https://github.com/leo-project/leofs/commit/88d41ae266e1bca4b8b5374e87e7a3cfb6e1bbc0 .
however we also have to fix #543 since metadata is valid but avs is broken in this case.

**Comment by yosukehara** [comment]
@mocchira I've reviewed https://github.com/leo-project/leofs/commit/88d41ae266e1bca4b8b5374e87e7a3cfb6e1bbc0 , and there is no issue. Thanks.

**Comment by yosukehara** [comment]
FIXED - https://gist.github.com/yosukehara/f62192c10cb6a43ae3a6f6a976d1ea3a

**Comment by yosukehara** [comment]
We've checked the read-quorum implementation of v1.3.2:
* [Performance evaluation of the read-quorum implementation of v1.3.2](https://github.com/leo-project/notes/blob/9c8beac81130a66e0170cdae6e86457ad3d38ea5/leofs/benchmark/leofs/1.3/1.3.2/front/20170130_image_f4m_read_ssd_10min_read_quo_1/README.md), which contains four test cases:
    * [R=1, Zero down node](https://github.com/leo-project/notes/blob/9c8beac81130a66e0170cdae6e86457ad3d38ea5/leofs/benchmark/leofs/1.3/1.3.2/front/20170130_image_f4m_read_ssd_10min_read_quo_1/README.md#read-quorum--1)
    * [R=1, One down node](https://github.com/leo-project/notes/blob/9c8beac81130a66e0170cdae6e86457ad3d38ea5/leofs/benchmark/leofs/1.3/1.3.2/front/20170130_image_f4m_read_ssd_10min_read_quo_1/README.md#read-quorum--1-1-node-failure)
    * [R=2, Zero down node](https://github.com/leo-project/notes/blob/9c8beac81130a66e0170cdae6e86457ad3d38ea5/leofs/benchmark/leofs/1.3/1.3.2/front/20170130_image_f4m_read_ssd_10min_read_quo_1/README.md#read-quorum--2)
    * [R=2, One down node](https://github.com/leo-project/notes/blob/9c8beac81130a66e0170cdae6e86457ad3d38ea5/leofs/benchmark/leofs/1.3/1.3.2/front/20170130_image_f4m_read_ssd_10min_read_quo_1/README.md#read-quorum--2-1-node-failure)

After benchmarking that, we've recognized there is no issue.
