### ISSUE TITLE
[leo_object_storage][test] API to break a data block in AVS

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#590]
In order to test such as #589. (like add_incorrect_data/1 for compaction tests)

```erlang
-module(leo_object_storage_api).

-ifdef(TEST).
-spec(overwrite_data(Offset, Bin) -> ok | {error, any()} when Offset::pos_integer(), 
                                                              Bin::binary()).
-endif.
```

**Comment by mocchira** [comment]
WIP

**Comment by yosukehara** [comment]
I've confirmed this issue was resolved:

- leo_object_storage_api
    - [leo_object_storage_api.erl#L389-L396](https://github.com/leo-project/leo_object_storage/blob/1.3.1/src/leo_object_storage_api.erl#L389-L396)
    - [leo_object_storage_api.erl#L389-L396](https://github.com/leo-project/leo_object_storage/blob/1.3.1/src/leo_object_storage_api.erl#L389-L396)
- leo_object_storage_server
    - [leo_object_storage_server.erl#L316-L317](https://github.com/leo-project/leo_object_storage/blob/1.3.1/src/leo_object_storage_server.erl#L316-L317)
    - [leo_object_storage_server.erl#L316-L317](https://github.com/leo-project/leo_object_storage/blob/1.3.1/src/leo_object_storage_server.erl#L316-L317)
- leo_object_storage_haystack
    - [leo_object_storage_haystack.erl#L53](https://github.com/leo-project/leo_object_storage/blob/1.3.1/src/leo_object_storage_haystack.erl#L53)
    - [leo_object_storage_haystack.erl#L372-L383](https://github.com/leo-project/leo_object_storage/blob/1.3.1/src/leo_object_storage_haystack.erl#L372-L383)
