### ISSUE TITLE
[leo_storage] [data-compaction] Reserve Disk Space for Compaction

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#591]
## Description
When disk is full, data compaction cannot proceed and therefore cannot reclaim the disk space.

We have to find a way to reserve disk space.

## Proposals
1. Create a dummy AVS with the size of largest AVS
    - Need to update the AVS size from time to time
2. Block Writes when Disk Space is Low
    - Part of the purpose of Disk Watchdog but disk space could be used by other processes
3. Limit the total Capacity of one `leo_storage` node
4. (Workaround) Add a temporary point to store WIP AVS
5. (New) Fixed Size AVS
    - Keep 1 extra AVS for disk space

**Comment by windkit** [comment]
## Related Issues
[Check before Compaction] https://github.com/leo-project/leofs/issues/465
[Operation Manual] https://github.com/leo-project/leofs/issues/464

**Comment by yosukehara** [comment]
We already delivered `auto-compaction feature`, and recommend using this feature but in case of its disabled, LeoFS' storage node crashes when disk-full situation happen.

I strongly recommend a LeoFS' storage node reject write-operation before its node reached `not able to compaction situation` as below:

![data-compaction](https://cloud.githubusercontent.com/assets/148770/22361052/46d22d30-e499-11e6-81c2-4f66a7cb2645.png)

**Comment by yosukehara** [comment]
We're able to support expanding disk issue for data-compaction by a method of leo-project/leofs/issues/592
