### ISSUE TITLE
[leo_storage][data-compaction] Avoids write operation before leo_storage is not able to execute data-compaction

### ISSUE THREAD

**Issue by yosukehara** [leo-project/leofs#592]
We already delivered auto-compaction feature, and recommend using this feature but in case of its disabled, LeoFS' storage node crashes when **disk-full situation** happen.

We need to support a LeoFS' storage node reject write-operation before its node reached not able to compaction situation as below:

![data-compaction](https://cloud.githubusercontent.com/assets/148770/22371983/c1d2ef44-e4dd-11e6-8877-8e0598818248.png)

After stoping WRITE operation, an admin needs to maintain a stoped leo_storage:
- Administration Options:
    - Expands disk space
    - Moves data-files to somewhere, needs to reconfigure [obj_containers.path](https://github.com/leo-project/leofs/blob/master/apps/leo_storage/priv/leo_storage.conf#L45)

- Related issue
    - [Check before Compaction] https://github.com/leo-project/leofs/issues/465
    - [Operation Manual] https://github.com/leo-project/leofs/issues/464

**Comment by yosukehara** [comment]
WIP

**Comment by mocchira** [comment]
WIP

**Comment by yosukehara** [comment]
@mocchira We've benchmarked v1.3.7-dev today. Its result is not good, [Benchmark LeoFS v1.3.7](https://github.com/leo-project/notes/blob/eaee349c863d68760e9f6b19703b3f2818c38a53/leofs/benchmark/leofs/1.3/1.3.7/front/20170911_image_f4m_load_read_r95w5_r80w20_ssd_30min_1/README.md). We need to reconsider this implementation. So I would like to propose this implementation as below:

### Proposal

* One monitor process, `leo_object_storage_diskspace_mon (tentative name)` checks disk-space every one minute which is configurable 
* In case of over the threshold, `leo_object_storage_diskspace_mon` set a flag of **is_able_to_write** to `leo_object_storage_server's 'State'`
* `leo_object_storage_server's put and store` always checks **is_able_to_write** to reject storing an object.

**Comment by yosukehara** [comment]
WIP

**Comment by mocchira** [comment]
@yosukehara Confirmed. It seems disksup gen_server process might be bottleneck as multiple leo_object_storage_server (default: 8) call that gen_server each time and also each call cause callers to be locked exclusively (waiting for other calls to finish). so your proposal loos reasonable.

**Comment by yosukehara** [comment]
@mocchira 

> Confirmed. It seems `disksup` gen_server process might be the bottleneck as multiple leo_object_storage_server (default: 8) call that gen_server each time and also each call cause callers to be locked exclusively (waiting for other calls to finish). so your proposal looks reasonable.

Thanks for your confirmation. I'm going to send a PR soon.

**Comment by yosukehara** [comment]
We've recognized this issue was fixed:

* [Benchmark LeoFS v1.3.7](https://github.com/leo-project/notes/blob/e6ca1e350e27a2f4fcd510ba1bce49cea75349ea/leofs/benchmark/leofs/1.3/1.3.7/front/20170912_image_f4m_load_read_r95w5_ssd_30min_1/README.md)
