### ISSUE TITLE
[leo_gateway][nfs] Makes the response to fsinfo configurable

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#598]
In order to pull the maximum performance on as many platforms as possible.
Now fields included in the response to fsinfo are hardcoded like the following.
https://github.com/leo-project/leofs/blob/1.3.2/apps/leo_gateway/src/leo_nfs_proto3_server.erl#L404-L414

**Comment by mocchira** [comment]
WIP

**Comment by yosukehara** [comment]
FIXED
