### ISSUE TITLE
[nfs][test] Integration Test for NFS in CI

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#600]
Sorry if getting this already done.
IIRC the our CI pipeline don't do https://github.com/leo-project/leofs/blob/1.3.2/apps/leo_gateway/test/leo_nfs_integration_tests.sh 
if so, we have to do.

**Comment by windkit** [comment]
Added with
https://github.com/leo-project/leofs_concourse/commit/144c6975816897f28a7dfd5b4abb8cc874b63ad4

**Comment by mocchira** [comment]
GJ!
