### ISSUE TITLE
[leo_manager][leo_storage] how to recover from a queue being lost

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#618]
### Discussion
https://groups.google.com/d/msg/leoproject_leofs/QsxY2wNWhYg/Y83jzgMJBQAJ

### Preconditions
- losing queues on a single storage 
- some objects stored at only this node (It can happen in case running a cluster with consistency.W < 2) 
- try to recover those objects across the cluster 

### What admin have to do 
- ASIS
  - do "recover-node" on every node in the cluster.
    - needs much operations
    - ineffective in all respects
    - unrealistic if the number of nodes in the cluster is very large
- TOBE
  - do "recover-xxx" on only the target node that enumerate all objects stored at this node and try to sync with others.

**Comment by yosukehara** [comment]
Fixed  this with PR#1042
