### ISSUE TITLE
[leo_mq][leo_storage] a message in a queue can get lost

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#624]
This can happen like this.

### ASIS
- dequeue
- process something based on a message dequeued <=== the message can get lost if the erlang process stop here for some reason (killed by OOM killer
  - enqueue if some error happened and need to retry
  - do nothing if no error happened

### TOBE
- peek (just reference the first item and don't remove it
- process something based on a message peeked
  - dequeue if no error happened

### Remark
As all operations conducted through queues are idempotent,
harmless even if an operation is executed multiple times so that the procedure suggested at TOBE section would be reliable, efficient and dead simple solution to me.

**Comment by yosukehara** [comment]
Fixed this issue with https://github.com/leo-project/leo_mq/pull/4
