### ISSUE TITLE
[NFS] Recursive Delete may Fail as Operations are Asynchronus

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#629]
## Description
Shipped NFS Integration Test Script may fail as a result
https://github.com/leo-project/leofs/blob/master/apps/leo_gateway/test/leo_nfs_integration_tests.sh

Same issue happens to other operations as well, such as `rmdir` after `rm` all the files under the directory, those could be fixed with `sleep` in between. But commands like `rm -rf` having recursive nature could not be easily fixed

**Comment by mocchira** [comment]
@windkit 
If you run the test with N>=2 && (W|D) < N then it's supposed to fail due the eventual consistency.
This test suite is supposed to run with N=1 or N=W=D so if this issue can happen under such conditions,
something should be fixed, if not please close.

**Comment by windkit** [comment]
@mocchira Oh I misunderstood the testing script, thanks for pointing out it. I will close this issue.
