### ISSUE TITLE
[leofs_client_test] s3cmd: add tests covering #483 cases

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#634]
confirm `sync --delete` works as expected on https://github.com/leo-project/leofs/issues/483

**Comment by windkit** [comment]
Added via https://github.com/leo-project/leofs_client_tests/commit/c5832b6fd5249dfefbd3dc83391dae3288675ce6

**Comment by mocchira** [comment]
LGTM. Confirmed with s3cmd <= 1.5.2.
