### ISSUE TITLE
[s3cmd][test] don't work with 1.6.x

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#639]
Works with <= 1.5.2 but don't with 1.6.x because s3cmd has started using Get Object ACL API that is not supported yet on LeoFS.

### Goal
Pass the leofs_client_tests/s3cmd/s3cmd.sh with 1.6.2 (the current stable

### Related issues.
- #490

**Comment by windkit** [comment]
Updated the sync test with identical files with https://github.com/leo-project/leofs_client_tests/commit/943a62009aa6b7f949a2aa278b8163fa348af194

PR https://github.com/leo-project/leofs/pull/646 should fix the problem with new version

**Comment by mocchira** [comment]
LGTM. thanks for your contribution.
