### ISSUE TITLE
[leo_s3_libs] failed to fetch a bucket info while both managers are down after bucket_prop_sync_interval passed

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#642]
This cause the operations(GET|PUT|DELETE) to fail via S3 as reported on https://groups.google.com/forum/#!topic/leoproject_leofs/v_BAJT58Foo .

This should never happen even if the bucket information got obsolete, instead keep handling operations by using obsolete ones on local and also try to keep the latency consistent (don't get into blocking due to waiting for RPC timeout).

**Comment by yosukehara** [comment]
Fixed
