### ISSUE TITLE
[mdc][leo_storage] read-repair, data-compaction, data-recovery feature may replicate objects more than "mdc_replication.num_of_replicas_a_dc"

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#645]
Because read_repair don't take care whether an object was replicated via MDC replication or via local replication.

For example, 
say
```ini
mdc_replication.num_of_replicas_a_dc = 1 ### on the source cluster
consistency.num_of_replicas = 2 ### on the destination one
```
When a MDC replication happened, one replica is created on the destination.
Subsequently when a GET request to the replicated object on the destination happened, that cause read_repair and in turn one more replica is created (Now the destination have 2 replicas for the object).

**Comment by yosukehara** [comment]
WIP. I've recognized that `data-compaction`, `data-recovery` are also affected.

**Comment by mocchira** [comment]
@yosukehara 

Sorry for closing the issue unintentionally.
It seems now github automatically close the issue if the commit message includes **Fix ${Organization}/${Project}#${IssueNumber}** (yes actually there are much more cases). 
AFAIK this auto issue closer worked only when **Fix xxx** part appeared in the head of a message, however now it seems to work regardless of its position.

We need to take care not to use such commit messages to avoid unintentional closes.

**Comment by yosukehara** [comment]
@mocchira 

> It seems now GitHub automatically close the issue if the commit message includes Fix ${Organization}/${Project}#${IssueNumber} (yes actually there are much more cases).
> AFAIK this auto issue closer worked only when Fix xxx part appeared in the head of a message, however now it seems to work regardless of its position.

I see.
