### ISSUE TITLE
[leo_s3_libs] make find_bucket_by_name fail-safe as #642

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#647]
in order to keep GET Object ACL working while both managers are down.
Found through the review https://github.com/leo-project/leofs/pull/646
Reference: #642 .

**Comment by windkit** [comment]
PR https://github.com/leo-project/leo_s3_libs/pull/10/files

**Comment by mocchira** [comment]
LGTM. Thanks for your contribution.
