### ISSUE TITLE
1.3.2 cluster 

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#652]
Hello, i now encounter leofs-adm status view cluster state no response

error log 
[E]	manager_0@10.39.1.24	2017-03-24 13:32:32.542278 +0800	1490333552	null:null	0	Supervisor leo_manager_sup had child undefined started with leo_manager_ring_sync:start_link() at <0.19854.6> exit with reason {timeout,{gen_server,call,[leo_redundant_manager_worker,checksum,30000]}} in context child_terminated

**Comment by windkit** [comment]
Can you provide some background information about your setup?
e.g. LeoFS version, OS, and etc.

And can you try to point the `leofs-adm` to secondary manager by editing the two lines
```
: ${LEOFS_ADM_HOST=127.0.0.1}
: ${LEOFS_ADM_PORT=10010}
```

**Comment by xingxing9688** [comment]
你好，我安装的是1.3.2 的版本，系统为ubuntu 14.04 采用deb 包安装 ，使用5台机器单独部署，每一台机器一个服务，leofs-admin 的集群是怎么关闭的，leofs-admin   start  之后没有stop
