### ISSUE TITLE
performance tools ?

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#656]
Leofs s3 protocol performance test using those tools?

**Comment by windkit** [comment]
LeoFS Benchmark Reports are published at https://github.com/leo-project/notes/tree/master/leofs/benchmark/leofs/1.3/1.3.2
And we are using Basho Bench for the benchmarks https://github.com/leo-project/basho_bench

**Comment by xingxing9688** [comment]
Thank you, is this a detailed document?

**Comment by xingxing9688** [comment]
There are other professional testing tools, basho_bench this tool can not download, the server needs to over the wall.

**Comment by xingxing9688** [comment]
Benchmark in ubuntu 14.0.4 how to install?

**Comment by windkit** [comment]
You can refer to the doc here
http://docs.basho.com/riak/kv/2.2.1/using/performance/benchmarking/

**Comment by windkit** [comment]
## To Prepare Basho Bench Environment
```bash
## Build Tools
sudo apt-get install git build-essential

## Erlang
wget https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_17.5.3-1~ubuntu~trusty_amd64.deb -O esl-erlang.deb
sudo dpkg -i esl-erlang.deb

## Fix Dependencies
sudo apt-get install -f

## Get LeoFS Basho Bench
git clone https://github.com/leo-project/basho_bench.git

cd basho_bench;
make
```

**Comment by xingxing9688** [comment]
Thanks !
