### ISSUE TITLE
[leo_object_storage][compaction] Choose the target based on the active ratio

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#658]
As it's obviously ineffective to do compaction for a AVS which active ratio is very high,
it would be great to run compaction in ascending order of the active ratio by default.

**Comment by yosukehara** [comment]
@mocchira This issue is almost same with leo-project/leofs/issues/460

**Comment by mocchira** [comment]
@yosukehara Yep totally missed it.
Close as duplicated.

**Comment by yosukehara** [comment]
@mocchira Thanks for your confirmation.
