### ISSUE TITLE
Performance test error

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#663]
10:12:36.396 [warning] No data for op: {put,put}
10:12:36.397 [info] Errors:[{{put,put},36336},{{{put,put},{http_error,"500"}},36336}]
10:12:46.397 [warning] No data for op: {put,put}
10:12:46.398 [info] Errors:[{{put,put},35322},{{{put,put},{http_error,"500"}},35322}]
10:12:56.398 [warning] No data for op: {put,put}
10:12:56.399 [info] Errors:[{{put,put},38944},{{{put,put},{http_error,"500"}},38944}]
10:13:06.397 [warning] No data for op: {put,put}
10:13:06.398 [info] Errors:[{{put,put},38080},{{{put,put},{http_error,"500"}},38080}]
10:13:16.397 [warning] No data for op: {put,put}
10:13:16.398 [info] Errors:[{{put,put},37233},{{{put,put},{http_error,"500"}},37233}]
10:13:26.400 [warning] No data for op: {put,put}
10:13:26.400 [info] Errors:[{{put,put},35132},{{{put,put},{http_error,"500"}},35132}]

Performance test process will occasionally appear, 3 million small file pressure measurement

reference：
https://github.com/leo-project/notes/blob/master/leofs/benchmark/leofs/1.3/1.3.2/front/20170118_image_f4m_load_read_r95w5_ssd_30min_1/load/image_f4m_load.conf

**Comment by yosukehara** [comment]
@xingxing9688 Can you share error logs of `leo_gateway` and `leo_storage`? We'd like to recognize this situation in detail.

**Comment by xingxing9688** [comment]
What log do you need, can you tell me?
