### ISSUE TITLE
question about consistency of leofs storage (Auto-recovery of storage nodes)

### ISSUE THREAD

**Issue by Argentum88** [leo-project/leofs#666]
Quotation from LeoFS storage architecture

> On the other hand, in case of a read operation, LeoFS Gateway requests a LeoFS Storage node. Then the LeoFS Storage node retrieves an object from the local object-storage or the remote LeoFS Storage node. Finaly, the LeoFS Storage node respond an object to the gateway. Also, the LeoFS Storage node checks consistency of the object with the asynchronous processing.
If the LeoFS Storage node finds inconsistency of an object, it will be recovered with the backend process. The object eventually keep consistensy with their functions.

Let's imagine the scenario

State of system on start our scenario:
 - Our have two storage nodes
 - These storage node, store a number of objects (replication factor 2)
 - Storage nodes in a consistent state

Scenario
1) One of the storage nodes is temporarily unavailable
2) We put a number of new objects
3) Unavailable storage node became available

QUESTION
If the new objects will never be get back, then for these new objects will not be satisfied replication factor 2, right?

If so, will auto-recovery of storage node in the future???

**Comment by yosukehara** [comment]
LeoFS adopts [eventual consistency](https://en.wikipedia.org/wiki/Eventual_consistency) of the consistency model, whose model takes priority over AP(Availability and Partition tolerance) over C(consistency) which depends on [CAP theorem](https://en.wikipedia.org/wiki/CAP_theorem).

As the above, LeoFS delivers the automated recover feature to automatically fix consistency of an object, and you can set [the consistency level](https://github.com/leo-project/leofs/blob/master/docs/admin/settings/cluster.md#data-availability-of-consistency-level) of your LeoFS system to configure your needs of it.

**Comment by Argentum88** [comment]
Thank you for the explanation
