### ISSUE TITLE
[leo_storage][leo_backend_db] leo_storage can be rebooted when lots of badarg from eleveldb happened

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#668]
Reported on https://github.com/leo-project/leofs/issues/644#issuecomment-290717176.

Now I think the following thing can happen in eleveldb.

- During Comaction (NOT LeoFS BUT Leveldb)
Any Operation (PUT/GET/DELETE/FETCH) to leo_backend_db backed by eleveldb can block due to 
  - An OS thread managed by eleveldb being blocked until the compaction finished
  - The corresponding OS thread managed by Erlang Runtime being blocked until the OS thread managed by eleveldb responded to the request (PUT/GET/DELETE/FETCH) 
  - There are multiple leveldb instances on the same node in which the number of its instances is same with the number of AVS files (default: 8) so that **leo_storage with the number of cpu cores <= 8** can get stuck under high load during compaction happened at leveldb
  - Cause Erlang Runtime no to respond heartbeat for a long time and as a result heart triggers the restart for leo_storage

As we have test/benchmark(ed) LeoFS on relatively high spec machines (IIRC, the number of cores is 24/32),
there is little chance to see the restart happened in such reason. 

Now I'm working to confirm whether the above assumption is correct or not.

**Comment by mocchira** [comment]
Tests in my dev box and the vet around leveldb which details are described at https://github.com/leo-project/leofs/issues/503 show that my assumption seems to be correct.

So the root problem can be defined as
### Problems
- How to mitigate the disk I/O caused by leveldb
- Prevent the whole Erlang Runtime from getting stuck due to the above reason

### Solutions
The former one can be partly solved by

- Optimizing compaction activities through eleveldb options
  - https://github.com/basho/eleveldb/blob/2.0.34/priv/eleveldb.schema#L186-L202  
- Optimizing other I/O activities through eleveldb options (should be covered at #503)
  - https://github.com/basho/eleveldb/blob/2.0.34/priv/eleveldb.schema

according to I/O pattern.

The latter one can be solved by

- Checking WIP compaction activities by leveldb.stats BEFORE calling any operation (GET/PUT/DELETE/FETCH) to eleveldb
  - https://github.com/leo-project/leofs/issues/503#issuecomment-265652522
- Return an error like `{error, wip_compaction}` if there is WIP compaction activities so that we can prevent any operation (GET/PUT/DELETE/FETCH) from being called to eleveldb
- Return 503 on leo_gateway in the end

@yosukehara @windkit IMHO, at least the latter one should be fixed to avoid leo_storage being restarted by heart reported at #644. Thoughts?

**Comment by mocchira** [comment]
As for the solution,
Implementing leo_watchdog for leveldb could be another choice.
In either way,
As we've gotten to be able to retrieve compaction related info by https://github.com/leo-project/leofs/issues/671, we can implement a new safe guard based on that info.

**Comment by yosukehara** [comment]
> As for the solution,
> Implementing leo_watchdog for leveldb could be another choice.
> In either way,
> As we've gotten to be able to retrieve compaction related info by https://github.com/leo-project/leofs/issues/671, we can implement a new safe guard based on that info. 

@mocchira I agree with you idea.

**Comment by mocchira** [comment]
We've come to conclusion how to solve the root cause with two solutions.
I filed each ones as followings.
- [ ] Conservative watchdog setting - https://github.com/leo-project/leofs/issues/693
- [ ] Extend the watchdog monitoring error logs -  https://github.com/leo-project/leofs/issues/694

**Comment by windkit** [comment]
During my testing, after a `leo_object_storage` got restarted. The corresponding metadata process then kept failing with `badarg`.
Once I killed the corresponding metadata process with `kill(whereis(leo_metadata_2), kill)`
Supervisor would restart it and afterwards operation is back to normal.

It seems that some internal data structure in eleveldb went wrong during the time.

**Comment by windkit** [comment]
`badarg` can easily reproduce by setting the timeout of
https://github.com/leo-project/leo_object_storage/blob/develop/src/leo_object_storage_event_notifier.erl#L88
```
    gen_server:call(?MODULE, {notify, Msg, Method, Key, ProcessingTime}, ?TIMEOUT).
``` 
And trigger the event notify.

**Comment by windkit** [comment]
I am checking the issue in two aspects
1. Why the gen_server would timeout (probably because all the threads are in eleveldb nif, i will try to test it by limiting the number of scheduler)
2. Why restarting leo_object_storage_ alone is not enough, and what's wrong with the leo_metadata_

To me, the simplest fix is to let the metadata process die and restart upon errors like this.

**Comment by mocchira** [comment]
@windkit thanks for vetting this one.

From what I've already observed on my dev box,

> Why the gen_server would timeout (probably because all the threads are in eleveldb nif, i will try to test it by limiting the number of scheduler)

As I mentioned on the issue description, 
- eleveldb has its own thread pool (isolated from erlang scheduler's one) and every operation can get stuck within threads in leveldb's when the operation take too long (especially during compaction)
- Since leo_object_storage get stuck while waiting the response from eleveldb, timeout will happen.

> Why restarting leo_object_storage_ alone is not enough, and what's wrong with the leo_metadata_

That's the point. For now I also have no idea why so I will vet later.

> To me, the simplest fix is to let the metadata process die and restart upon errors like this.

Let's discuss after it turns out why restaring is not enough.

**Comment by mocchira** [comment]
@yosukehara @windkit 

Found the guilty one.
https://github.com/leo-project/leo_object_storage/blob/1.3.1/src/leo_object_storage_server.erl#L920
Because leo_backend_db_server:close can be called through gen_server:terminate callback in case of not only normal shutdown but also abnormal shutdown. 
(Given that looking into the current code, we assumed it's called only in case of normal shutdown..)

Instead we have to call leo_backend_db_server:close only if terminate called with the reason **normal**.

Reference: http://erlang.org/doc/man/gen_server.html#Module:terminate-2

**Comment by mocchira** [comment]
Just in case,
https://github.com/leo-project/leo_object_storage/blob/1.3.1/src/leo_object_storage_server.erl#L551-L560
Now the above block is executed in case of normal shutdown caused by `bin/leo_storage stop` so I will change to call leo_backend_db_server:close only in this path.

Note about the sequence of shutdown on leo_storage
- leo_storage stop
- init:stop
- leo_storage_app:prep_stop
- leo_object_storage_sup:stop
- leo_object_storage_server:close
- leo_object_storage_server:handle_call with close

**Comment by yosukehara** [comment]
Fixed
