### ISSUE TITLE
[leo_backend_db] Implement status callback for eleveldb

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#671]
In order to make it easy to debug/monitor I/O activity inside leveldb in detail like the following case.
- #503 
- #644 

Providing (Disk Throughput/The number of files) per LSM level using https://github.com/basho/leveldb/blob/2.0.33/db/db_impl.cc#L2113-L2135

If the above information is not enough then also considering to provide whether there is any scheduled compaction using https://github.com/basho/leveldb/blob/2.0.33/db/db_impl.cc#L2404-L2412
We have to add a new I/F in eleveldb in this case (and maybe have to maintain our home grown eleveldb).

Reference: https://github.com/leo-project/leofs/issues/503#issuecomment-265652522

**Comment by mocchira** [comment]
@yosukehara 
I noticed that leo_backend_db_server:status has been used for providing the number of entries stored in a leo_backend_db at https://github.com/leo-project/leo_mq/blob/1.4.13/src/leo_mq_api.erl#L160-L167.
As changing the behavior of leo_backend_db_server:status also requires the changes of leo_mq_api:status,
I think it would be good to implement this feature as another callback function like `compaction_status` rather than changing the current `status` semantics. Thoughts?

**Comment by yosukehara** [comment]
> I think it would be good to implement this feature as another callback function like compaction_status  rather than changing the current status semantics. Thoughts?

@mocchira I agree with your opinion. Let's implement its function.

**Comment by mocchira** [comment]
@yosukehara thanks. will do with compaction_status.

**Comment by yosukehara** [comment]
Fixed
