### ISSUE TITLE
Listing objects by prefix with s3cmd

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#706]
I know that right now listing buckets with lots of objects is not supposed to work nice (and there are tickets like https://github.com/leo-project/leofs/issues/548); this question is about slightly different matter.

I am surprised that listing objects by prefix with S3 API works much better than expected for some cases and interested in details - whether there is some design decision affecting that or some bug.
For LeoFS 1.3.3 and s3cmd 1.6.1, I can do this:
```
$ /usr/bin/time s3cmd ls s3://body/ | wc -l
1.82user 0.06system 0:03.81elapsed 49%CPU (0avgtext+0avgdata 53824maxresident)k
0inputs+0outputs (0major+25923minor)pagefaults 0swaps
3073
```
it takes almost 4 seconds to list lots of object (I did it a few times, it was even longer when the cache was cold). This is accompanied by high CPU usage on local system and on gateway. Expected, I suppose.
I'm surprised about this:
```
$ /usr/bin/time s3cmd ls s3://body/test | wc -l
0.08user 0.01system 0:00.11elapsed 92%CPU (0avgtext+0avgdata 19600maxresident)k
0inputs+0outputs (0major+6746minor)pagefaults 0swaps
2
```
It takes fraction of second to list "subdirectory". But these subdirectories aren't real; it's just some case of prefix search which works properly, right?

What I'm interested in that why I can't do listing by prefix other than subdirectory:
```
$ s3cmd ls s3://body/ff
WARNING: Retrying failed request: /?prefix=ff&delimiter=/
WARNING: 503 (ServiceUnavailable): Please reduce your request rate.
WARNING: Waiting 3 sec...
^CSee ya!
```
The error is instant and accompanied by
```
[E]	storage_0@192.168.3.53	2017-04-13 18:59:21.960042 +0300	1492099161	leo_backend_db_eleveldb:prefix_search/3	210	badarg
```
message on storage nodes.

I expected to see some of these objects:
```
$ /usr/bin/time s3cmd ls s3://body/ | grep body/ff
2017-04-13 13:33     19064   s3://body/ff3cb8e2c21db10cc19f88eb746d8eb2443208e692d9055ba4390b52565ba1c7e414ed5963b87d4aa223ac7049a4eeacd073000000000000.xz
2017-04-13 13:33       948   s3://body/ff418438b3bdda14bb82b6a8deb5f1b9ebe875512c5cd392be75b2bf9c2ec34c7fcf6b8aacabbfa1ead838ede1533e359ccc000000000000.xz
2017-04-11 04:30   1638224   s3://body/ff459f7f9d969f3e3eaf91bb41a77236bad89268d5bee5ffa9ecf0ae3f291fcb7b28b7947ced0299ed91cc03cfa7070800905d0000000000.xz
...
```

I'd like to know if this functionality is expected, but there is bug that breaks it, or that '/' separator is a special one and prefix search is supported by that separator. I understand that limiting prefix search options might be required for performance / index size reasons, but understanding whether '/' is special or not might affect how it's best to store data for our systems (e.g. using `body/ff/45/9f/ff459f7f9d969f3e3eaf91bb41a77236bad89268d5bee5ffa9ecf0ae3f291fcb7b28b7947ced0299ed91cc03cfa7070800905d0000000000.xz` for this case and get ability to do prefix search)

**Comment by windkit** [comment]
Without the sub directory, LeoFS essentially perform a full scan, that's why it is slow.

We have a general issue about prefix and delimiter at https://github.com/leo-project/leofs/issues/431
In other words, LeoFS now only support prefixes which are sub directory with delimiter is '/'

**Comment by mocchira** [comment]
@vstax 

Just in case, to supplement

> but understanding whether '/' is special or not might affect how it's best to store data for our systems (e.g. using body/ff/45/9f/ff459f7f9d969f3e3eaf91bb41a77236bad89268d5bee5ffa9ecf0ae3f291fcb7b28b7947ced0299ed91cc03cfa7070800905d0000000000.xz for this case and get ability to do prefix search)

As @windkit explained the above,
Your example will be prefix searched with s3://body/ff or s3://body/ff/45 and so on.

One thing you might be interested in is
As you narrow the directory down, the latency gets lower.
(s3://body/ff/45 is probably lower than s3://body/ff)

I hope you would find it helpful to design how to store your data into LeoFS :)

**Comment by vstax** [comment]
@windkit @mocchira 
Thanks for explanation. Yes, it's useful to know that '/' is indeed a special separator in regards to `ls` command. I was under impression that since storage itself is flat, these fake "subdirectories" don't matter, now I understand that they allow to do fast prefix search, this can be helpful.
