### ISSUE TITLE
Gateway cache can violate consistency in some cases?

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#708]
Based on explanation in https://github.com/leo-project/leofs/issues/702#issuecomment-294262790 I created a hypothetical scenario where current implementation of cache can cause consistency problems. I'd like to ask - before performing experiments, which are a bit complicated - if I'm thinking in the right direction, or am wrong somewhere and such problem is impossible?

Settings are N=3, W=2, D=2, R=2; high level of consistency is expected (but setting W=3 would be too troublesome since one can't even upgrade storage nodes without interrupting the system).

The object OBJ should go to nodes S0, S1 and S2, with S0 being primary. There might be different versions of that object, let's call them OBJ1 and OBJ2 - same name, different contents. There are two gateways, G0 and G1 behind load balancer (LB).

Client 1 makes "PUT OBJ1" through LB->G0. Now S0 (primary), S1 and S2 all have OBJ1, plus OBJ1 is in cache of G0.

A network trouble happens, splitting G0 and S0 from the rest of the network. Not to worry! With W=2 and R=2, we expect system to be consistent even in case of splits - either write would fail, or the read would, but we shouldn't be able to get old version of object regardless.

Client 1 makes "PUT OBJ2" though LB->G1 (LB has detected that G0 is not available). Since G1 has no connection to S0, it puts object to S1 and S2. Now we have S0:OBJ1, S1:OBJ2, S2:OBJ2. OBJ2 is in cache of G1.

Client 1 messages Client 2 that actual version of object is stored, and can be retrieved.

Client 2 does "GET OBJ" through G0 (maybe it was on that side of the split. Or maybe connection to G0 got fixed, but there is still no connectivity between S1/S2 and S0 - S0 can only communicate with G0). G0 has OBJ1 in cache, it checks version against S0, which has OBJ1 as well, OBJ1 is returned to the Client 2.

There lies a problem; since W+R > N, strong consistency was expected, but we didn't get it because of the way cache works. Or maybe I oversimplified the process and some other check is performed, so this scenario won't happen?

**Comment by windkit** [comment]
The key here is, when R=2, does G0 only verify cache with S0 but not 2 out of 3 storage nodes.

Let me verify this first.

**Comment by windkit** [comment]
I have confirmed that cache verification does not follow the quorum.

https://github.com/leo-project/leofs/blob/master/apps/leo_storage/src/leo_storage_handler_object.erl#L1072

If the gateway contacted a storage node holding the old object, it would think it has the correct object in cache.
Worse still, this would not trigger the consistency fix as other nodes are not contacted through the process.

**Comment by yosukehara** [comment]
@vstax I've explained the cache feature as below:
The latest version of LeoGateway does not depend on the consistency level, and LeoGateway requests a storage node to ask for comparing a cached object's hash (leo_gateway) with its object's hash (leo_storage).

It is important that LeoGateway selects a requested LeoStorage's node from RING, distributed hash table by a target object/file name, then LeoGateway requests the first of the selected node list.

If the requested node's object from a LeoGateway node is inconsistency in the replicas, a client retrieves it which is inconsistent.

I'm considering the strong consistency cache feature on LeoGateway. It will be an optional feature with v1.4 or v1.5.

**Comment by vstax** [comment]
@yosukehara I see, thank you for explanation.

Given that cache is enabled by default, shouldn't a comment be added in documentation (http://leo-project.net/leofs/docs/configuration/configuration_1.html and http://leo-project.net/leofs/docs/configuration/configuration_3.html) and / or in config files (leo_gateway around "cache" options, leo_manager_0 around consistency options) for above explanation? Stating the fact that active cache reduces R to 1 for the objects that are currently in cache. So that people who need to depend on strong consistency can take a note of that and disable the cache (until strongly consistent cache feature is implemented).

**Comment by yosukehara** [comment]
@vstax I've contained the explanation of the cache consistency on the new documentation:
- https://github.com/leo-project/leofs/commit/698cf9f6ba2ecbd87f74dc6283da0b1de74d9b95

**Comment by mocchira** [comment]
@vstax 

Now we have noted this issue on http://leo-project.net/leofs/docs/admin/settings/leo_gateway/#cache-consistency-between-leogateway-and-leostorage.
Please close this issue if the above doc make senses to you.

**Comment by vstax** [comment]
Nice, thank you!
Please consider this documentation fix. I feel like this is important information that should be mentioned where handling of READs is described (since LeoGateway is the only way to make there READ requests).

**Comment by mocchira** [comment]
@vstax 

> I feel like this is important information that should be mentioned where handling of READs is described

Thanks for your suggestion.
Please let me clarify where **handling of READs is described** is. 
here? http://leo-project.net/leofs/docs/architecture/leo_gateway/
If so, that makes sense to me.

**Comment by vstax** [comment]
@mocchira It's fine, thanks to your comment I double-checked it and found that I've edited **the wrong part** - the one related to "Large object support". Of course this should go to "READ-Request Handling" section in "Fundamentals" instead.
