### ISSUE TITLE
[leo_logger] Tons of logs can get LeoFS overloaded

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#729]
Found through the discussions on #722.
In the worst case, as a result leo_storage can get restarted by heart.

### Solutions
- Use https://github.com/erlang-lager/lager instead of leo_logger
- Fix leo_logger to implement https://github.com/erlang-lager/lager#overload-protection as lager does

**Comment by yosukehara** [comment]
I've considering `error`, `warn`, and `info` logger which depend on `leo_logger` are replaced with `Lagger`, but other loggers keep using  `leo_logger`. After surveying  `Lagger`, we will decide whether to use `Lagger` or not.

**Comment by yosukehara** [comment]
I've recognized `erlang/lager` does not support the hourly log. We need to consider how to implement it to leo_logger using `erlang/lager`.

**Comment by windkit** [comment]
I think it is good to allow user switch backend between leo_logger / lager
but how to do it efficiently with the macros seems non-trial to me.

While we can use a gen_server to easily record the backend with state, I am not so sure if wrapping lager (gen_event) with gen_server is a good idea, particularly when we consider the overload case.

**Comment by mocchira** [comment]
@windkit 

> While we can use a gen_server to easily record the backend with state, I am not so sure if wrapping lager (gen_event) with gen_server is a good idea, particularly when we consider the overload case.

Yes it's not good idea wrapping by gen_server as using a **naked** gen_server around lager means we lose the overload protection lager has provided so we need another abstraction layer that allows us to implement leo_logger with lager without gen_server.

**Comment by mocchira** [comment]
@windkit 

At first, let's sort out how the current impl works.

1. Called a macro defined at https://github.com/leo-project/leo_logger/blob/develop/include/leo_logger.hrl
2. Called a function (debug|info|warn|error) defined at https://github.com/leo-project/leo_logger/blob/develop/src/leo_logger_client_message.erl
3. Called leo_logger_server (behavior(gen_server)) <-- we have to avoid the execution path to reach here.

Also given that we keep the existing code working without any modification,
We need to change the behavior of **leo_logger_client_message** somehow.

The ways to do it I just come up with are
- Recompile the module on the fly with the **code** module as https://github.com/eproxus/meck does.
- Use parse transform as lager does (kind of meta programming approach in Erlang) in https://github.com/erlang-lager/lager/blob/master/src/lager_transform.erl.

The latter way looks promising to me.

**Comment by mocchira** [comment]
Good entry points on parse transform in Erlang.
- http://www.erlang-factory.com/upload/presentations/521/yrashk_parse_transformations_sf12.pdf
- https://stackoverflow.com/questions/2416192/is-there-a-good-complete-tutorial-on-erlang-parse-transforms-available

**Comment by yosukehara** [comment]
I want to go back to the beginning and organize it to solve this problem correctly.

We need to think about ways to **solve this problem** and to **enable hourly log output**. We can think of the following two ways. 

- Fork `erlang/lager`, then implement a function of hourly log output
- Incorporate erlang/lager's some functions into leo_logger to fix the overload problem

We need to consider which one to adopt before getting started with the program design.

**Comment by mocchira** [comment]
@yosukehara Agreed that's what I originally intended.

### Pros/Cons

- Fork
  - Pros
    - benefit from other functionalities lager provides (not only overload protection but other safe guards)
    - performance boost thanks to lager_transform that gets rid of checking log level at caller sites
  - Cons
    - initial IMPL cost is a little higher than the port solution
    - have to keep maintaining our homegrown lager 
- Port the overload protection into leo_logger
  - Pros/Cons on the fork solution inverted

Given that the core functionalities provided by lager seems to be stable enough that means we could expect backports barely happen, IMHO +1 for the fork solution.

**Comment by mocchira** [comment]
Note:
Why we have to maintain the original one is 
- The feature hourly logging has been rejected on the upstream in the past
  - refer https://github.com/erlang-lager/lager/issues/272 for more detail

**Comment by mocchira** [comment]
### Where we have to modify the existing leo_logger for the fork solution
- Initialization
  - https://github.com/leo-project/leo_logger/blob/develop/src/leo_logger_client_message.erl#L59-L91
- Logging for each log level
  - https://github.com/leo-project/leo_logger/blob/develop/src/leo_logger_client_message.erl#L119-L151

Also have to understand **Sink** how lager manage multiple log instances to implement not only info/error logs but other non-rotated logs like the result of diagnose
- https://github.com/erlang-lager/lager#sinks

and how to configure a log instance at runtime
- https://github.com/erlang-lager/lager/blob/master/src/lager_app.erl#L180-L196

**Comment by windkit** [comment]
I would try to use `parse_transform` to switch logger backend.

By default, `leo_logger_api` is used, which passes the call to `leo_logger_client_base` or `leo_logger_client_message`
If `lager` backend is preferred, add the compile option `{parse_transform, lager_logger_transform}` to switch.

WIP Branch: https://github.com/windkit/leo_logger/tree/lager

TODO List:
- [ ]  parse_transform
- [ ]  access log
- [ ]  modify log rotation of lager

**Comment by yosukehara** [comment]
@windkit I've checked your suggestion. Go ahead.

**Comment by mocchira** [comment]
@windkit Confirmed WIP work. LGTM.

**Comment by windkit** [comment]
Forgot to also push the WIP branch for leofs
https://github.com/windkit/leofs/tree/lager

I have changed the code for `leo_gateway`.
Now I am working on `leo_storage` and `leo_manager`

**Comment by windkit** [comment]
`lager` log rotation TODO

- [ ] Log File Name Format (now is `name`+"."+`count`, make it configurable)
- [ ] Log Rotation Hourly (now is daily, weekly, monthly)

**Comment by windkit** [comment]
Log Rotation fixed, updated WIP Branches
https://github.com/windkit/leofs/tree/lager
https://github.com/windkit/leo_logger/tree/lager
https://github.com/windkit/lager/tree/for-leofs

I only tested on `leo_gateway`

Maybe it is good to push the modification lager to upstream as it only opens up possibility to use hourly rotation and custom log rotator.

Next TODO: access log

### Output ###
```
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.754680 +0900        1506153457      leo_gateway_app:start/3 677     sending chunk length: 5242880
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.754735 +0900        1506153457      leo_gateway_app:start/3 678     cache_method: inner
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.754797 +0900        1506153457      leo_gateway_app:start/3 679     cache workers: 16
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.754858 +0900        1506153457      leo_gateway_app:start/3 680     cache ram capacity: 268435456
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.754918 +0900        1506153457      leo_gateway_app:start/3 681     cache disc capacity: 0
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755024 +0900        1506153457      leo_gateway_app:start/3 682     cache disc threshold len: 1048576
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755086 +0900        1506153457      leo_gateway_app:start/3 683     cache disc data-dir: "./cache/data"
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755149 +0900        1506153457      leo_gateway_app:start/3 684     cache disc journal-dir: "./cache/journal"
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755215 +0900        1506153457      leo_gateway_app:start/3 685     cache expire: 300
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755279 +0900        1506153457      leo_gateway_app:start/3 686     cache_max_content_len: 1048576
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755339 +0900        1506153457      leo_gateway_app:start/3 687     cacheable_content_types: []
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755404 +0900        1506153457      leo_gateway_app:start/3 688     cacheable_path_patterns: []
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755464 +0900        1506153457      leo_gateway_app:start/3 689     max_chunked_obj: 1000
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755553 +0900        1506153457      leo_gateway_app:start/3 690     max_len_of_obj: 5242880000
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755613 +0900        1506153457      leo_gateway_app:start/3 691     chunked_obj_len: 5242880
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755669 +0900        1506153457      leo_gateway_app:start/3 692     reading_chunked_obj_len: 5242880
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:37.755725 +0900        1506153457      leo_gateway_app:start/3 693     threshold_of_chunk_len: 5767168
```

### Remaining Problem ###
`lager` seems cannot get the `module` `line` `function` with `error_logger:info_msg` or `error_logger:debug_msg`
```
[D]     gateway_0@192.168.100.31        2017-09-23 16:57:38.191155 +0900        1506153458      null:null       0       Supervisor leo_backend_db_sup started leo_backend_db_server:start_link(mq_worker_node_message_0, leo_backend_db_eleveldb, "./work/queue/membership/message0", true) at pid <0.1499.0>
[D]     gateway_0@192.168.100.31        2017-09-23 16:57:38.191498 +0900        1506153458      null:null       0       Supervisor leo_mq_sup started leo_mq_server:start_link(mq_worker_node_3, 3, {mq_properties,mq_worker_node,undefined,leo_membership_mq_client,leveldb,3,1,"./work/queue/membe...",...}) at pid <0.1494.0>
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:38.191813 +0900        1506153458      null:null       0       {module,"leo_mq_consumer"},{function,"init/1"},{line,171},{body,[{id,mq_worker_node_consumer_3_1},{publisher_id,mq_worker_node},{interval,10},{batch_of_msgs,5000}]}
[D]     gateway_0@192.168.100.31        2017-09-23 16:57:38.192103 +0900        1506153458      null:null       0       Supervisor leo_mq_sup started leo_mq_consumer:start_link(mq_worker_node_consumer_3_1, mq_worker_node, {mq_properties,mq_worker_node,undefined,leo_membership_mq_client,leveldb,3,1,"./work/queue/membe...",...}, 3) at pid <0.1501.0>
[D]     gateway_0@192.168.100.31        2017-09-23 16:57:38.192440 +0900        1506153458      null:null       0       Supervisor leo_mq_sup started leo_mq_server:start_link(mq_worker_node_2, 2, {mq_properties,mq_worker_node,undefined,leo_membership_mq_client,leveldb,3,1,"./work/queue/membe...",...}) at pid <0.1502.0>
[I]     gateway_0@192.168.100.31        2017-09-23 16:57:38.192506 +0900        1506153458      null:null       0       {module,"leo_mq_consumer"},{function,"init/1"},{line,171},{body,[{id,mq_worker_node_consumer_2_1},{publisher_id,mq_worker_node},{interval,10},{batch_of_msgs,5000}]}
```

**Comment by windkit** [comment]
### Related PRs
https://github.com/leo-project/lager/pull/1
https://github.com/leo-project/leo_logger/pull/5
https://github.com/leo-project/leofs/pull/861

**Comment by vstax** [comment]
@windkit I have a question, before this change a new log file was always created upon start, e.g. when the current log file was info.20171027.20.1 and you restarted node, then logs after startup went to info.20171027.20.2.
It's different on current devel version, new log lines get appended to info.20171027.20.1 instead. Is this change intentional and it will be like that in the future?

**Comment by windkit** [comment]
@vstax this is unintentional, i will fix it. As we want the behavior remains the same

**Comment by windkit** [comment]
PR at https://github.com/leo-project/leo_logger/pull/8

**Comment by yosukehara** [comment]
Since solved the problem, I've closed this issue.
