### ISSUE TITLE
[leo_storage][leo_mq][1.3.3] Items in QUEUE_ID_ASYNC_DELETION can keep existing

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#732]
if it's already deleted.
Found on https://github.com/leo-project/leofs/issues/725#issuecomment-300698977.
This issue is degradation mixed in during 1.3.3-dev cycle.

**Comment by yosukehara** [comment]
Linked https://github.com/leo-project/leofs/issues/725#issuecomment-300711899
