### ISSUE TITLE
[leofs_client_tests] add the test for aws-sdk-cpp

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#743]
Background: There are some needs to use aws-sdk-cpp with LeoFS as mentioned on https://groups.google.com/forum/#!topic/leoproject_leofs/jNXNBhahfbs.

Reference: https://github.com/aws/aws-sdk-cpp

Sample Code: https://gist.github.com/mocchira/0bb570f240cbad3c8d97191fa0d6d68b

**Comment by windkit** [comment]
@kunaltyagi I have checked your code at https://github.com/kunaltyagi/leofs_client_tests
1. the endpointOverride should not contain the scheme, aka http/https
2. aws-sdk-cpp uses the virtual-hosted-style to address a bucket, so you need a DNS record for {bucket}.{host}

After fixing these, the test works fine.

**Comment by mocchira** [comment]
@windkit Please close this one once CI pipeline become to run the tests for aws-sdk-cpp.

**Comment by windkit** [comment]
It is now included in the CI pipeline
