### ISSUE TITLE
[leo_storage] delete-bucket can not work in case the objects were created on LeoFS <= 1.3.2.1

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#754]
Revealed through the comment https://github.com/leo-project/leofs/issues/725#issuecomment-305876515.

### Conditions
- The objects stored under a bucket that is supposed to be deleted through delete-bucket were created on
  - LeoFS <= 1.3.2.1
- LeoFS that is supposed to invoke delete-bucket
  - LeoFS >= 1.3.3 (1.3.3, 1.3.4 affected)

### How to fix
Call leo_object_storage_transformer:transform_metadata against each metadata in leo_storage_handler_object:prefix_search_and_remove_objects as leo_storage_handler_object:prefix_search does.

**Comment by yosukehara** [comment]
DONE
