### ISSUE TITLE
Resetting gateway identity/membership (or light gateways)

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#756]
I have a question / feature request regarding gateway nodes. They are important component for handling load, and can be scaled as needed. You can place them where you got resources, and unlike storage nodes which obviously should be placed on dedicated servers, I think it makes more sense to have more gateways spread over few servers rather than have dedicated servers with less gateways. All in all, it seems really alluring to put them in containers and manage through e.g. kubernetes, but there is a problem. They store identity / membership persistently, which creates need for persistent volumes or anything similar; of course I'd like to avoid that, to me it just doesn't make sense to have any disk persistence for gateway. But managers insist on knowing all their gateways (and will complain if gateway disappears and so on).

I can think of two ways to solve this problem (but there might be more). First is just ignoring the membership queues and create gateway each time with the same name (e.g. `gateway_0@192.168.0.1`); technically it will be a different gateway each time the container is created, but leo_manager will be tricked into thinking that it's the same. Are there any downsides / possible problem with this approach? (idk, maybe something useful is stored in these queues. Or maybe it will cause some garbage to accumulate on manager nodes after you do this a lot of times)

Even if it works, it's not perfect, e.g. it doesn't allow you to create "few more gateways for now to handle current load" and just remove the excess later - executing "remove-gateway" will be needed. Still, if there are no other downsides, it's quite nice solution regardless.
 
The other solution is some kind of "light gateway" flag. The idea is that manager automatically wipes the gateway soon after it's stopped. Then you generate each gateway as unique, e.g. `gateway_65fa1eaae221@some_ip` and don't care about how long it lives; soon after it's destroyed and new one is generated, the managers will forget about existence. The idea is that 1) you can have as many gateways as you need right now (e.g. by just scaling number of pods in RC in kubernetes) and 2) there are no tricks, you don't make managers into thinking that "it's the same gateway but unfortunately lost its membership information!", it's genuinely new gateway and manager is aware of that. So if there are any problems with first solution, this one should work better. But, well, it needs this feature (auto-wipe of stopped gateways).

(I assume that gateways are always behind load balancers which are configured to detect gateway changes right away, so applications have no problems with all this)

**Comment by mocchira** [comment]
@vstax 

> I can think of two ways to solve this problem (but there might be more). First is just ignoring the membership queues and create gateway each time with the same name (e.g. gateway_0@192.168.0.1); technically it will be a different gateway each time the container is created, but leo_manager will be tricked into thinking that it's the same. Are there any downsides / possible problem with this approach? (idk, maybe something useful is stored in these queues. Or maybe it will cause some garbage to accumulate on manager nodes after you do this a lot of times)

No downsides as membership queues only include the notifications to managers that  there are inconsistencies in the ring checksum between the local node and others (that said others can detect the same inconsistencies even if the one the local node have got lost).
So I'd recommend in this way.

> Even if it works, it's not perfect, e.g. it doesn't allow you to create "few more gateways for now to handle current load" and just remove the excess later - executing "remove-gateway" will be needed. Still, if there are no other downsides, it's quite nice solution regardless.

Yes not perfect but should work with a little bit tweaks as you said (assign the same ip address and issue remove-gateway as needed).

> The other solution is some kind of "light gateway" flag. The idea is that manager automatically wipes the gateway soon after it's stopped. Then you generate each gateway as unique, e.g. gateway_65fa1eaae221@some_ip and don't care about how long it lives; soon after it's destroyed and new one is generated, the managers will forget about existence. The idea is that 1) you can have as many gateways as you need right now (e.g. by just scaling number of pods in RC in kubernetes) and 2) there are no tricks, you don't make managers into thinking that "it's the same gateway but unfortunately lost its membership information!", it's genuinely new gateway and manager is aware of that. So if there are any problems with first solution, this one should work better. But, well, it needs this feature (auto-wipe of stopped gateways).

Interesting to me.
We may take this idea into account for the future release.
Thanks for your suggestion.

**Comment by vstax** [comment]
@mocchira Thank you. I'll proceed with the first way.
