### ISSUE TITLE
[docs] How to reset the numbers leofs-adm du shows

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#765]
There are some cases that need such operation like

- https://github.com/leo-project/leofs/issues/763 - wrong numbers caused by Unknown Bugs
- State files were not updated properly due to an abnormal shutdown.

So it would be good to have a document to fix those numbers.

**Comment by vstax** [comment]
But doesn't the answer already exist in current FAQ ("do compaction and it'll fix everything")? Here: http://leo-project.net/leofs/docs/faq/administration/#the-result-of-the-du-command-can-be-different-with-the-actual-disk-usage

**Comment by mocchira** [comment]
@vstax Yep I'm totally missing this one. thank you.
