### ISSUE TITLE
Support extra config files (*.d/*.conf) in addition to main one

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#771]
In some cases, people prefer not to change default application config but add an extra one which only has changes from default values. This style (typically in addition to `application.conf` you get `application.d/*.conf` files) is popular because you can easily see all the changes made by system administrator, it also gets rids of problem during upgrades when default config is changed: you either ignore the default changes (usually made for a reason) or need to check & merge config after each upgrade, which is annoying.

Notably, changes like https://github.com/leo-project/leofs/pull/737/commits/37dd4df10af2fdad0f0d04f8e1faeb127f64f51d are pulled automatically if people use this style config changes.

Example minimal leo_manager config:
```
$ cat /usr/local/leofs/1.3.4/leo_manager_0/etc/leo_manager.d/10-nodename.conf
nodename = manager_0@192.168.3.50
manager.partner = manager_1@192.168.3.51
```

Here is example implementation: https://github.com/vstax/leofs/commit/c56d8febdcfb9fd1e025ca1107ca49572b5a1b2f

It's currently missing Makefile and documentation changes (I'll do them if there is interest in this change).

This feature is completely optional, if the directory or extra config files don't exist, nothing is changes. All expected features work like in other products - changing extension from .conf to something else make launch script ignore that file, config files are processed in alphabetical order (use `10-*`, `20-*` etc for enforcing strict order). Current limitation: spaces in path to config files, or config files themselves will break this code. I don't know of a way to implement this without shell arrays (which /bin/sh doesn't always support, e.g. `dash` in Debian doesn't); don't think there is any need to bother, this isn't expected in real life anyway. And if it happens, the script will likely to break in other places anyway.

**Comment by mocchira** [comment]
@vstax Thanks for the suggestion.

> It's currently missing Makefile and documentation changes (I'll do them if there is interest in this change).

We have interests :) so please do. looking forward to receiving your PR.

> Current limitation: spaces in path to config files, or config files themselves will break this code. I don't know of a way to implement this without shell arrays (which /bin/sh doesn't always support, e.g. dash in Debian doesn't); don't think there is any need to bother, this isn't expected in real life anyway. And if it happens, the script will likely to break in other places anyway.

Agreed.
Just Commenting "Doesn't work if there is any file whose name includes any space" is enough to me.

**Comment by vstax** [comment]
@mocchira Here it is, please review #773. Came as a few commits, so feel free to squash them during merge if everything is OK.

New logic to pick config files works as supposed on bash / dash (Linux), ksh93 (Solaris) and FreeBSD sh, although I didn't do a real testing of how it all works together other than on Linux - but there shouldn't really be any difference.

**Comment by vstax** [comment]
@mocchira Thank you for review and testing. Everything seems fine so closing this.
