### ISSUE TITLE
s3cmd 

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#775]
[E]	gateway_01@10.39.1.28	2017-06-22 15:05:44.901926 +0800	1498115144	null:null	0	Ranch listener leo_gateway_s3_api had connection process started with cowboy_protocol:start_link/4 at <0.18250.0> exit with reason: {[{reason,{case_clause,{value,{badrpc,nodedown}}}},{mfa,{leo_gateway_s3_api,handle,2}},{stacktrace,[{leo_s3_bucket,find_bucket_by_name_2,3,[{file,"src/leo_s3_bucket.erl"},{line,948}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{leo_s3_bucket,find_bucket_by_name_1,3,[{file,"src/leo_s3_bucket.erl"},{line,907}]},{leo_s3_bucket,get_latest_bucket,1,[{file,"src/leo_s3_bucket.erl"},{line,612}]},{leo_gateway_s3_api,handle,2,[{file,"src/leo_gateway_s3_api.erl"},{line,1425}]},{cowboy_handler,handler_handle,4,[{file,"src/cowboy_handler.erl"},{line,111}]},{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]},{req,[{socket,#Port<0.2197>},{transport,ranch_tcp},{connection,keepalive},{pid,<0.18250.0>},{method,<<"GET">>},{version,'HTTP/1.1'},{peer,{{10,39,1,43},39964}},{host,<<"s3.amazonaws.com">>},{host_info,undefined},{port,80},{path,<<"/">>},{path_info,undefined},{qs,<<"delimiter=/">>},{qs_vals,undefined},{bindings,[]},{headers,[{<<"host">>,<<"s3.amazonaws.com">>},{<<"accept-encoding">>,<<"identity">>},{<<"content-length">>,<<"0">>},{<<"authorization">>,<<"AWS 1f4b5c2d20406ba4d6c2:ylcXKKOdfX3B3xP4l60XVopgPc0=">>},{<<"x-amz-date">>,<<"Thu, 22 Jun 2017 07:05:44 +0000">>}]},{p_headers,[]},{cookies,undefined},{meta,[]},{body_state,waiting},{buffer,<<>>},{multipart,undefined},{resp_compress,false},{resp_state,waiting},{resp_headers,[]},{resp_body,<<>>},{onresponse,undefined}]},{state,[{1,64},true,undefined,{http_options,leo_gateway_s3_api,8080,8443,"./etc/server_cert.pem","./etc/server_key.pem",128,4096,"./etc/http_custom_header.conf",5000,15000,5242880,inner,16,268435456,0,1048576,"./cache/data","./cache/journal",300,1048576,[],[],1000,5242880000,5242880,5242880,5767168}]}],[{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]}

**Comment by yosukehara** [comment]
I've formatted the error-log to easily understand:

```erl
[E]	gateway_01@10.39.1.28	2017-06-22 15:05:44.901926 +0800
	1498115144	null:null	0	
Ranch listener leo_gateway_s3_api had connection process started
with cowboy_protocol:start_link/4 at <0.18250.0> exit with reason:

{[{reason,{case_clause,{value,{badrpc,nodedown}}}},
  {mfa,{leo_gateway_s3_api,handle,2}},
  {stacktrace,[{leo_s3_bucket,find_bucket_by_name_2,3,[{file,"src/leo_s3_bucket.erl"},{line,948}]},
               {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
               {leo_s3_bucket,find_bucket_by_name_1,3,[{file,"src/leo_s3_bucket.erl"},{line,907}]},
               {leo_s3_bucket,get_latest_bucket,1,[{file,"src/leo_s3_bucket.erl"},{line,612}]},
               {leo_gateway_s3_api,handle,2,[{file,"src/leo_gateway_s3_api.erl"},{line,1425}]},
               {cowboy_handler,handler_handle,4,[{file,"src/cowboy_handler.erl"},{line,111}]},
               {cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]},
  {req,[{socket,#Port<0.2197>},
        {transport,ranch_tcp},
        {connection,keepalive},{pid,<0.18250.0>},{method,<<"GET">>},{version,'HTTP/1.1'},
        {peer,{{10,39,1,43},39964}},
        {host,<<"s3.amazonaws.com">>},
        {host_info,undefined},{port,80},{path,<<"/">>},
        {path_info,undefined},{qs,<<"delimiter=/">>},
        {qs_vals,undefined},{bindings,[]},
        {headers,[{<<"host">>,<<"s3.amazonaws.com">>},
                  {<<"accept-encoding">>,<<"identity">>},
                  {<<"content-length">>,<<"0">>},
                  {<<"authorization">>,<<"AWS 1f4b5c2d20406ba4d6c2:ylcXKKOdfX3B3xP4l60XVopgPc0=">>},
                  {<<"x-amz-date">>,<<"Thu, 22 Jun 2017 07:05:44 +0000">>}]},
        {p_headers,[]},
        {cookies,undefined},
        {meta,[]},
        {body_state,waiting},
        {buffer,<<>>},
        {multipart,undefined},
        {resp_compress,false},
        {resp_state,waiting},
        {resp_headers,[]},
        {resp_body,<<>>},
        {onresponse,undefined}]},
  {state,[{1,64},true,undefined,
          {http_options,leo_gateway_s3_api,8080,8443,
           "./etc/server_cert.pem","./etc/server_key.pem",
           128,4096,"./etc/http_custom_header.conf",
           5000,15000,5242880,
           inner,16,268435456,0,1048576,
           "./cache/data","./cache/journal",300,1048576,[],[],1000,
           5242880000,5242880,5242880,5767168}]}],
 [{cowboy_protocol,execute,4,[{file,"src/cowboy_protocol.erl"},{line,442}]}]}
```

**Comment by mocchira** [comment]
@yosukehara thanks.

@xingxing9688 given that the stack trace including `leo_s3_bucket,find_bucket_by_name_2,3,[{file,"src/leo_s3_bucket.erl"},{line,948}]`, you seems to use version 1.3.2.1.

https://github.com/leo-project/leo_s3_libs/blob/1.2.9/src/leo_s3_bucket.erl#L948

that said, you probably hit https://github.com/leo-project/leofs/issues/642 so upgrading to the latest 1.3.4(or 1.3.5 that will be released on the next week) should solve your problem.
