### ISSUE TITLE
Storage nodes perform some operations quite slow

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#787]
I have a question regarding performance issues on storage nodes during some operations; it's delete-bucket here in question, but it's not limited to just this, I'm more interested in this problem in general sense.

The operation is slow; there are errors, e.g.
```
[W]	storage_1@192.168.3.54	2017-07-19 19:11:13.860610 +0300	1500480673	leo_storage_replicator:replicate/5	123	[{method,delete},{key,<<"bodytest/e5/a3/84/e5a384f216d906661267a25f00c7e91f69d61e0b628d527940226028734d07dd7fc12da6dcb17936a2ac13ff1a15087248d5df0000000000.xz\n2">>},{cause,timeout}]
[W]	storage_1@192.168.3.54	2017-07-19 19:11:13.861225 +0300	1500480673	leo_storage_replicator:replicate_fun/2	243	[{key,<<"bodytest/e5/a3/84/e5a384f216d906661267a25f00c7e91f69d61e0b628d527940226028734d07dd7fc12da6dcb17936a2ac13ff1a15087248d5df0000000000.xz">>},{node,local},{req_id,0},{cause,"Replicate failure"}]

[I]	storage_1@192.168.3.54	2017-07-19 19:11:15.890270 +0300	1500480675	leo_object_storage_event:handle_event/254	[{cause,"slow operation"},{method,fetch},{key,<<"bodytest">>},{processing_time,41940}]
[I]	storage_1@192.168.3.54	2017-07-19 19:11:15.890615 +0300	1500480675	leo_object_storage_event:handle_event/254	[{cause,"slow operation"},{method,head},{key,<<"bodytest/0f/c3/90/0fc390382e880d2abde1858f795349a3a0ec549cc61e59009b84433b7ec4d98a771000d7e4acf3cb827f4c90942f21e5989b040000000000.xz">>},{processing_time,38964}]
```
"processing_time,38964" means head operation took 39 seconds, right? However, isn't that quite a lot for this operation?

The disk load is very low, network load is low as well. It looks like some threads are either CPU-bound or waiting for , e.g.
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 2464 leofs     20   0 7523880 409484 102120 R 41,3  5,1   1:30.43 2_scheduler                                                  
 2463 leofs     20   0 7523880 409484 102120 S 23,9  5,1   2:16.80 1_scheduler                                                  
 2465 leofs     20   0 7523880 409484 102120 S 21,7  5,1   0:38.35 3_scheduler                                                  
 2466 leofs     20   0 7523880 409484 102120 R 21,7  5,1   0:22.53 4_scheduler                                                  
 2551 leofs     20   0 7523880 409484 102120 R  6,5  5,1   0:21.04 Eleveldb                                                     
 2544 leofs     20   0 7523880 409484 102120 S  4,3  5,1   0:07.29 Eleveldb                                                     
```

From "perf top" (this one without kernel/glibc debug symbols, just for big picture):
```
  13,10%  beam.smp                 [.] scheduler_wait
   7,59%  beam.smp                 [.] process_main
   6,41%  [kernel]                 [k] __do_softirq
   5,73%  [kernel]                 [k] _raw_spin_unlock_irqrestore
   4,18%  [kernel]                 [k] finish_task_switch
   3,52%  [kernel]                 [k] __schedule
   2,10%  [kernel]                 [k] smp_call_function_many
   1,27%  beam.smp                 [.] full_sweep_heaps.isra.12
   1,00%  beam.smp                 [.] erts_schedule
   0,98%  libpthread-2.17.so       [.] pthread_getspecific
   0,98%  libc-2.17.so             [.] __memcpy_ssse3_back
   0,93%  beam.smp                 [.] erts_alcu_check_delayed_dealloc
   0,88%  [vdso]                   [.] __vdso_clock_gettime
   0,76%  [kernel]                 [k] system_call_after_swapgs
   0,74%  beam.smp                 [.] copy_struct_x
   0,73%  beam.smp                 [.] aoff_get_free_block
   0,72%  [kernel]                 [k] __audit_syscall_exit
   0,70%  beam.smp                 [.] erts_alcu_alloc_thr_pref
   0,66%  [kernel]                 [k] tick_nohz_idle_enter
   0,65%  beam.smp                 [.] aoff_link_free_block
   0,65%  eleveldb.so              [.] leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::FindGreaterOrEqual
   0,64%  libc-2.17.so             [.] __memcmp_sse4_1
   0,59%  beam.smp                 [.] size_object
   0,57%  beam.smp                 [.] erts_alcu_free_thr_pref
   0,55%  [kernel]                 [k] tick_nohz_idle_exit
```

leo_doctor output: https://pastebin.com/MFGAQRGb

vm.args contents:
```
config /etc/leofs/leo_storage/leo_snmp
+secio true
+zdbbl 32768
+scl true
-smp enable
-env ERL_MAX_ETS_TABLES 256000
-env ERL_CRASH_DUMP /var/log/leofs/leo_storage/erl_crash.dump
-env ERL_FULLSWEEP_AFTER 0
-env ERL_MAX_PORTS 64000
+A 32
+K true
-setcookie 401321b4
-name storage_2@192.168.3.55
+P 1048576
```
Error and rex watchdogs are enabled with default parameters, rest are disabled. This is SL 7.3 VM with 8 CPU cores, and they are mostly idling. LeoFS was built with erlang-19.3 (official Centos 7 package from Erlang Solutions) here. The situation is identical for all 3 nodes.

I'd like to know if this whole situation is caused by some suboptimal settings like buffers, amounts of threads and so on and it's possible to change something to improve it. I don't strictly need more performance here, this is test system, I'd just like to understand if there is some problem with configuration that I should be aware of.

Alternatively - if the configuration is OK and it's a problem in implementation, is it well-known? Or it's not really a problem but just something done so that service operation won't consume all the resources and enough is left for normal GET / PUT operations?

If it is a problem but not well-known, what analyzing tools can be used to get more details about it? Like, what is waiting for what here?

**Comment by mocchira** [comment]
@vstax thanks for reporting.

> "processing_time,38964" means head operation took 39 seconds, right? However, isn't that quite a lot for this operation?

Right. it's in **ms**.

The root cause of this sort of problems are already filed there.

- https://github.com/leo-project/leofs/issues/764
- https://github.com/leo-project/leofs/issues/758

In short, **Lock** around the operation to a AVS/metadata can cause the other operation trying to touch the same AVS/metadata to timeout. as commented on the issue or pointers described on it, those problems can be solved by making each operation as short as possible or distributing operations evenly on every AVS/metadata (for the delete-bucket case).

> I'd like to know if this whole situation is caused by some suboptimal settings like buffers, amounts of threads and so on and it's possible to change something to improve it. I don't strictly need more performance here, this is test system, I'd just like to understand if there is some problem with configuration that I should be aware of.

As I said above, it's userland software problem so no need to tweak configurations.

>  If it is a problem but not well-known, what analyzing tools can be used to get more details about it? Like, what is waiting for what here?

Good question. leofs_doctor is your best friend for the purpose.
While such problem happen, kind of the below lines get appeared by leofs_doctor.

```
             Pid Registered Name      Initial Call                   Current Function                         Reductions   Reductions+  MQueue HSize        SSize  HTotal      
       <0.180.0> leo_metadata_0       proc_lib:init_p/5              eleveldb:iterator_move/2                 3471268148   3471268148   138    10958        31     11046        
```
In this case, metadata_0 is congested (lots of operations are trying to touch it at the same time) due to iterating objects by eleveldb:iterator_move/2.
The large value at the column **MQueue** is a sign that something goes wrong.

**Comment by vstax** [comment]
@mocchira Thank you. I understand that there is nothing to be done right now so closing this.
