### ISSUE TITLE
Better upgrades that don't require manual steps

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#791]
This is related to tickets #790 and #792 and might require implementation that depends on them.

Environment files made upgrades easier, but still not perfect - I still need to e.g. place that environment file in directory which depends on LeoFS version - global config isn't supported. Sure, on real setup it might be as easy as executing "chef-client" or similar configuration management system which is set up to place correct config files to correct directories, but that's still an extra step, it can be forgotten, and what about development, not-yet-production systems or systems that haven't described management of LeoFS yet? If global config files or global environment files would work, then no extra steps would be needed. Sure, upgrades of such software should be done carefully and thoughtfully, but mundane steps should be avoided, if possible.

This can be solved by global config file and/or global environment file support, but the problems are:
1. How to make it work both for users that want global config and for users that plan to use current system (config files under versioned tree). Current users should be able to continue using current system without any steps, should be able to switch to global config system if desired, and new users should have easy way of picking and using both global or current config files, depending on preference.
2. How to make it work with multiple instances of nodes of the same type (#792)

Some options on how the first part might work:
Startup script checks for existence of `/etc/leofs/global.conf`; if it exists and has "global_config = yes" defined, then it ignores .conf and .environment files in `/usr/local/leofs/<version>/leo_*/etc` and only picks schema from that directory (but if needed, it can be redefined in .environment file so schema is picked from other place as well - should someone want that).

Script checks its name (like "leo_manager_1" or "leo_storage") and loads .environment file from `/etc/leofs/<name>/<node type>.environment`. It also changes its config path default to `/etc/leofs/<name>/<node type>.conf`. This allows people to both redefine things in environment (like RUNNER_LOG_DIR) *and* use config files in `/etc/leofs/<name>` directly without setting `RUNNER_ETC_DIR=/etc/leofs/leo_manager_1` in environment file. Asking them to do a change like that just seems kind if silly, normally for this kind of setup you'd expect config file to be picked from `/etc/leofs/<name>` as well without changing .environment file. Anyhow, "global_config = yes" option changes defaults for both environment and normal config (thus `vm.args` and `app.config` as well) to global path for all LeoFS instances on this system. I think this is acceptable?

For this setup, rpm/deb package install config files for each node to `/etc/leofs/<name>` as well - they'll be identical to current config installed in `/usr/local/leofs/<version>/<name>/etc`, but marked with %config directive for rpm (and whatever is the way to handle it in Debian, I haven't checked yet but I know there should be some). The contents of `/etc/leofs/global.conf` will have "global_config = no". So current users will get that directory and it will be updated (silently, as long as they don't touch anything there) but nothing else will change. At any point of time users can set "global_config = yes", change config file and start using global config files.

This should work nicely with conf.d directory support, as long as users don't touch main config file like `/etc/leofs/leo_storage/leo_storage.conf` but only add new ones to `/etc/leofs/leo_storage/leo_storage.d/`, the main config will get overwritten during upgrade and they will get new defaults. If people prefer to change main config, that's fine as well, the config won't be overwritten.

**Caveat 1**: what if users do change config file in `/etc/leofs` but forget to set "global_config = yes"? Right now, the only indication of where config files are picked are in `erlang.log` file, for example
```
Exec: /usr/local/leofs/current/leo_gateway/erts-8.3/bin/erlexec -boot /usr/local/leofs/current/leo_gateway/releases/1/leo_gateway -mode embedded -config /etc/leofs/leo_gateway/app.config -args_file /etc/leofs/leo_gateway/vm.args -- console
```
Not sure if this is enough or not. Maybe just document it around description of "global_config", that users need to check that log in case of troubles and be done with it.

**Caveat 2**: `/etc/leofs/leo_manager_1/leo_manager.conf` and `/etc/leofs/leo_manager_0/leo_manager.conf` - that's how names of manager config files will be in this scheme, isn't it a bit strange? Or totally fine? Also, `global.conf` and "global_config = yes" definitely look silly, any better ideas?

Running multiple nodes of the same type: split off to #792.

**EDIT:** option will have to be set like `global_config=yes` (without spaces around "=") since it will need to be read from shell script. I can see some hacks to read ini-style config from shell but they are ugly and usually bash-centered, better to just add a comment to that file that file is in shell syntax.

**Comment by mocchira** [comment]
As I commented on #790, I'd agree with the overall idea about global config.

> Not sure if this is enough or not. Maybe just document it around description of "global_config", that users need to check that log in case of troubles and be done with it.

Documents seems enough to me for now.

> Caveat 2: /etc/leofs/leo_manager_1/leo_manager.conf and /etc/leofs/leo_manager_0/leo_manager.conf - that's how names of manager config files will be in this scheme, isn't it a bit strange? Or totally fine? 

IMHO, fine.

> Also, global.conf and "global_config = yes" definitely look silly, any better ideas?

As other software products tend to use ${PRODUCT_NAME}.conf as sort of global.conf, **leofs.conf** and "global_config = yes" within that looks sane to me.

**Comment by vstax** [comment]
@mocchira 
Given the condition that leofs.conf is parsed as shell script, https://github.com/vstax/leofs/commit/3b6bab162debb405bb1b28d0cc981a32522fdeb6 is about all implementation that's needed from main script, unless I'm missing something. It seems to work fine. I'm not too happy about `NODE_TYPE=$(basename "$RUNNER_BASE_DIR")` code because it relies on directory name which is a bit crooked, but I don't know another simple way to differentiate between leo_manager_0 and leo_manager_1 (without reading schema or config).

The rest is package changes (install copy of config files to /etc/leofs, mark them as config files), `rel/common/leofs.conf` (to be installed into /etc/leofs), containing notice that these config files are disabled by default and "GLOBAL_CONFIG=no" line and documentation. All of which are pretty trivial (I just want to finish merge of package and documentation changes from #790, otherwise changes will interfere).

.schema file isn't read from global config directory by default because it just doesn't seem right (this can be overridden from .environment file which is read from global config directory, of course).

Really the main problem about this feature is not implementation but how to make things not too confusing with two copies of config files installed and just one being picked.

**Comment by mocchira** [comment]
@vstax 

> Given the condition that leofs.conf is parsed as shell script, vstax/leofs@3b6bab1 is about all implementation that's needed from main script, unless I'm missing something. It seems to work fine. I'm not too happy about NODE_TYPE=$(basename "$RUNNER_BASE_DIR") code because it relies on directory name which is a bit crooked, but I don't know another simple way to differentiate between leo_manager_0 and leo_manager_1 (without reading schema or config).

I also couldn't come up with a simple/robust way instead of relying on directory names so go forward with this direction for now.

> The rest is package changes (install copy of config files to /etc/leofs, mark them as config files), rel/common/leofs.conf (to be installed into /etc/leofs), containing notice that these config files are disabled by default and "GLOBAL_CONFIG=no" line and documentation. All of which are pretty trivial (I just want to finish merge of package and documentation changes from #790, otherwise changes will interfere).

Got it. 

> .schema file isn't read from global config directory by default because it just doesn't seem right (this can be overridden from .environment file which is read from global config directory, of course). server_cert.pem/server_key.pem files are not copied as well; technically people who need SSL would want their version of these certs in /etc/leofs/leo_gateway, but with default leo_gateway.conf they won't be picked from there anyway, so I think it's best not to confuse anyone and ignore these files.

make sense to me.

> Really the main problem about this feature is not implementation but how to make things not too confusing with two copies of config files installed and just one being picked.

Yes I think so. the documentation with some images containing 

- how directories are structured
- control flow (order to read files and which ones would be prioritized and so on)

would be helpful to make it easy to understand.

and also leofs-adm status ${Node} show the path to the config file being picked might be helpful. (more easy to check rather than checking erlang.log)

**Comment by vstax** [comment]
@mocchira 
> and also leofs-adm status ${Node} show the path to the config file being picked might be helpful. (more easy to check rather than checking erlang.log)

But this would require code changes (showing directory with vm.args/app.config). Not to mention that you can't check status of managers this way. It's possible with just "status", but that would mean that managers would report different line there, which kind of breaks concept of both managers outputting exactly the same output for "status" command, no?

I could add an explicit line for log file at startup ("Using configuration files from <...>"), so at least it's clear and one doesn't need to look at the long erlexec line. It will go to erlang.log for normal script and journald for systemd service.

**Comment by vstax** [comment]
Script part is ready and can be merged if everything is OK.
Package part is available at https://github.com/vstax/leofs_package/commit/c9c38cb624272e4ef43b574a7a61cffeba6f1d3d - I think it's ready as well, but can't submit PR until https://github.com/leo-project/leofs_package/pull/7 is merged

> Yes I think so. the documentation with some images containing

I, uh, am not too sure about images.. I'll try to describe it the best I can.
Images are hard to support as well: i.e. current image in documentation describing upgrade process has mistake (it suggest copying queue/mnesia directories before stopping nodes), and how to fix if it's a picture?.. So complicated.

Right now (with proposed script change) log in erlang.log or journalctl looks like this:
```
[root@bodies-s2 ~]# journalctl -u leofs-storage|head -n 6
-- Logs begin at Ср 2016-10-19 21:10:26 MSK, end at Чт 2017-09-14 22:10:01 MSK. --
сен 14 21:35:38 bodies-s2.dev.cloud.lan systemd[1]: Started LeoFS storage node.
сен 14 21:35:38 bodies-s2.dev.cloud.lan systemd[1]: Starting LeoFS storage node...
сен 14 21:35:40 bodies-s2.dev.cloud.lan leo_storage[17117]: Config path: /etc/leofs/leo_storage
сен 14 21:35:40 bodies-s2.dev.cloud.lan leo_storage[17117]: Exec: /usr/local/leofs/current/leo_storage/erts-9.0/bin/erlexec -noinput -boot /usr/local/leofs/current/leo_storage/releases/1/leo_storage -mode minimal -config /etc/leofs/leo_storage/app.config -args_file /etc/leofs/leo_storage/vm.args -- console
сен 14 21:35:40 bodies-s2.dev.cloud.lan leo_storage[17117]: Root: /usr/local/leofs/current/leo_storage
```

Anyhow, interesting part about this change is that it should be compatible with any OS (including FreeBSD and Solaris), though I didn't test that, but there are no reasons why it wouldn't work - except for packagers for these systems (or users themselves) need to actually create /etc/leofs hierarchy to activate it.

**Comment by mocchira** [comment]
@vstax 

> But this would require code changes (showing directory with vm.args/app.config). Not to mention that you can't check status of managers this way. It's possible with just "status", but that would mean that managers would report different line there, which kind of breaks concept of both managers outputting exactly the same output for "status" command, no?

Yes required and at a first glance to estimate the cost to implement in this way, ROI isn't good compared to a simple logging solution also as you said, a little bit semantically incompatible changes may be required so I'd agree with logging one now.

> Script part is ready and can be merged if everything is OK.
Package part is available at vstax/leofs_package@c9c38cb - I think it's ready as well, but can't submit PR until leo-project/leofs_package#7 is merged

Looks good. please PR as leo-project/leofs_package#7 got merged right now.

> I, uh, am not too sure about images.. I'll try to describe it the best I can instead, I think.

Sorry. my words aren't enough. please describe the doc with words only as usual :) images will be added as needed by @yosukehara. (To make image contents consistent across all docs, he designs/creates all image stuffs on github/website)

> Images are hard to support as well: i.e. current image in documentation describing upgrade process has mistake (it suggest copying queue/mnesia directories before stopping nodes), and how to fix if it's a picture?.. So complicated.

Oops. Completely missed that issue and this ticket https://github.com/leo-project/leofs/issues/575. we will check and set appropriate milestone again. thanks!

> Right now (with proposed script change) log in erlang.log or journalctl looks like this:

Looks fine.

> Anyhow, interesting part about this change is that it should be compatible with any OS (including FreeBSD and Solaris), though I didn't test that, but there are no reasons why it wouldn't work - except for packagers for these systems (or users themselves) need to actually create /etc/leofs hierarchy to activate it.

OK. I will test platforms you didn't test so go ahead with this direction.

**Comment by vstax** [comment]
@mocchira 
I've submitted PR for package changes, please review when you have time.

> Oops. Completely missed that issue and this ticket #575. we will check and set appropriate milestone again. thanks!

Great; well, upgrade instructions should become simpler in the next version with `/usr/local/leofs/current` symlink.
Anyhow, with implementation from this ticket - when using config in `/etc/leofs` and all paths (log, mnesia, queue, etc) are configured to be set in external location (/var/leofs/...) I'm able to perform upgrades with just the following (it's not a real 1.3.7 but the one with systemd & global config patches, used to upgrade 1.3.6 with systemd & global config patches):
```
(all nodes) # rpm -Uvh leofs-1.3.7-1.x86_64.rpm
(manager master) # leo-backup-mnesia.sh; leo-backup-ring.sh
(manager slave) # systemctl stop leofs-manager-slave
(manager master) # systemctl restart leofs-manager-master
(manager slave) # systemctl start leofs-manager-slave
(all gateway) # systemctl restart leofs-gateway
(all storage) # systemctl restart leofs-storage
```
Well this example is missing suspend/resume before restarting storages since I was OK with turning off clients here, but otherwise - that's it! With non-systemd version it would be about the same, except for you'd use `/usr/local/leofs/current/leo_manager_0/bin/leo_manager stop; /usr/local/leofs/current/leo_manager_0/bin/leo_manager start` in place of `systemctl restart leofs-manager-master` because "restart" has different meaning in original script.

(backup scripts here execute "backup-mnesia" and "dump-ring" and move resulting files to backup server)

Just upgrading package and then restarting service is all that's needed. Keeping in mind that you need to shutdown both managers for upgrade instead of upgrading them one by one and that you need to suspend/resume storage nodes if you don't want extra errors on the clients, I can say that upgrade process now can be about as simple as it's supposed to be. Well, it's possible because online upgrade is supported by LeoFS nodes themselves, it's only default installation directories and launch script peculiarities that were preventing it from being simple.

Actually, thinking about this, I wonder if it's possible to automate "suspend" before shutting down storage node and "resume" after it's up and connected; it's a bit annoying to do it on completely different systems and synchronize the timing. As I understand, it's more of interface problem (like the need for two different kinds of "stop" operation - one that does suspend, then waits for requests to finish before shutdown and another that shutdowns directly; plus, automatic "resume" after node is started kills the ability to delay that "resume" operation till somewhat later).

I'll do documentation for this feature a bit later.

**Comment by mocchira** [comment]
@vstax Great job!

> Actually, thinking about this, I wonder if it's possible to automate "suspend" before shutting down storage node and "resume" after it's up and connected; it's a bit annoying to do it on completely different systems and synchronize the timing. As I understand, it's more of interface problem (like the need for two different kinds of "stop" operation - one that does suspend, then waits for requests to finish before shutdown and another that shutdowns directly; plus, automatic "resume" after node is started kills the ability to delay that "resume" operation till somewhat later).

It seems somewhat worth thinking about how it should be such as providing graceful stop/start commands in startup scripts.

> I'll do documentation for this feature a bit later.

OK.

**Comment by vstax** [comment]
@mocchira 
Thank you for review. I got some time to write documentation, preliminary version is at https://gist.github.com/vstax/5231ff285b0d997db2912cd97efeaa79
Came out as a bit heavy/annoying reading, too many paths embedded in text blocks, not yet sure how to fix this. But adding more text will hurt this even more, I need to throw away something out of here instead, I think, to make smaller so it can be read at just a quick glance (because feature itself is simple enough for that).

**Comment by mocchira** [comment]
@vstax Thanks! I will check that version later and drop feedback here if I find something to be fixed or something to be thrown away.

**Comment by mocchira** [comment]
@vstax IMHO, the current version is well enough readable to me.

Two things I noticed and maybe worth rewriting.

> When launched from other location like /home/leofs/leo_manager_0 it will load configuration from /home/leofs/leo_manager_0/etc

This part looks a little bit redundant so can be thrown away.

> The full path depends on node type, there are /etc/leofs/leo_manager_0 - for manager master, /etc/leofs/leo_manager_1 - for manager slave, /etc/leofs/leo_gateway - for gateway, /etc/leofs/leo_storage - for storage node.

Using table markdown might improve the readability like below

The full path depends on node type as below.

|Node Type|Full Path|
|:--|:--|
|Manager Master|/etc/leofs/leo_manager_0|
|Manager Slave|/etc/leofs/leo_manager_1|
|Storage|/etc/leofs/leo_storage|
|Gateway|/etc/leofs/leo_gateway|

The content itself looks good to me.

**Comment by vstax** [comment]
@mocchira Thank you for advice on tables! I replaced the all the text from first section describing old and new config paths with two tables with short descriptions and got much more readable result.

I finished documentation for this and #792, please look at #862 when you have time.

**Comment by vstax** [comment]
@mocchira 
This issue is done for 1.3.8.
