### ISSUE TITLE
[leo_storage] How to restrict user's hard disk space

### ISSUE THREAD

**Issue by Lizting** [leo-project/leofs#806]
How to restrict user's hard disk space？

**Comment by yosukehara** [comment]
In the current implementation, v1.3.5, LeoFS outputs `error/warning log` when reaching [the threshold of a disk usage](https://github.com/leo-project/leofs/blob/master/apps/leo_storage/priv/leo_storage.conf#L145). We need to implement the restriction of write operations to avoid "disk full", which will be delivered on v1.4.0.

Related issues:
- #428 
- #464
- #747

**Comment by mocchira** [comment]
@Lizting 

> How to restrict user's hard disk space？

If **user** means the LeoFS user created by `leofs-adm create-user` then currently no way to restrict the disk usage per user like the unix quota does. however we might implement this feature when we proceed the user level multitenancy on https://github.com/leo-project/leofs/issues/557.

**Comment by Lizting** [comment]
@yosukehara @mocchira ok, thank

**Comment by mocchira** [comment]
@Lizting Could you close this issue if our comments answer your question?

**Comment by Lizting** [comment]
ok,sorry
