### ISSUE TITLE
leofs or Smartos

### ISSUE THREAD

**Issue by Lizting** [leo-project/leofs#815]
I saw it on the SmartOS website
![image](https://user-images.githubusercontent.com/31204659/29905049-d5c045f0-8e3e-11e7-813e-456eedcc607c.png)

**Comment by yosukehara** [comment]
[Project FiFo](https://project-fifo.net/) which has been [utilizing LeoFS as a data storage](https://docs.project-fifo.net/docs/installing-leofs).

**Comment by Lizting** [comment]
In fifo, create a virtual machine, where the hard disk and the system are in leofs?

**Comment by yosukehara** [comment]
> In fifo, create a virtual machine, where the hard disk and the system are in leofs?

"Project FiFo uses LeoFS for storing VM datasets, snapshots and backups."
- [docs.project-fifo.net/docs/leofs-overview](https://docs.project-fifo.net/docs/leofs-overview)

**Comment by Lizting** [comment]
OK，Thank you very much
But I asked fifo author before
He said：FiFo downloads datasets into LeoFS, creating zones/vm's happens from LeoFS not from the web or remote sources. That is exactly the reason why we use LeoFS in the first place.
I don't understand（creating zones/vm's happens from LeoFS）<--What does that mean？

**Comment by yosukehara** [comment]
> I don't understand（creating zones/vm's happens from LeoFS）<--What does that mean？

@Lizting I'm not sure. I suggest you directly confirm that to him.

**Comment by Lizting** [comment]
OK,Thank
