### ISSUE TITLE
[leo_object_storage] Take much time to open with lots of AVS files

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#841]
https://github.com/leo-project/leo_object_storage/blob/1.3.17/src/leo_object_storage_haystack.erl#L430 cause opening an AVS to take at least 100ms so it could be non-negligible time with lots of AVSs. Instead timer:sleep should be invoked only in abnormal cases.

**Comment by vstax** [comment]
Thank you, this cuts loading time for (4*64 AVS files) from 1 minute 52 seconds to just 9 seconds.

**Comment by mocchira** [comment]
Great to hear that.
