### ISSUE TITLE
Added Leofs as a suggestion to include in Landscape for CNCF

### ISSUE THREAD

**Issue by raghu999** [leo-project/leofs#847]
https://github.com/cncf/landscape/issues/182

Hello Leofs Team, I have referenced Leofs to be added in CNCF landscape.Please let me know if you Leofs Team have any issues with this, I will delete or close this issue in cncf landscape

**Comment by mocchira** [comment]
@raghu999 Thanks for suggesting LeoFS on CNCF landscape.  no issues at all so please keep it open :)

**Comment by yosukehara** [comment]
@raghu999 LeoFS has appeared on [Landscape v0.9.8 for CNCF](https://raw.githubusercontent.com/cncf/landscape/master/landscape/CloudNativeLandscape_latest.jpg)

Thank you for your contribution.
