### ISSUE TITLE
Unable to remove gateway using DNS name through leofs-adm

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#851]
On latest develop version, I'm unable to execute "leofs-adm remove-gateway" when gateway has DNS name:
```
[vm@bodies-master ~]$ leofs-adm status|grep k09
  G    | gateway_k09@192.168.130.218                      | stop         | -1             | -1             | 2017-09-27 19:45:08 +0300
  G    | gateway_k09@k09.selectel.cloud.lan               | stop         | -1             | -1             | 2017-09-27 19:10:14 +0300
[vm@bodies-master ~]$ leofs-adm remove-gateway gateway_k09@192.168.130.218
OK
[vm@bodies-master ~]$ leofs-adm remove-gateway gateway_k09@k09.selectel.cloud.lan
[ERROR] Invalid arguments
```
Commands like "status <gateway>" work fine, though. There are no errors in logs. Gateway with the same name and just IP was added later just for test (i.e. removal didn't work even before I added gateway_k09@192.168.130.218)

**Comment by mocchira** [comment]
@vstax Thanks for reporting. I've found there is an unnecessary validation to check whether the latter part of the argument to remove-gateway comply with IPv4 format so I will get rid of that.

**Comment by mocchira** [comment]
@vstax as you may know, this has been fixed on develop so please check it out if you have time.

**Comment by vstax** [comment]
@mocchira 
This fix works, thank you.
