### ISSUE TITLE
LeoFS Create Bucket and Put Object Tests Fail

### ISSUE THREAD

**Issue by kunaltyagi** [leo-project/leofs#854]
Reproduction (using ```erlcloud```):
```
$ pwd
~/leofs_client_tests/erlcloud
$ make
$ ./leofs-adm delete-bucket teste 05236  # I fixed this step but haven't done a PR yet
$ make exec
$ ./leofs-adm delete-bucket teste 05236  # Delete bucket, coz the test dosn't. Will issue a PR soon
$ make exec
```
All 3 test runs give different results.
1st run succeeds

2nd run Output:
```
===== Create Bucket [teste] Start =====
escript: exception error: {aws_error,
                     {http_error,500,undefined,
                         <<"<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>teste/</Resource><Req"...>>}}
  in function  erlcloud_s3:s3_request/8 (src/erlcloud_s3.erl, line 1059)
  in call from erlcloud_s3:s3_simple_request/8 (src/erlcloud_s3.erl, line 1028)
```

3rd run Output:
```
...
===== Put Object [teste/test.large.meta] with Metadata Start =====
escript: exception error: {aws_error,{socket_error,timeout}}
  in function  erlcloud_s3:s3_request/8 (src/erlcloud_s3.erl, line 1059)
  in call from erlcloud_s3:put_object/6 (src/erlcloud_s3.erl, line 707)
```

If you wait for sufficient time, then the tests run successfully.

IMO, the bucket creation and object put should trigger cleanups in case the bucket and object details are similar enough.

**Comment by windkit** [comment]
Essentially, this is creating a bucket right after deleting the bucket with the same name.

For Amazon S3, it is also done asynchronously, but it returns a HTTP 409 (Conflict)

**Comment by windkit** [comment]
HTTP 500 is not informative, and it is caused by the new return value `{error, "Same bucket exists")` from `leo_manager_api:add_bucket`
https://github.com/leo-project/leofs/blob/master/apps/leo_manager/src/leo_manager_api.erl#L2262

`leo_gateway_s3_api:put`, the return is not handled
https://github.com/leo-project/leofs/blob/master/apps/leo_gateway/src/leo_gateway_s3_api.erl#L340

I would suggest to handle it and reply 409 as Amazon S3 does
@yosukehara @mocchira

**Comment by windkit** [comment]
For the 3rd run, it is a socket timeout, it may be the node is slow down by the bucket clear process

**Comment by mocchira** [comment]
@windkit please close if there is no problem.
