### ISSUE TITLE
Special URL to check gateway's health in S3 mode (for LB)

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#858]
Having multiple gateways behind load balancer creates a need for LB to check health of gateway. For example, Riak CS offers special "/riak-cs/ping" URL for that purpose - performing "GET /riak-cs/ping" every second or few allows LB to check if the gateway is working.

I couldn't find anything similar for LeoGateway. This is not a problem for REST mode, but annoying in S3. I had to settle for this sequence:
1. Create new user (e.g. "leofs-adm create-user _health_check")
2. Create bucket for that user (e.g. "leofs-adm add-bucket hcheck ...")
3. Put access and secret key to .s3cfg and put an empty object to the bucket ("touch empty; s3cmd put empty s3://hcheck/empty")
4. Start tcpdump capture and execute "s3cmd --signature-v2 get s3://hcheck/empty". Signature part is important because otherwise there will be much more headers.
5. Grab headers from capture and put them to LB config (escaping all carriage returns and spaces, if needed).

And I get this (in haproxy configuration):
```
option      httpchk GET http://hcheck.s3.amazonaws.com/empty HTTP/1.1\r\nHost:\ hcheck.s3.amazonaws.com\r\nAuthorization:\ AWS\ 7114d4a2b8336e1a52be:i/rcyKXK/fXNv5U+MVRpM8BYXIs=\r\nx-amz-date:\ Wed,\ 27\ Sep\ 2017\ 19:45:30\ +0000
```

Which isn't compatible with any other cluster and such even, these steps need to be performed for each cluster separately.

I've tried doing it simpler way without creating bucket, using GET / request - which lists buckets for that user (i.e. getting empty result), it works as well but creates some extra traffic between gateway and manager. Doing GET on actual object doesn't do that, so it's better, I think.

It would be nice to have a special URL for that purpose (unless I missed one and it's already there). Ideally, that URL should be available for GET request without any authorization and return any 2xx code with any data, if gateway is connected to cluster. It should return bad code (e.g. 500) when there are problems on gateway meaning that it shouldn't be used right now (during startup, when losing connection to cluster and so on).

Health check by HTTP request is not the only way - naturally, LBs have an option to use simple connection check on the port gateway listens to. However, it's not a good indication that gateway is actually connected to cluster and should be used.

**Comment by vstax** [comment]
@mocchira 
Thank you. I've checked this patch and the logic seems to work perfectly ("OK" reply is instant even when some storage nodes are stopped or powered off). Just two thoughts:
1. `/_leofs_adm/ping` could be a "special name" regardless of authorization header because it's impossible to create bucket starting with "_". I'm not sure if it makes any sense to do health check WITH authorization header, though, so it probably doesn't matter.
2. Even though I mentioned S3 in here (because in REST mode you just upload an empty object and then access it) - since you implemented more proper check, I think it makes sense to have it available in REST mode as well. So in case someone needs that feature there will be no surprise that it's available in S3 mode but unavailable in REST.

I think the fact that you can't access a real object named "leofs_adm/ping" (or "_leofs_adm/ping", or even declaring that all URLs starting from "_leofs_adm" are special) shouldn't be a problem?

**Comment by mocchira** [comment]
@vstax Thanks for checking this out.

> /_leofs_adm/ping could be a "special name" regardless of authorization header because it's impossible to create bucket starting with "_". I'm not sure if it makes any sense to do health check WITH authorization header, though, so it probably doesn't matter.

Totally make sense. we will rename to something like you suggested by using http://leo-project.net/leofs/docs/admin/protocols/s3/#naming-rule-of-a-bucket.
Also this should be fixed because there is a case in S3 mode that /leofs_adm/ping can be accessed as an object created by a user without the authorization header when the access control level of a bucket named `leofs_adm` is set to **public-read**.

> Even though I mentioned S3 in here (because in REST mode you just upload an empty object and then access it) - since you implemented more proper check, I think it makes sense to have it available in REST mode as well. So in case someone needs that feature there will be no surprise that it's available in S3 mode but unavailable in REST.

Also make sense to me.

> I think the fact that you can't access a real object named "leofs_adm/ping" (or "_leofs_adm/ping", or even declaring that all URLs starting from "_leofs_adm" are special) shouldn't be a problem?

I think so (documenting would make it no problem).

**Comment by mocchira** [comment]
PR: https://github.com/leo-project/leofs/pull/864

**Comment by vstax** [comment]
@mocchira It works for me on test system:
```
$ wget -Y off http://leo-g0.dev.cloud.lan:8080/_leofs_adm/ping -O /dev/null
--2017-10-05 19:38:42--  http://leo-g0.dev.cloud.lan:8080/_leofs_adm/ping
Resolving leo-g0.dev.cloud.lan (leo-g0.dev.cloud.lan)... 192.168.3.52
Connecting to leo-g0.dev.cloud.lan (leo-g0.dev.cloud.lan)|192.168.3.52|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2
Saving to: '/dev/null'

/dev/null                         100%[===========================================================>]       2  --.-KB/s    in 0s      

2017-10-05 19:38:42 (887 KB/s) - '/dev/null' saved [2/2]
```
but fails on the other:
```
$ wget -Y off http://k02.selectel.cloud.lan:8080/_leofs_adm/ping -O /dev/null
--2017-10-05 19:37:46--  http://k02.selectel.cloud.lan:8080/_leofs_adm/ping
Resolving k02.selectel.cloud.lan (k02.selectel.cloud.lan)... 192.168.130.211
Connecting to k02.selectel.cloud.lan (k02.selectel.cloud.lan)|192.168.130.211|:8080... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-10-05 19:37:46 ERROR 403: Forbidden.
```
HTTP session to leo-g0:
```
GET /_leofs_adm/ping HTTP/1.1
User-Agent: Wget/1.19.1 (linux-gnu)
Accept: */* 
Accept-Encoding: identity
Host: leo-g0.dev.cloud.lan:8080
Connection: Keep-Alive

HTTP/1.1 200 OK
Connection: keep-alive
Date: Thu, 05 Oct 2017 16:38:42 GMT
Content-Length: 2 
Server: LeoFS

OK
```
HTTP session to k02:
```
GET /_leofs_adm/ping HTTP/1.1
User-Agent: Wget/1.19.1 (linux-gnu)
Accept: */* 
Accept-Encoding: identity
Host: k02.selectel.cloud.lan:8080
Connection: Keep-Alive

HTTP/1.1 403 Forbidden
Connection: keep-alive
Date: Thu, 05 Oct 2017 16:32:16 GMT
Content-Length: 192
Server: LeoFS

<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>k02.selectel.cloud.lan/_leofs_adm/ping</Resource><RequestId></RequestId></Error>
```

leo-g0 is on fully running cluster, users:
```
user_id       | role_id | access_key_id          | created_at                
--------------+---------+------------------------+---------------------------
_test_leofs   | 9       | 05236                  | 2016-10-27 21:10:55 +0300
body          | 1       | 8b8124cd9ba4e9e191bf   | 2017-03-10 18:57:50 +0300
body_download | 1       | 1a41c8fc5dca817f35c6   | 2017-03-10 18:54:29 +0300
leo_admin     | 9       | 82074a0f63a78bccf84e   | 2016-10-28 20:28:47 +0300
new_test      | 1       | 0ad943c90daa3193f3ea   | 2017-09-07 17:03:41 +0300
s3_test       | 1       | 1c402877c67f3794f8c1   | 2016-11-03 20:14:03 +0300
```
k02 is on cluster with both managers and 1 storage node (out of 6) running:
```
user_id       | role_id | access_key_id          | created_at                
--------------+---------+------------------------+---------------------------
_health_check | 1       | 7114d4a2b8336e1a52be   | 2017-09-27 20:24:25 +0300
_test_leofs   | 1       | 05236                  | 2017-09-15 20:30:42 +0300
body          | 1       | 0fc67b42677ded00cc46   | 2017-09-22 21:17:37 +0300
```
I can't figure out any more differences. The same code, nearly identical gateway configs.. Nothing in debug or access log.

**Comment by mocchira** [comment]
> It was just me doing a stupid thing, I forgot that S3 gateway must be accessed only with correct endpoint in "Host" header. (DNS name points to LB so I did it this way to access gateway directly)
With correct "Host" header, everything works fine. "Host" header needs to be added to health check because real endpoint resolves to IP of load balancer so it can't do it correctly automatically.

Good to hear that. 

> I will add example of LB configuration to documentation

Thanks. really appreciate.

**Comment by vstax** [comment]
@mocchira I wrote preliminary text describing usage of LB, it's here: https://gist.github.com/vstax/dad69a02006d5bb4abe3d925287817bb; I'd like to move text from the current document about health check that you wrote to this document describing LB.
Also I'd like your comments on the contents (if I'm wrong on some points or there is something else important that should be added). I will do formatting/fixing minor issues and references/spellchecking later.

There are two sections (NOTE 1 and NOTE 2) that won't end up in the final document, these are the questions I have for you - I need better understanding there to ensure that sections that go after these notes are correct. I mean, I can see the need for tweaking timeouts that I describe there (it's not too hard to see problems when storages are under load and these timeouts aren't set correctly), but I can't test all cases just by creating load so I can't be sure that gateway never can exceed timeout in config just from the test. Also some complicated cases like what happens if gateway timeouts on getting N-th chunk when requesting large objects over REST (or when that part is just missing / not enough replicas? Can it even happen or it ensures that all parts are accessible before returning the object?).

**Comment by mocchira** [comment]
@vstax Thanks for writing the doc for LB! Looks almost great to me. (I mean there are nothing wrong in terms of content itself other than minor issues)

Below are the answers to questions included in the gist.

> I don't quite understand why gateway has different timeouts for "timeout.level_5" and "timeout.get" and how in all various situations it translates into maximum possible delay between client sending a request and gateway 1) sending HTTP header reply and 2) starting to send the data. 

timeout.level.* has been used only for PUT operations (it's apparently difficult to understand by its name so should be renamed to something like timeout.put.level.*) so it would be sufficient to care about only http.get for the sake of health check.

> Also, does it work the same both for S3 and REST modes or these delays can be different for REST?

Yes works the same.

> And when receiving large object in REST mode, is it possible to have delays in data between chunks?

Yes and the max delay should be limited under timeout.get.

> Does gateway always use Content-Length with full object length (even for large objects over REST) or it can use chunked encoding as well? 

Always Content-Length (no chunked encoding at all).

> Right now, the text below is written assuming that maximum possible delay between request and start of HTTP headers is no more than single maximum timeout (30 sec by default) and there is no delay between sending headers and data (or that delay is no more than 30s as well).

You are right.

> Recomendation to increase timeout_for_header here is written from LB perspective and general logic, but I can't be sure if there is nothing wrong with it from the perspective of LeoGateway itself (e.g. it can burden gateway somewhat besides usual expectation that keeping connection requires a bit more memory comparing to dropping and re-establishing it).

Yes a bit more memory is needed, to be precise, as one erlang process is spawned per one connection, at least 309 machine words (approximately 2K on 64bit) will be consumed according to http://erlang.org/doc/efficiency_guide/processes.html.

> Also some complicated cases like what happens if gateway timeouts on getting N-th chunk when requesting large objects over REST (or when that part is just missing / not enough replicas? Can it even happen or it ensures that all parts are accessible before returning the object?).

Yes it can happen so as a result, immature Body which size is less than Content-Length will be returned to the Client.

**Comment by vstax** [comment]
@mocchira 
Thanks for information, I updated contents to be more clear / precise and fixed the minor issues. I'll PR after doing checking/better formatting. I integrated note from your "Health Check URL" document here so I plan to remove it as well.

> Yes it can happen so as a result, immature Body which size is less than Content-Length will be returned to the Client.

Well it can be "returned" only if connection is closed, otherwise it will be just stuck till client or gateway timeouts, I think? It's not like connection can be reused when there wasn't enough data to match Content-Length.

**Comment by mocchira** [comment]
@vstax 

> Well it can be "returned" only if connection is closed, otherwise it will be just stuck till client or gateway timeouts, I think? It's not like connection can be reused when there wasn't enough data to match Content-Length.

Yep right. 
anyway, what do you think changing the current impl on leo_gateway to terminate the connection because the current one forces the client (LB in your case) to wait for their timeout?

**Comment by vstax** [comment]
@mocchira Yes it's definitely a good idea because that timeout (mid-stream) is often configured to very large value, so it will be a long wait unless gateway aborts the connection itself. That said, I didn't check if that's what really happens now (connection gets stuck when gateway in REST mode can't get some chunk of data).

**Comment by mocchira** [comment]
@vstax OK. I'll work that on https://github.com/leo-project/leofs/issues/894

**Comment by vstax** [comment]
@mocchira I looked at logs and suddenly realized that even in S3 mode big objects are requested by applications with a single GET request, not by parts (at least that's what boto3 does). Somehow I missed this before. I'll change LB documentation a bit to show that it's not just REST mode that can suffer from this timeout mid-stream.

**Comment by mocchira** [comment]
@vstax the PR got merged so please close if there is nothing to do.

**Comment by vstax** [comment]
@mocchira Thank you.
