### ISSUE TITLE
leofs qq 群 (Discussion Group in Tencent QQ)

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#868]
leofs qq 群号 群号:610390335

**Comment by yosukehara** [comment]
@xingxing9688 Do you think you could edit the title and the description in English? I cannot understand Chinese.

Also, can you explain to me in a little more detail?

**Comment by windkit** [comment]
@yosukehara It is a discussion group created in Tencent QQ

**Comment by yosukehara** [comment]
@windkit Thanks for your comment.
@xingxing9688 I've closed this issue. If you have any issue, please file it as another issue.
