### ISSUE TITLE
Increase default open files limit (on Linux)

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#883]
Both storage nodes (when having > ~40 AVS files) and gateway nodes (when handling many connections at once, especially since "erlang.max_ports" is already set to 64000 by default) need increase in open files limit, which defaults to 1024 on EL6/EL7 and Ubuntu distributions. When nodes are launched as systemd services, this limit will be increased (to 65535) in unit files. I thought it's a good idea to document that users launching through normal script (at least all EL6 and Ubuntu 14 users) might need to increase it manually, but then understood that it's possible to just supply PAM configuration with the package to do it automatically instead. The change is in https://github.com/leo-project/leofs/pull/882 and https://github.com/leo-project/leofs_package/pull/10 (package should can only be merged after main one).

However, while this fully works for EL6/7, it doesn't work on current Ubuntu due to it lacking pam_limits.so in PAM configuration for sudo (which is used to switch user to "leofs"): https://bugs.launchpad.net/ubuntu/+source/sudo/+bug/1268373
There are 4 options:
1. Ignore this problem (just mention it in documentation). Which is kind of sad and inconvenient. Especially because documenting that "you need to set bigger nofile in limits.conf" won't help as limits configuration is ignored.
2. Replace "sudo" by "su" in launch script. Probably possible, but somewhat annoying change: I've tested how sudo works on various Linux systems and FreeBSD and Solaris as well, and right now everything (environment variables, default directory, shell) works correctly. Using su would require specifying shell directly (e.g. `su -s /bin/sh - leofs ...`) and testing on all various systems that it really behaves just like sudo does right now. I know for sure that "su" works differently, e.g. it seems to go through scripts in `/etc/profile.d` which is kind of undesirable, I think (not in sense that it's bad, just that it's a change). Basically sudo executes command directly (though it's possible to execute through shell as well) and su always goes through shell, which is the reasons for their slightly different behaviour.
3. Add explicit ulimit call in launch script, e.g. "ulimit -n 65535 2> /dev/null". This is a bit ugly, but seems to be the most compatible change. The bad thing about it is that it will reduce bigger limit to this, possibly creating a big annoyance for user. So no matter what is set in limits.conf or systemd unit file will be downgraded to 65535 here. I'm pretty sure that it should not be a problem, however: for storage node, it would require launching it with >4500 AVS files to require bigger limit, for gateway it probably would mean load so high that multiple gateways should really be used at that point. Still, this issue is something to keep in mind. Also this command would always fail (even though error will be silenced) for managers running as systemd services (where limit isn't increased for managers because there is no need). Again, not really a problem, just not a very nice thing.
4. More complicated version of previous: put 65535 in leo_storage / leo_gateway schema/config as some "max file descriptors" option and increase file limit directly from code. This avoids all problems of previous solution but requires bigger changes than adding a single line to script (config/schema changes are needed as well), plus apparently calling setrlimit() in Erlang isn't that simple? (not sure)

Both su and setrlimit() solution will work on Ubuntu, there is no hard limit set, only soft limit of 1024 files.
Personally I like option 3 the most, though if it's not too hard to do setrlimit() call in Erlang, then 4 becomes a better solution (best user experience).
For the record, it's also possible to avoid problem of redefining the limit to lower value in 3rd solution by adding new environment variable, e.g. `ulimit -n ${MAX_OPEN_FILES:-65535}`; then, in case someone _really_ would want to increase that limit, it could be changed in .environment file. At a cost of slightly added complexity, though.

Overall, this change should solve this problem for all production systems using default rpm/deb packages and running services as "leofs" user. I can't do anything about users of FreeBSD/Solaris, also users that are using non-default user on production and for development systems: for example, running 3 storage nodes on single system probably would require increasing open files limit past 1024 even with default amount of AVS files.

**Comment by mocchira** [comment]
@vstax Thanks for the suggestion.

> Personally I like option 3 the most, though if it's not too hard to do setrlimit() call in Erlang, then 4 becomes a better solution (best user experience).

+1 for option 3 as calling setrlimit in erlang force us to write NIF. (actually there is a third-party library that enables us to call setrlimit without managing NIF by ourselves however the way to abstract setrlimit looks not good to me so am not going to depend on this library without fixing this problem) 

> For the record, it's also possible to avoid problem of redefining the limit to lower value in 3rd solution by adding new environment variable, e.g. ulimit -n ${MAX_OPEN_FILES:-65535}; then, in case someone really would want to increase that limit, it could be changed in .environment file. At a cost of slightly added complexity, though.

Sounds good to me. let's go with this direction if there is no other drawbacks.

**Comment by vstax** [comment]
@mocchira 
OK, I changed launch script like that. Increases limit on Ubuntu just fine. Had to make new PR because for some reason old PR refused to show second commit to the same branch; weird.

**Comment by vstax** [comment]
@mocchira To fully work (case when sudo uses pam_limits.so, like EL6/EL7 and Ubuntu with different settings) this still requires merging of package changes https://github.com/leo-project/leofs_package/pull/10 - can you please review them?

**Comment by mocchira** [comment]
@vstax Oops. thanks for pointing out. I'll check right now.
