### ISSUE TITLE
 s3cmd can not be uploaded and downloaded, but you can create bucket

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#890]
leofs  version    1.37  
centos    7.2    3.10.514  
s3cmd put  x86_64.tar.gz s3://test-xing 
WARNING: Retrying failed request: /x86_64.tar.gz?uploads
WARNING: 500 (InternalError): We encountered an internal error. Please try again.
WARNING: Waiting 3 sec...
upload: 'x86_64.tar.gz' -> 's3://test-xing/x86_64.tar.gz'  [part 1 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in    0s    62.59 MB/s  done
upload: 'x86_64.tar.gz' -> 's3://test-xing/x86_64.tar.gz'  [part 2 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in    0s    71.12 MB/s  done
WARNING: Upload failed: /x86_64.tar.gz?partNumber=2&uploadId=d5b34b9b8ac3a6447e7e956c0766cb80 (500 (InternalError): We encountered an internal error. Please try again.)
WARNING: Waiting 3 sec...
upload: 'x86_64.tar.gz' -> 's3://test-xing/x86_64.tar.gz'  [part 2 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in    0s    70.15 MB/s  done
WARNING: Upload failed: /x86_64.tar.gz?partNumber=2&uploadId=d5b34b9b8ac3a6447e7e956c0766cb80 (500 (InternalError): We encountered an internal error. Please try again.)
WARNING: Waiting 6 sec...
upload: 'x86_64.tar.gz' -> 's3://test-xing/x86_64.tar.gz'  [part 2 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in    0s    64.99 MB/s  done
WARNING: Upload failed: /x86_64.tar.gz?partNumber=2&uploadId=d5b34b9b8ac3a6447e7e956c0766cb80 (500 (InternalError): We encountered an internal error. Please try again.)
WARNING: Waiting 9 sec...
upload: 'x86_64.tar.gz' -> 's3://test-xing/x86_64.tar.gz'  [part 2 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in    0s    50.14 MB/s  done
WARNING: Upload failed: /x86_64.tar.gz?partNumber=2&uploadId=d5b34b9b8ac3a6447e7e956c0766cb80 (500 (InternalError): We encountered an internal error. Please try again.)
WARNING: Waiting 12 sec...
upload: 'x86_64.tar.gz' -> 's3://test-xing/x86_64.tar.gz'  [part 2 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in    0s    59.87 MB/s  done
WARNING: Upload failed: /x86_64.tar.gz?partNumber=2&uploadId=d5b34b9b8ac3a6447e7e956c0766cb80 (500 (InternalError): We encountered an internal error. Please try again.)
WARNING: Waiting 15 sec...
upload: 'x86_64.tar.gz' -> 's3://test-xing/x86_64.tar.gz'  [part 2 of 3, 15MB] [1 of 1]
 15728640 of 15728640   100% in    0s    67.28 MB/s  done
WARNING: Too many failures. Giving up on 'x86_64.tar.gz'
ERROR: 
Upload of 'x86_64.tar.gz' part 2 failed. Use
  /bin/s3cmd abortmp s3://test-xing/x86_64.tar.gz d5b34b9b8ac3a6447e7e956c0766cb80
to abort the upload, or
  /bin/s3cmd --upload-id d5b34b9b8ac3a6447e7e956c0766cb80 put ...
to continue the upload.
ERROR: Upload of 'x86_64.tar.gz' failed too many times (Last reason: )

**Comment by mocchira** [comment]
@xingxing9688 Can you share the error logs on leo_storage(s)?

**Comment by mocchira** [comment]
@xingxing9688 also please tell us the version of s3cmd. if you use s3cmd 2.0 then you may hit https://github.com/leo-project/leofs/issues/799. if this is the case then please try 1.6.1 instead that is expected to work.

**Comment by windkit** [comment]
As we don't have further updates on this, we would close this issue @xingxing9688
