### ISSUE TITLE
Storge automatically stop, but the message in the log does not show any exception

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#900]
My configuration can be seen  # #872 ，
Last night was normal. Check out 04 stop today

There are no log files available in the log

**Comment by xingxing9688** [comment]
![1 png](https://user-images.githubusercontent.com/23273577/31921434-f8427034-b8a1-11e7-9368-e035180fa323.jpg)

**Comment by xingxing9688** [comment]
If there is a storge node or stop failure in leofs cluster, then use s3cmd or API upload and download files will fail, and the design of leofs distributed high availability is not, I think, if have a leofs storge stop or failure, should not affect the normal operation of the entire cluster I leofs

**Comment by xingxing9688** [comment]
egrep -v "^$|#" /usr/local/leofs/1.3.7/leo_storage/etc/leo_storage.conf 
managers = [manager_0@10.39.20.29, manager_1@10.39.20.25]
obj_containers.path = [/data/leofs]
obj_containers.num_of_containers = [8]
watchdog.common.loosen_control_at_safe_count = 1
watchdog.rex.is_enabled = true
watchdog.rex.interval = 10
watchdog.rex.threshold_mem_capacity = 33554432
watchdog.cpu.is_enabled = false
watchdog.cpu.raised_error_times = 5
watchdog.cpu.interval = 10
watchdog.cpu.threshold_cpu_load_avg = 5.0
watchdog.cpu.threshold_cpu_util = 100
watchdog.disk.is_enabled = false
watchdog.disk.raised_error_times = 5
watchdog.disk.interval = 10
watchdog.disk.threshold_disk_use = 85
watchdog.disk.threshold_disk_util = 90
watchdog.disk.threshold_disk_rkb = 98304
watchdog.disk.threshold_disk_wkb = 98304
watchdog.cluster.is_enabled = false
watchdog.cluster.interval = 10
watchdog.error.is_enabled = false
watchdog.error.interval = 60
watchdog.error.threshold_count = 100
autonomic_op.compaction.is_enabled = false
autonomic_op.compaction.parallel_procs = 1
autonomic_op.compaction.interval = 3600
autonomic_op.compaction.warn_active_size_ratio = 70
autonomic_op.compaction.threshold_active_size_ratio = 60
compaction.limit_num_of_compaction_procs = 4
compaction.waiting_time_regular = 500
compaction.waiting_time_max = 3000
compaction.batch_procs_regular = 1000
compaction.batch_procs_max = 1500
mq.num_of_mq_procs = 4
mq.num_of_batch_process_max = 3000
mq.num_of_batch_process_regular = 1600
mq.interval_between_batch_procs_max = 3000
mq.interval_between_batch_procs_regular = 500
replication.recovery.size_of_stacked_objs = 5242880
replication.recovery.stacking_timeout = 1
mdc_replication.size_of_stacked_objs = 33554432
mdc_replication.stacking_timeout = 30
mdc_replication.req_timeout = 30000
mdc_replication.stacking_procs = 1
log.log_level = 0
log.is_enable_diagnosis_log = true
leo_ordning_reda.send_after_interval = 0
mnesia.dump_log_write_threshold = 50000
mnesia.dc_dump_limit = 40
nodename = storage_04@10.39.20.24
distributed_cookie = 401321b4
erlang.kernel_poll = true
erlang.async_threads = 32
erlang.max_ports = 64000
erlang.crash_dump = ./log/erl_crash.dump
erlang.max_ets_tables = 256000
erlang.smp = enable
erlang.schedulers.compaction_of_load = true
erlang.schedulers.utilization_balancing = false
erlang.distribution_buffer_size = 32768
erlang.fullsweep_after = 0
erlang.secio = true
process_limit = 1048576

**Comment by mocchira** [comment]
@xingxing9688 I think this issue is duplicated with #901 so please close this one as now discussion is ongoing on #901.

**Comment by mocchira** [comment]
Close as duplicated with #901.
