### ISSUE TITLE
Multi Data Center Replication  error 

### ISSUE THREAD

**Issue by xingxing9688** [leo-project/leofs#906]
Configuring join-cluster failed to report connections, but the telnet port is open

**Comment by xingxing9688** [comment]
[root@leofs_manager01 ~]# leofs-adm -h 10.39.1.39  join-cluster manager_0@10.39.20.29:13075 manager_1@10.39.20.25:13076  
[ERROR] Could not connect
[root@leofs_manager01 ~]# leofs-adm -h 10.39.1.39  join-cluster manager_0@10.39.20.29 manager_1@10.39.20.25
[ERROR] Could not connect
[root@leofs_manager01 ~]# leofs-adm   join-cluster manager_0@10.39.20.29 manager_1@10.39.20.25
[ERROR] Could not connect
[root@leofs_manager01 ~]# leofs-adm   join-cluster manager_0@10.39.20.29 manager_1@10.39.20.25
[ERROR] Could not connect

**Comment by xingxing9688** [comment]
leofs  本地是 1.3.2.1   版本

远程leofs 版本是 1.3.7
Leofs is local version of 1.3.2.1
The remote version of leofs is 1.3.7

**Comment by xingxing9688** [comment]
Leofs is local version of 1.3.2.1
The remote version of leofs is 1.3.7

**Comment by xingxing9688** [comment]
leofs-adm  join-cluster manager_0@10.39.20.29:13075 manager_1@10.39.20.25:13076 
[ERROR] Could not connect

**Comment by windkit** [comment]
can you confirm the two cluster can communicate to each other?

**Comment by xingxing9688** [comment]
![1111](https://user-images.githubusercontent.com/23273577/32035681-6abaaddc-ba4d-11e7-9b6c-dc6505adeb70.png)



The network is open

**Comment by xingxing9688** [comment]
@ @yosukehara @windkit

**Comment by windkit** [comment]
can you ping between the servers
10.39.1.39 and 10.39.20.25

**Comment by xingxing9688** [comment]
You don't have to think about the level of the network, because the network between my servers is universal

**Comment by xingxing9688** [comment]
Our entire network 10.39.0.0/16 network is through

**Comment by xingxing9688** [comment]
leofs-adm  join-cluster manager_0@10.39.20.29:13075 manager_1@10.39.20.25:13076 
[ERROR] Could not connect
The command failed to execute. Where is his log?
 Troubleshoot network failures,

**Comment by xingxing9688** [comment]
@windkit #816   

Is this 1.3.2's Bug?

**Comment by xingxing9688** [comment]
Does 1.3.2 have to be upgraded to 1.3.7? If the database integrity is ensured during the upgrade process

**Comment by windkit** [comment]
In #816, join-cluster was not the problem, it can join the cluster but data are not replicated.

**Comment by xingxing9688** [comment]
I'm now copying the 1.3.2 version of the leofs cluster data to the 1.3.7 version of the leofs cluster。 
But I did encounter this problem when I joined the cluster, and whether there was a problem between the leofs 1.3.2 version and the 1.3.7 version cluster

**Comment by xingxing9688** [comment]
leofs 1.3.2 If you can not copy, then how elegant upgrade to 1.3.7

**Comment by windkit** [comment]
A better description is in https://github.com/leo-project/leofs/issues/914

This is caused by the change on `system_conf_2` to `system_conf_3` introduced at `1.3.3`
Discussion would now move to #914 as the title is more informative.

**Comment by windkit** [comment]
Discussion moved to #914
