### ISSUE TITLE
ansible deployment issue

### ISSUE THREAD

**Issue by MarkLi2011** [leo-project/leofs#913]
leofs-adm status Do not see storage and gatway nodes

![image](https://user-images.githubusercontent.com/9192780/32086491-304001f0-bb08-11e7-812c-2b092cb2e5ed.png)

![image](https://user-images.githubusercontent.com/9192780/32086517-5f3154aa-bb08-11e7-9897-49c7cb454809.png)

thanks!!

**Comment by MarkLi2011** [comment]
execute script
ansible-playbook -i hosts install_leofs.yml
ansible-playbook -i hosts config_leofs.yml
ansible-playbook -i hosts start_leofs.yml

![image](https://user-images.githubusercontent.com/9192780/32087295-6d06db90-bb0d-11e7-8956-caeeb3a22ae7.png)

**Comment by mocchira** [comment]
@MarkLi2011 Can you share the hosts file and the output from ansible-playbook (output with -v option would be more helpful)? and also make sure storage hosts specified at the file can be reachable from where ansible-playbook runs.

**Comment by MarkLi2011** [comment]
@mocchira 
The problem has been resolved because of the obj_containers.path permission to modify, thanks for your advice

**Comment by mocchira** [comment]
@MarkLi2011 

> The problem has been resolved because of the obj_containers.path permission to modify, thanks for your advice!!

Good to hear that, please close this issue if there is no other problems.

**Comment by mocchira** [comment]
Close as the OP problem seems to be resolved.
