### ISSUE TITLE
Memory usage on storage nodes grows all the time

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#917]
I have a problem with high memory usage on storage nodes; I think something is leaking as resident memory usage of beam.smp process grows without stop at rate 2 GB / a day. It's at 14 GB right now. The process has 232 threads (seems sane, considering 128 async threads)
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1310 leofs     20   0 29,653g 0,014t 714000 S  12,5 44,7   1539:25 beam.smp
```
This cluster was launched on 20th, with some load on it right from the start and bigger (current) load which uploads about 10M objects per day on 24th. About a day after, memory usage started to grow - here is graph showing free memory on node ("free memory" here includes cache/buffers; all memory usage here is from beam.smp):

![free-memory-graph](https://user-images.githubusercontent.com/25686523/32186452-2b23a0e8-bdb3-11e7-83e8-9318f77eaae5.png)

This is alarming because 1) I've never seen storage nodes to use much memory (over 1 GB) during normal PUT/GET load; only special operations such as recover-node, compaction, delete-bucket and such could add few GB to memory usage, but nothing of sorts is happening here and 2) it looks like it'll keep on growing and I never expected it to use so much memory. Currently nodes have only 32 GB RAM each; 14 GB is not a problem by itself and more memory can be added, but I need to know when the growth will stop (and it doesn't seem like it will stop at all right now). The only load is PUT/GET operations and statistics gathering (every minute via SNMP, "status <node>", "du <node>" and "compact-status <node>"; also "status" and "version all" commands are issued to managers). There is nothing strange (no growth) in any other values - other than growing amount and size of objects stored, of course.

Values from erlang memory statistics are all at low values and hardly changed since launch (always about the same as in report of "status" command below).

This is happening on all 6 storage nodes. Memory usage is the same (within 5% difference) on each of them. Here are status command for first node:

```
[vm@bodies-master ~]$ leofs-adm du bodies@stor01.selectel.cloud.lan
 active number of objects: 30401283
  total number of objects: 30444709
   active size of objects: 2165897866189
    total size of objects: 2167188083648
     ratio of active size: 99.94%
    last compaction start: ____-__-__ __:__:__
      last compaction end: ____-__-__ __:__:__

[vm@bodies-master ~]$ leofs-adm compact-status bodies@stor01.selectel.cloud.lan
        current status: idling
 last compaction start: ____-__-__ __:__:__
         total targets: 256
  # of pending targets: 256
  # of ongoing targets: 0
  # of out of targets : 0

[vm@bodies-master ~]$ leofs-adm status bodies@stor01.selectel.cloud.lan
--------------------------------------+--------------------------------------
                Item                  |                 Value
--------------------------------------+--------------------------------------
 Config-1: basic
--------------------------------------+--------------------------------------
                              version | 1.3.8
                     number of vnodes | 168
                    object containers | - path:[/mnt/avs1/bodies], # of containers:64
                                                  | - path:[/mnt/avs2/bodies], # of containers:64
                                                  | - path:[/mnt/avs3/bodies], # of containers:64
                                                  | - path:[/mnt/avs4/bodies], # of containers:64
                        log directory | /var/log/leofs/leo_storage/erlang
                            log level | info
--------------------------------------+--------------------------------------
 Config-2: watchdog
--------------------------------------+--------------------------------------
 [rex(rpc-proc)]                      |
                    check interval(s) | 10
               threshold mem capacity | 33554432
--------------------------------------+--------------------------------------
 [cpu]                                |
                     enabled/disabled | disabled
                    check interval(s) | 10
               threshold cpu load avg | 5.0
                threshold cpu util(%) | 100
--------------------------------------+--------------------------------------
 [disk]                               |
                     enabled/disalbed | disabled
                    check interval(s) | 10
                threshold disk use(%) | 85
               threshold disk util(%) | 90
                    threshold rkb(kb) | 98304
                    threshold wkb(kb) | 98304
--------------------------------------+--------------------------------------
 Config-3: message-queue
--------------------------------------+--------------------------------------
                   number of procs/mq | 4
        number of batch-procs of msgs | max:3000, regular:1600
   interval between batch-procs (ms)  | max:3000, regular:500
--------------------------------------+--------------------------------------
 Config-4: autonomic operation
--------------------------------------+--------------------------------------
 [auto-compaction]                    |
                     enabled/disabled | disabled
        warning active size ratio (%) | 70
      threshold active size ratio (%) | 60
             number of parallel procs | 1
                        exec interval | 3600
--------------------------------------+--------------------------------------
 Config-5: data-compaction
--------------------------------------+--------------------------------------
  limit of number of compaction procs | 4
        number of batch-procs of objs | max:1500, regular:1000
   interval between batch-procs (ms)  | max:3000, regular:500
--------------------------------------+--------------------------------------
 Status-1: RING hash
--------------------------------------+--------------------------------------
                    current ring hash | 4bb5757b
                   previous ring hash | 4bb5757b
--------------------------------------+--------------------------------------
 Status-2: Erlang VM
--------------------------------------+--------------------------------------
                           vm version | 8.3.5.3
                      total mem usage | 103531320
                     system mem usage | 60657704
                      procs mem usage | 42960752
                        ets mem usage | 6117336
                                procs | 2562/1048576
                          kernel_poll | true
                     thread_pool_size | 128
--------------------------------------+--------------------------------------
 Status-3: Number of messages in MQ
--------------------------------------+--------------------------------------
                 replication messages | 0
                  vnode-sync messages | 0
                   rebalance messages | 0
--------------------------------------+--------------------------------------

```

Config file:
```
nodename = bodies@stor01.selectel.cloud.lan
managers = [manager_0@bodies-master.selectel.cloud.lan, manager_1@bodies-slave.selectel.cloud.lan]

obj_containers.path = [ /mnt/avs1/bodies,/mnt/avs2/bodies,/mnt/avs3/bodies,/mnt/avs4/bodies ]
obj_containers.num_of_containers = [  64 , 64 , 64 , 64 ]
object_storage.is_strict_check = true
watchdog.error.is_enabled = true
object_storage.threshold_of_slow_processing = 5000

sasl.sasl_error_log = /var/log/leofs/leo_storage/sasl/sasl-error.log
sasl.error_logger_mf_dir = /var/log/leofs/leo_storage/sasl

log.erlang = /var/log/leofs/leo_storage/erlang
log.app = /var/log/leofs/leo_storage/app
log.member_dir = /var/log/leofs/leo_storage/ring
log.ring_dir = /var/log/leofs/leo_storage/ring

queue_dir  = /var/leofs/leo_storage/work/queue
leo_ordning_reda.temp_stacked_dir = /var/leofs/leo_storage/work/ord_reda/
erlang.crash_dump = /var/log/leofs/leo_storage/erl_crash.dump

snmp_conf = /etc/leofs/leo_storage/leo_snmp

erlang.async_threads = 128
```

pmap -x output is here: https://pastebin.com/nr4Stcaz
erlang:memory() output for stor01 (only small amounts here..):
```
[{total,97797056},
 {processes,43286744},
 {processes_used,43260072},
 {system,54510312},
 {atom,695209},
 {atom_used,668642},
 {binary,21891760},
 {code,13201352},
 {ets,6119624}]
```
I've quickly checked some articles on debugging memory usage in Erlang but they seem to focus on memory consumption in Erlang VM and don't seem to show anything interesting, this looks more like memory leak in C code or some off-heap memory that can't be seen through usual means, I think?

For example, output of erlang:system_info({allocator, binary_alloc} is here: https://pastebin.com/ZBbvNtDi

On graph above, it is possible to see a short flat line at 27th from about 2:00 to 5:00 - upload of objects to cluster was stopped during that time (there was still low PUT/GET load on cluster, but not much was uploaded - the PUT rate was at 1/100 of PUT rate at other times). Apparently, memory usage didn't grow during that time. It's more clear in "sar -r" output here: https://pastebin.com/Xk8JUim4 - when there were almost no writes (very low average kbdirty), memory usage (kbactive) didn't grow.

Any suggestion how to find the cause (and solve it)?

**Comment by mocchira** [comment]
@vstax 

> I've quickly checked some articles on debugging memory usage in Erlang but they seem to focus on memory consumption in Erlang VM and don't seem to show anything interesting, this looks more like memory leak in C code or some off-heap memory that can't be seen through usual means, I think?

Pretty much yes.

At a first glance, https://github.com/basho/eleveldb/blob/2.0.34/src/eleveldb.app.src#L11-L16 this option might be problematic in case num_of_containers is set to large number (128 in your case) as the default: 15% would easily fill up your memory even with 7. this should be exposed and configurable to users so I will send PR later.

**Comment by mocchira** [comment]
@windkit Can you confirm if my assumption above is correct on RIT cluster environment? (as my dev-env for leofs is on memory constrained VM)

**Comment by windkit** [comment]
@mocchira sure, I will check it.

**Comment by yosukehara** [comment]
@windkit Just in case, I'd like to ask you to set `num_of_containers = 128` of each storage-node.

**Comment by windkit** [comment]
### Test Setup
Load 40Mil Images to 5 nodes cluster
 - number of AVS: 256
 - async thread: 128

### Result
Memory Increase in storage nodes, reaching around 6 GB
```
$ free -mh
             total       used       free     shared    buffers     cached
Mem:           31G        30G       279M       844K        18M        24G
-/+ buffers/cache:       6.0G        25G
Swap:           0B         0B         0B
```

```
$ ./leofs-adm du S5@192.168.100.41
 active number of objects: 22172941
  total number of objects: 22172941
   active size of objects: 783736280187
    total size of objects: 783736280187
     ratio of active size: 100.0%
    last compaction start: ____-__-__ __:__:__
      last compaction end: ____-__-__ __:__:__
```

![image](https://user-images.githubusercontent.com/360884/32206500-cf44bbc8-be38-11e7-9a38-a034175aa254.png)

I am trying to run the same test for 64 AVS

**Comment by mocchira** [comment]
@windkit Thanks for checking. looks correct to me for now.

> I am trying to run the same test for 64 AVS

OK. This should be half (so around 3GB?).

**Comment by windkit** [comment]
@mocchira Result for 64 AVS is quite similar ~5.6GB Memory USage
```
$ free -mh
             total       used       free     shared    buffers     cached
Mem:           31G        30G       255M       844K        14M        25G
-/+ buffers/cache:       5.6G        25G
Swap:           0B         0B         0B
```
```
$ ./leofs-adm du S5@192.168.100.41
 active number of objects: 22172949
  total number of objects: 22172949
   active size of objects: 783737246988
    total size of objects: 783737246988
     ratio of active size: 100.0%
    last compaction start: ____-__-__ __:__:__
      last compaction end: ____-__-__ __:__:__
```

![image](https://user-images.githubusercontent.com/360884/32208102-a90e272c-be43-11e7-828a-47e7d78fb04e.png)

**Comment by mocchira** [comment]
@windkit Sorry 

> OK. This should be half (so around 3GB?).

I was wrong here, the amount of memory consumption is proportional to the number of PUT requests so should be around the same.

> Result for 64 AVS is quite similar ~5.6GB Memory USage

So it's expected.
I will send PR tomorrow and ask you to do the same test.

**Comment by vstax** [comment]
@mocchira Thank you for analyzing. Glad it's not a leak but (more or less) expected.
If I understand correctly, the option that's supposed to work as global cache memory limit for all leveldb databases works individually for each of them due to the way LeoFS works with leveldb?

If you make it a user setting (configurable either in percents of memory or bytes), is it possible to make it work as a setting for total amount of memory for leveldb cache - like, count that when we have N leveldb instances, each needs to be passed (setting / N) amount?

Interestingly, memory usage right now is even higher than total size of leveldb "metadata" directories on disk (13 GB on-disk size, 16 GB beam.smp usage), but I suppose it's possible for many reasons.

A few more questions:
1. Is my understanding that leveldb uses its own IO and doesn't use Erlang's async_threads correct (I can see 71 Eleveldb threads on each storage node, some of which do IO)? 128 async_threads here is more or less random setting, btw, it was left from my experiments whether there will be any performance gains compared to default value under write-intense load - I couldn't notice any, but it kind of slipped into production configs later and I thought "why not, let's keep it, shouldn't hurt" and didn't remove it.
2. What about message queues? They can get quite large during some operations. I've seen queue directory to grow to 1 GB when it had millions of messages for node recovery, and nodes only had 1/20 of planned amounts of objects - which probably means that they can grow much bigger during recovery when nodes hold lots of objects. How much extra cache can they consume compared to AVS metadata? Running out of memory on all other nodes during recovery of one of them is the last thing I'd want to happen :) Maybe these queues deserve separate cache setting (which might be important in case of cache settings implementation that sets "cache setting / N" for each out of N instances, so that queues won't suffer). Unless I'm overcomplicating things, of course...

**Comment by mocchira** [comment]
@vstax 

> If I understand correctly, the option that's supposed to work as global cache memory limit for all leveldb databases works individually for each of them due to the way LeoFS works with leveldb?

Yes.

> If you make it a user setting (configurable either in percents of memory or bytes), is it possible to make it work as a setting for total amount of memory for leveldb cache - like, count that when we have N leveldb instances, each needs to be passed (setting / N) amount?

Yes possible and it would be better for users to NOT force them to calculate the appropriate amount taking num_of_containers(N) into account.

> EDIT: I gave cluster a short break from objects upload (low PUT/GET load was still there) and apparently it compacted all "metadata" directories on all nodes - now there are some .sst files (before it was just a huge .log file) and now disk usage for metadata is half of what it used to be, it went 55 MB -> 28 MB for each AVS file. For some reason this compaction couldn't proceed for days under previous load, but it happened within 5 minutes after removing that load. Even through the load wasn't that intense (4K incoming objects per minute, or 40 Mb/s incoming traffic - that's for each node), apparently it couldn't find enough time to compact databases when the load was proceeding without any pause. 5 minute break was all it needed to trigger the compaction. Is this expected?

From what I understand, yes expected.
As the size of each sst file on basho's leveldb has been changed to a large number (30-60MB) according to https://github.com/basho/leveldb/wiki/mv-overview#overlapped-versus-sorted-levels and we set write_buffer_size to around 60MB here (https://github.com/leo-project/leo_backend_db/blob/develop/include/leo_backend_db.hrl#L32), the compaction will not be triggered under a certain load but once the size of imm(immutable memory table) overflow the write_buffer_size, the compaction will occur regardless of the load.

> Is my understanding that leveldb uses its own IO and doesn't use Erlang's async_threads correct (I can see 71 Eleveldb threads on each storage node, some of which do IO)? 128 async_threads here is more or less random setting, btw, it was left from my experiments whether there will be any performance gains compared to default value under write-intense load - I couldn't notice any, but it kind of slipped into production configs later and I thought "why not, let's keep it, shouldn't hurt" and didn't remove it.

Yes leveldb use its own IO however 128 async_threads are expected to be used for read/write AVS files from the erlang code so setting async_threads to num_of_containers would be still good practice.

> What about message queues? They can get quite large during some operations. I've seen queue directory to grow to 1 GB when it had millions of messages for node recovery, and nodes only had 1/20 of planned amounts of objects - which probably means that they can grow much bigger during recovery when nodes hold lots of objects. How much extra cache can they consume compared to AVS metadata? Running out of memory on all other nodes during recovery of one of them is the last thing I'd want to happen :) Maybe these queues deserve separate cache setting (which might be important in case of cache settings implementation that sets "cache setting / N" for each out of N instances, so that queues won't suffer). Unless I'm overcomplicating things, of course...

Goood point. separate cache setting looks promising to me for now. as there are many kind of queues, we will consider what queue should be configurable from users.

**Comment by mocchira** [comment]
The result of benchmarks and replying the previous comment reminds me of write_buffer_size could be the root cause.
Assuming 256 byte is consumed to store one record on leveldb,
The amount of data that is supposed to be stored on each storage would be calculated by
```bash
# ${NUM_OF_OBJECTS} * 256 * ${NUM_OF_REPLICAS} / ${NUM_OF_NODES}
40000000 * 256 * 3 / 5 
= 6144000000 (6GB)
```
That's nearly what each storage is consuming now for the bench.

@windkit Can you try the same bench with eleveldb_write_buf_size set to smaller value like 2MB/4MB (less than around 20MB should cap the upper memory usage)

**Comment by windkit** [comment]
@mocchira I am running a test with 256 avs and set the write_buffer_size to 4MB

**Comment by windkit** [comment]
Here is the result
```
$ free -mh
             total       used       free     shared    buffers     cached
Mem:           31G        30G       324M       844K        33M        27G
-/+ buffers/cache:       3.1G        28G
Swap:           0B         0B         0B
```

![image](https://user-images.githubusercontent.com/360884/32260581-1937fafa-bf0c-11e7-8a22-b2df477b7a6b.png)

**Comment by mocchira** [comment]
@windkit Thanks. looks fine(capped)

@vstax turned out that tweaking backend_db.eleveldb.write_buf_size defined at https://github.com/leo-project/leofs/blob/develop/apps/leo_storage/priv/leo_storage.conf#L255 can reduce the amount of memory used by leofs.

Given that your obj_containers settings (128 * 4) and other leveldb instances for queues (8 * 4) that can have large records in case recover/rebalance plus a extra buffer for safe, you would have to reserve memory for write_buffer of at least 600 instances. so if you can reserve 20MB for each then around 12GB will be consumed at most.

As changing (decreasing) drastically this setting could have side effect that the frequency of compaction will increase and affect the 95th percentile latency, I'd recommend making the new setting as close as the current one while the maximum memory that can be consumed by leofs goes below what you want.

**Comment by vstax** [comment]
@mocchira 
Oh, I see. Thank you for finding this. 2GB increase in memory usage per day makes sense now: roughly 410 bytes per record in my case (in log file, which is less compact than .sst file), 3800-3900 written objects per minute, that's 410 * 3800 * 60 * 24 ~= 2 GB per day.

> Given that your obj_containers settings (128 * 4) and other leveldb instances for queues (8 * 4)

I have 64 containers per directory (as per config above), not sure if 128 * 4 is a mistake or it's 2 DB per container?
Assuming it's 64, then memory usage in my case with default configuration - 60 MB per DB - should be not much bigger than 60M * 64 * 4 ~= 15 GB (the queues were empty all the time). And that's actually the case, node memory usage has stopped growing and stays at 16.5 GB now.

> As changing (decreasing) drastically this setting could have side effect that the frequency of compaction will increase and affect the 95th percentile latency

I see. Latency doesn't really matter for this cluster. But database will be compacted only when there are new records arriving at rate faster than this value, right? In other words, if it depends only on PUT (and DELETE, but not in this case) rate, so with the same incoming rate (4K objects per minute), I know that there are 2 GB of incoming metadata per day. But since this 2GB is split over 4*64 containers, that's just 8 MB per container per day. So setting write_buffer even to 10MB will make compaction execute more rarely than once per day which is hardly a problem, right?

In that sense, the current way to set this value is a bit annoying because when greatly increasing number of containers (the original reason for which is making AVS compaction easier by reducing maximum possible file size) - say, by N times compared to default - the default write_buffer value means very high memory usage. So it has to be reduced. But the downside you're writing about (reducing will cause compaction more often and have negative effect on latency) is actually *not* the case when having large number of containers in the first place! It's like that when reducing write_buffer with default number of containers, but when number of containers is increased by N times, reducing write_buffer by N times will actually make compaction trigger at the same intervals as when not increasing number of containers and not decreasing write_buffer in the first place (with queues being exception, they might suffer from write_buffer decrease...). I don't really know what to suggest here because current way to set write_buffers directly does make sense, but at the same time reducing it accordingly to increasing number of containers does make some sense as well.
If I'm correct in the assumption above, I think that it makes sense having write_buffers setting separately for AVS metadata and for queues. So that it can be decreased for metadata without hurting service operations that create lots of messages in queues (that is, unless even very low write_buffers won't hurt queues in practice - but I really have no idea about that).

To summarize (just trying to reformulate to get better idea for some simple comment in config or documentation entry on this issue), basically what I did with these setting is increased total write buffer for metadata on each node from original 480 MB (60 * 8) to 15360 MB (60 * 64 * 4) and this write buffer has to be in memory. While increasing it does make sense under intense write load, I definitely didn't need increase that high. This per-container write buffer should be decreased when increasing number of containers so that total memory requirements won't become too high. Also, to keep compactions at bay and not to hurt latency, this value (total write buffer for all containers, not per-container!) needs to be adjusted according to rate of write (PUT/DELETE) operations per node (available over SNMP, for example).

**Comment by mocchira** [comment]
@vstax 

> Assuming it's 64, then memory usage in my case with default configuration - 60 MB per DB - should be not much bigger than 60M * 64 * 4 ~= 15 GB (the queues were empty all the time). And that's actually the case, node memory usage has stopped growing and stays at 16.5 GB now.

Grad to hear that.

> To summarize (just trying to reformulate to get better idea for some simple comment in config or documentation entry on this issue), basically what I did with these setting is increased total write buffer for metadata on each node from original 480 MB (60 * 8) to 15360 MB (60 * 64 * 4) and this write buffer has to be in memory. While increasing it does make sense under intense write load, I definitely didn't need increase that high. This per-container write buffer should be decreased when increasing number of containers so that total memory requirements won't become too high. Also, to keep compactions at bay and not to hurt latency, this value (total write buffer for all containers, not per-container!) needs to be adjusted according to rate of write (PUT/DELETE) operations per node (available over SNMP, for example).

Thanks for summarizing. It would really be helpful to document on this issue. I will write the doc on 
- http://leo-project.net/leofs/docs/admin/settings/leo_storage/
- http://leo-project.net/leofs/docs/faq/administration/

send PR and add you as a reviewer so please check it out.

**Comment by vstax** [comment]
@mocchira 
Sounds good. Looking at these documents now, I'd like to outline a few issues. In "LeoStorage Settings":

backend_db.eleveldb.write_buf_size description currently mentions "Up to two write buffers may be held in memory at the same time". Is that an error (in sense that really up to `num_containers` write buffers may be held in memory) _or_ the real memory usage can peak at  `num_containers * 2 * write_buf_size` under some conditions?

backend_db.eleveldb.max_open_files - you mentioned (in ML, IIRC) that current eleveldb doesn't use this option at all. It should be marked as obsolete then in config file and documentation.

In FAQ:
"Currently after restarting a storage node, you need to issue the resume command with leofs-adm script manually like this."

```
$ leofs-adm resume storage_0@127.0.0.1
```

It's not needed right now, unless "suspend" was explicitly executed before stopping node?

There are few more strange things in FAQ like the one regarding console from pre-1.1.0 versions but this advice about "resume" doesn't say anything about version so it seems like it applies to the latest one.


Regarding this issue. I think it definitely should be mentioned in config file as well (near write_buffers section, or maybe even better near num_of_containers settings). I think that there are two ways to describe this issue.

**First way**: near write_buffers or num_of_containers options in config file there should be a mention that these settings affect memory usage of node, which is increased by total num_of_containers * write_buffers value, and a link to the FAQ, which describes interaction between memory footprint, metadata compactions and operations like PUT / DELETE which change metadata in more detail.
The FAQ entry should give this more detailed description and include a simple calculation: node needs "write_buffers * num_of_containers" memory for all write buffers, and under constant write load, compactions will have to be performed every (write_buffers * num_of_containers / metadata_bytes_per_operation) PUT/DELETE operations (+some service ones like recover-node), e.g. every 60M * 8 / 400 ~= 1,200,000 operations. Using too much memory for write buffers is a bad idea because this memory might be needed for read cache instead, so when significantly increasing number_of_containers, it's a good idea to decrease write_buffers, but compactions affect latency of operations, so this should be taken into account as well.

I think it's really helpful to provide an example with some clear numbers like this (of course, maybe not with exactly these numbers).

**Alternative way**, which makes config and documentation simpler but requires schema changes: obsolete per-container write_buffers option (unless it's explicitly defined in user's config file). Instead provide total_write_buffers option (defaults at 480M); calculate per-container write_buffers as (total_write_buffers / num_of_containers), probably rounded to nearest 4KB or whatever value would be good.

This change makes documentation very clear: node needs total_write_buffers RAM for metadata write buffers. Under write load (PUT/DELETE) operations, metadata compactions will have to be performed every (total_write_buffers / metadata_bytes_per_operation), e.g. 480M / 400 ~= 1,200,000. It's a good idea to increase total_write_buffers for nodes that handle intense writes to make sure that latency won't suffer too often because of compactions running. (rest is the same as in previous version)

I think that second version is easier for users to understand but I don't know if it's really a good idea to replace parameter like this.
I think the fact that compactions actually will be spread over many containers is insignificant fact here, because it doesn't affect anything in a bad way. So if someone increased num_of_containers but forgot to increase total_write_buffers (and got less write_buffers per container), this configuration shouldn't be a problem because compactions will trigger at the same time, but e.g. 32 compactions of smaller databases should hurt latency less than 8 bigger compactions (in theory). And since documentation clearly states that total_write_buffers is to be increased when handling intense write load and caring about lantecy, that part is easy to understand as well.

This is contrary to the current version, where when increasing num_of_containers but not touching write_buffers, users get increased RAM usage (which can hurt normal disk caching), but not necessary get any noticeable latency improvements because increasing time between compactions that much might be pretty much worthless compared to the default settings. It all depends on type of load, and it's easier to understand interactions between total write buffers, write operations and compaction times.

What do you think?

**Comment by windkit** [comment]
To me, it is easier to have resource limits specified in total amount.

**Comment by mocchira** [comment]
@vstax Thanks for pointing out as always.

> backend_db.eleveldb.write_buf_size description currently mentions "Up to two write buffers may be held in memory at the same time". Is that an error (in sense that really up to num_containers write buffers may be held in memory) or the real memory usage can peak at num_containers * 2 * write_buf_size under some conditions?

`num_containers * 2 * write_buf_size` at a peak.

> backend_db.eleveldb.max_open_files - you mentioned (in ML, IIRC) that current eleveldb doesn't use this option at all. It should be marked as obsolete then in config file and documentation.

OK.

> It's not needed right now, unless "suspend" was explicitly executed before stopping node?

Right.

> Regarding this issue. I think it definitely should be mentioned in config file as well (near write_buffers section, or maybe even better near num_of_containers settings). I think that there are two ways to describe this issue.

Right, will do in such ways and IMO `Alternative way` sounds good to me and also @windkit as his prev comment so we are going to go towards this way while taking the semantic backward compatibility in conf into account.

**Comment by vstax** [comment]
@mocchira 

> num_containers * 2 * write_buf_size at a peak.

I see; is some special condition required to see such high memory use? If it's really rare, it's probably better to make total_write_buffer (or w/e it'll be called) as num_of_containers * write_buff_size (480M in default configuration) and mention near it that under some special condition memory usage can (temporarily, right?) peak at twice of that value?

**Comment by mocchira** [comment]
@vstax 

> I see; is some special condition required to see such high memory use? If it's really rare, it's probably better to make total_write_buffer (or w/e it'll be called) as num_of_containers * write_buff_size (480M in default configuration) and mention near it that under some special condition memory usage can (temporarily, right?) peak at twice of that value?

Yes. write buffer has been implemented in a way so-called double buffer so it can be twice at a peak while dumping the inactive buffer to disk and many writes continuously coming from outside. I will follow what you suggested above (480M in default and mention near it).

**Comment by mocchira** [comment]
### Proposal for the new write buffer configuration
Based on **Alternative way** described on https://github.com/leo-project/leofs/issues/917#issuecomment-341815068

---

#### Prerequisites
- Keep the semantic backward compatibility (SBC) for leo_storage.conf
    - **backend_db.eleveldb.write_buf_size** can be used with the same manner
- Keep the same behavior to allocate memory (**per instance**) with the prev version in default configuration.
    - need opt-in to enable the new way to allocate memory (**in total**)

#### Spec
- **backend_db.eleveldb.write_buf_size_for_metadata_in_total** will be added to allocate memory for metadata in total
    - `backend_db.eleveldb.write_buf_size_for_metadata_in_total / ${num_of_containers}` memory reserved for each leveldb instance
    - default: 0 that means `allocate memory in total` way is disabled. setting this to a positive value will make the new way take effect.
    - if `backend_db.eleveldb.write_buf_size_for_metadata_in_total / ${num_of_containers}` goes below **xMB** (TBD) then xMB will be used instead.
- **backend_db.eleveldb.write_buf_size_for_queues_in_total** will be added to allocate memory for queues in total
    - `backend_db.eleveldb.write_buf_size_for_queues_in_total / ${num_of_queue_instances}` memory reserved for each leveldb instance
    - default: 0 that means `allocate memory in total` way is disabled. setting this to a positive value will make the new way take effect.
    - if `backend_db.eleveldb.write_buf_size_for_queues_in_total / ${num_of_queue_instances}` goes below **xMB** (TBD) then xMB will be used instead.

#### Note
**xMB** will be decided later based on the enough benchmarks with as much variation of configurations as possible to avoid considerable performance degradation due to low write buffer size.

---

Feel free to drop comments.

**Comment by yosukehara** [comment]
@mocchira I agree with the specification.

**Comment by vstax** [comment]
@mocchira 
One slight problem I see is that how people who have increased num_of_containers would know that they have increased memory requirements and need to start tweaking memory options? Or that they need to switch to using `write_buf_size_for_metadata_in_total` (and would they know what value to set there?)

This depends on goal of this change, actually; if the goal is to make sure that num_of_containers and write_buffers are independent from configuration perspective (increasing num_of_containers doesn't automatically increase memory requirements), then setting `write_buf_size_for_metadata_in_total = 480M` by default (so that people know some base value) and activating backwards compatibility only when `backend_db.eleveldb.write_buf_size` is set to some (any) value - it's commented by default, so this will work - might be better, I think. But doing it this way requires a benchmark: with `write_buf_size_for_metadata_in_total` fixed to default value (480M), check latency with default number of containers (8) and for example with 128 containers, if it doesn't become worse (or becomes better) with 128 containers, then this is the way to go. If it becomes worse, this is not an option, of course. And increasing `write_buf_size_for_metadata_in_total` can be done strictly for reducing amount of compactions and reducing latency, from configuration perspective it'll be independent from num_of_containers. (the real nature of their relation will still be written in documentation / faq).

Your current plan is more compatible than this, of course, it doesn't change anything for people who have increased num_of_containers and are enjoying very rare compactions. But by having perfect backwards compatibility it makes everything more complicated for new users; I can't really say if it would be better to keep that compatibility or to break it somewhat to make it easier in a long way (with some information in release notes, of course).

**Comment by mocchira** [comment]
@vstax Thanks for the comment.

As it seems tradeoff problem taking care between existing users (my proposal) vs new users (yours), just in case I will seek public opinions through ML then decide based on the result. Thoughts?

**Comment by yosukehara** [comment]
@vstax @mocchira I suggest we make a documentation about the current behavior for v1.3.8,  after reaching the consensus how to fix this issue, we will implement that, then release it on v1.4.0.

**Comment by mocchira** [comment]
WIP

**Comment by mocchira** [comment]
@windkit When you have time,

> setting write_buf_size_for_metadata_in_total = 480M by default (so that people know some base value) and activating backwards compatibility only when backend_db.eleveldb.write_buf_size is set to some (any) value - it's commented by default, so this will work - might be better, I think. But doing it this way requires a benchmark: with write_buf_size_for_metadata_in_total fixed to default value (480M), check latency with default number of containers (8) and for example with 128 containers, if it doesn't become worse (or becomes better) with 128 containers, then this is the way to go. If it becomes worse, this is not an option, of course.

Before getting the IMPL phase started, To validate the above sentence, I'd like to ask you to benchmark as following scenarios.

- Loading and R:W=9:1 with the settings we have usually used other than num_of_containers and backend_db.eleveldb.write_buf_size
  - Test 1
    - obj_containers.num_of_containers = [8]
    - backend_db.eleveldb.write_buf_size = 62914560
  - Test 2
    - obj_containers.num_of_containers = [128]
    - backend_db.eleveldb.write_buf_size = 3932160

We would stick with @vstax proposal if there is negligible difference between two otherwise I will seek the public opinion whether or not which one is better
- default: the previous behavior enabled and need opt-in to enable the new one
- default: the new behavior enabled and need opt-in to enable the previous one

through any our public channels.

Let me know once you get things done.

**Comment by mocchira** [comment]
Now it's still under benchmarking though the latter graph in the below figure shows the result of the Test 2, looks not good shape. especially
- Load scenario (at the first peak) and R:W=9:1 mixed workload (at the third peak)

![leofs_917_bench](https://user-images.githubusercontent.com/279052/37133789-ba689e18-22d8-11e8-9dbf-892cf28b78a7.png)

however let us think for a while to decide the spec as now we are re-considering the milestone and release schedule.

**Comment by mocchira** [comment]
Note: The above benchmark has been conducted on the following environment.

### Environment

* OS: Ubuntu Server 14.04.3
* Erlang/OTP: 18.3
* LeoFS: 1.4.0-dev
* CPU: Intel Xeon E5-2630 v3 @ 2.40GHz
* HDD (node[36~50]) : 4x ST2000LM003 (2TB 5400rpm 32MB) RAID-0 are mounted at `/data/`, Ext4
* SSD (node[36~50]) : 1x Crucial CT500BX100SSD1 mounted at `/ssd/`, Ext4

**Comment by mocchira** [comment]
We've decided to leave this configuration as is for 1.4.x and will change the configuration as described on https://github.com/leo-project/leofs/issues/917#issuecomment-342731074 for 2.0. No backward compatible changes but we will provide a conf migration tool for 1.4.x users who want to upgrade 2.0.
Related issue: https://github.com/leo-project/leofs/issues/1000

Please reopen this issue if you find any remained problems here.
