### ISSUE TITLE
Making more information available over SNMP for storage nodes

### ISSUE THREAD

**Issue by vstax** [leo-project/leofs#941]
Currently, some important information is missing over SNMP, forcing to execute commands with leofs-adm to get this information (which is pretty inconvenient, requires parsing output, spams in cmd_history logs and so on). This includes:
1. Message queues. It's possible to get numbers for replication, sync-vnode and rebalance queues, but not others. Other queues, like ones related to bucket deletion are unavailable and require "mq-stats" command.
2. Compaction status, number of pending / ongoing target - information from "compact-status" command.
3. Extra information that's currently available in output of "du" command, precisely ratio of active size (I know it's just two numbers that are already available divided by each other, but it's really handy if it would be available as it is), last compaction start and end date.

Is it possible to provide these values over SNMP as well?

(btw, there is a typo in LEO-STORAGE.mib: "Acrive Objects Sizes during")

**Comment by mocchira** [comment]
Yes possible and make sense to me so will discuss among the team.

**Comment by yosukehara** [comment]
To be able to retrieve other items through SNMP, I'm going to add 12 items to [LEO-STORAGE.mib](https://github.com/leo-project/leofs/blob/master/apps/leo_storage/snmp/snmpa_storage_0/LEO-STORAGE.mib).

* MQ related items
    * Total number of MQ's messages of recovery node
    * Total number of MQ's messages of async deletion
    * Total number of MQ's messages of deletion directory
    * Total number of MQ's messages of delete directory of request
    * Total number of MQ's messages of comparison metadata between data centers
    * Total number of MQ's messages of sync object between data centers
* Data-compcation related items
    * Current status
        * _[{idle: 0}, {running: 1}, {suspending: 2}]_
    * Last start date time (Unix time)
    * Last end date time (Unix time)
    * Total number of pending targets
    * Total number of ongoing targets
    * Total number of out of targets

**Comment by yosukehara** [comment]
I've just recognized that there is one task to completely fix this issue as below:

* [ ] To be able to insert some new statistics items of LeoStorage into [Grafana](https://grafana.com/), modify [influxdata/telegraf/plugins/inputs/leofs](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/leofs)
