### ISSUE TITLE
[leo_manager] import-user with the access-key-id belonging to a deleted user doesn't work

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#964]
Because delete-user doesn't delete the corresponding credential record on the auth table.
Details can be found on https://groups.google.com/d/msg/leoproject_leofs/GGqJfRBKTAQ/V9B7yXTeBgAJ

TODO:
- [x] Delete not only records on user table but records on credential/auth table when handling delete-user
- [ ] Provide a tool to remove obsolete records on credential/auth table. (maybe checking on startup phase and deleting would be enough)

**Comment by mocchira** [comment]
The former one of TODO will be fixed by https://github.com/leo-project/leo_s3_libs/pull/11. 

Now I'm bit afraid that the latter one could take much time with many obsolete records being remained so instead I'd propose to extend import-user with -f (force update flag).
Now `import-user ${UserID} ${AccessKey} ${SecretKey}` will fail if there is no ${UserID} but ${AccessKey} exists on the credential table however `import-user -f ${UserID} ${AccessKey} ${SecretKey}` will succeed (overwrite the ${SecretKey}) even if there is ${AccessKey} record on the credential table.
@yosukehara what do you think?

**Comment by windkit** [comment]
To me, having a revocation list is better for security.

**Comment by mocchira** [comment]
@windkit 

> To me, having a revocation list is better for security.

Since we will make leofs GDPR-compliant enterprise storage on 1.4, we probably get to implement audit log for every operation so as a result, revocation list would be realized. what do you think? > @yosukehara

**Comment by yosukehara** [comment]
Due to GDPR, we need to keep logs related to user-info registration, update, and deletion/revocation, so need to also implement the following feature:

- Implements the log output of user-info operation for the system audit (GDPR, others)
