### ISSUE TITLE
[leo_manager] create|import-user can fail with records partially updated

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#965]
Because those two don't use transaction even though there are multiple update statements.
those should be changed into
```erlang
Fun = fun() -> 
    %% put all update statements into this anonymous function
    ok = mnesia:write(Table1, Value1, write),
    ok = mnesia:write(Table2, Value2, write),
end,
leo_mnesia:write(Fun);
```
to avoid partial updates.

**Comment by yosukehara** [comment]
* [create_user's transaction - apps/leo_manager/src/leo_manager_console.erl#L2097-L2132](https://github.com/leo-project/leofs/blob/1.4.2/apps/leo_manager/src/leo_manager_console.erl#L2097-L2132)
* [import_user's transaction - apps/leo_manager/src/leo_manager_console.erl#L2156-L2175](https://github.com/leo-project/leofs/blob/1.4.2/apps/leo_manager/src/leo_manager_console.erl#L2156-L2175)

**Comment by mocchira** [comment]
I'll close this as the fix has already been merged into v1.
