### ISSUE TITLE
[leo_storage] Measure rebalance/recover-node performance according to mq.num_of_mq_procs

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#987]
If there is a negligible time difference between 4 (current default) and the lower number like 1 or 2 then we should consider to lower the default as it turns out this number affect the CPU usage while there are suspended/downed nodes in the cluster. Details can be found on https://github.com/leo-project/leofs/issues/966#issuecomment-363331049.

**Comment by mocchira** [comment]
The benchmark result on RIT.

### Purpose
How much time does it take to recover-node with around 600,000 objects and how does mq.num_of_mq_procs affect the time?

### Result
- mq.num_of_mq_procs = 8
  - Time to recover: 5min
  - 1min Avg Load of the node recovered: 5.5
  - 1min Avg Load of the other nodes: 4.0 
- mq.num_of_mq_procs = 4
  - Time to recover: 8min
  - 1min Avg Load of the node recovered: 4.5
  - 1min Avg Load of the other nodes: 2.5
- mq.num_of_mq_procs = 2
  - Time to recover: 10min
  - 1min Avg Load of the node recovered: 3.5
  - 1min Avg Load of the other nodes: 1.7

### Summary
As the mq.num_of_mq_procs decreases, the time to recover takes longer while the CPU Load decreases. 

Also CPU hogged problem described on #710 has been strongly affected by mq.num_of_mq_procs so also note at the following.

Measured while one node was suspending and 20,000 items stored in the recover queue on each node.

- mq.num_of_mq_procs = 8
  - 1min Avg Load: 5.0 - 6.0
  - CPU: 500 - 650%
- mq.num_of_mq_procs = 2
  - 1min Avg Load: 2.5 - 3.0
  - CPU: 350%

### TODO
IMO, the current default (4) looks reasonable so that things we have to do is to document on
- How the mq.num_of_mq_procs setting affect the system operations
  - High
    - Fast recover/rebalance time
    - High CPU/Load on storage during recover/rebalance and also existing suspended/stopped nodes in the cluster
  - Low
    - Slow recover/rebalance time
    - Low CPU/Load on storage during recover/rebalance and also existing suspended/stopped nodes in the cluster
- Recommend settings
  - if you have enough CPU resources on storage nodes then set it to a higher one as long as it doesn't affect the operations coming from leo_gateway
  - if you don't then set it to somewhat a lower one unless the recover take too much time

@yosukehara please check the above comment, I will PR for the documentation based on the above if you find it valuable being added to the docs.

**Comment by yosukehara** [comment]
I've shared the chart of the benchmarks as below:

![leofs-benchmark-for-987](https://user-images.githubusercontent.com/148770/37131916-3897fdac-22ce-11e8-9e9e-9ac343dd692b.png)

**Comment by mocchira** [comment]
https://bitbucket.org/leo-project/reports/issues/14/benchmark-v140-dev-on-rit-server#comment-43782709 get merged into develop so I'll close.
