### ISSUE TITLE
[Feature Suggestion] Track disk usage of buckets

### ISSUE THREAD

**Issue by windkit** [leo-project/leofs#990]
### Description
Currently, if one wants to know the disk usage of a bucket, he has to send a list bucket request.
Which we know is too heavy.

If would be useful if we can keep track the total object size of a bucket, this would be useful to implement quota and provide information for multi-tenant scanerio

**Comment by yosukehara** [comment]
@windkit Thanks for your report. We already filed this issue on #127. I've closed this issue because it duplicates.
