### ISSUE TITLE
[eleveldb][leo_backend_db] Impl iterater_move in batch

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#994]
As it turned out that interactions _(to be precise, sending a message from an OS thread to an erlang scheduler thread)_ between erlang runtime and NIF are NOT negligible _(hogged CPU rather than Disk I/O)_ especially if the number of call times is relatively large _(For more details and evidences, see https://github.com/leo-project/leofs/issues/974)_.
https://github.com/leo-project/eleveldb/commit/61c1f5b3cffa61372e97598e22d6b3ec274bd73d has solved #974 by making the number of interactions from the number of records to 1 so let's take a step forward with this method, we can make this hack being applied to other iterator functions by adding a new I/F to eleveldb to iterate over items in a certain batch size, for example,
```erlang
    %% This may return 30 items in BatchItems at most or less than 30 if it hits EOF.
    %% We can expect this function to decrease the CPU cost as it lowers the number of interactions between erlang runtime and NIF.
    {ok, BatchItems} = eleveldb:iterator_next_in_batch(IterRef, 30, []),
```
With this hack, we might be able to solve #710.
I'm going to try on the next working day.

**Comment by yosukehara** [comment]
@mocchira I've just confirmed your idea. I agree to it.

**Comment by mocchira** [comment]
@yosukehara Thanks for taking time. I will go ahead from now.

**Comment by mocchira** [comment]
After some experiments, I've decided to change the new I/F as below.
```erlang
    %% This may return 30 items in BatchItems at most or less than 30 if it hits EOF.
    %% We can expect this function to decrease the CPU cost as it lowers the number of interactions between erlang runtime and NIF.
    {ok, BatchItems} = eleveldb:first_n(DBRef, 30),
```
Comparison to the previous I/F
- Pros
  - Much less code
  - Completely independent to the existing iterator related code base
- Cons
  - Use cases are narrowed down

However the iterating function we are using in leo_mq now is ONLY
- leo_backend_db_server:first_n

That said, just covering the first_n use case would solve most of our CPU hog problem for now.

**Comment by yosukehara** [comment]
@mocchira I've reviewed your idea, and I agree to deliver its function:

> the first_n use case would solve most of our CPU hog problem

```erlang
{ok, BatchItems} = eleveldb:first_n(DBRef, NumberOfItems)
```

**Comment by mocchira** [comment]
Confrimed this works fine. however unfortunately this improvement couldn't solve the #710 so I'll close this issue while leaving #710 open.
