### ISSUE TITLE
[eleveldb] Make log files less fragmented

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#995]
As reported on https://github.com/leo-project/leofs/issues/940 by @vstax, eleveldb have a fragmentation problem for its .log files. This can be fixed by calling fallocate() or posix_fallocate() when creating .log file. and also we have to check how this fix would affect the performance of synced writes to .log file for safe.

**Comment by mocchira** [comment]
@vstax Now the fallocate is called on every mmap region extent and It seems the fragmentation problem has gone at least on our test environments with ext4. If you have time, it would be great to check if this also works for your environment with xfs.

**Comment by vstax** [comment]
@mocchira Unfortunately, I won't be able to test this (given it's not in release and the problem was noticeable only on production).. I remember that original problem was worse on xfs than on ext4, though (every fragment was 4K or 8K, but fragments were somewhat bigger for ext4).

Is this change compatible with Solaris and FreeBSD, btw?

**Comment by mocchira** [comment]
@vstax 

> Unfortunately, I won't be able to test this (given it's not in release and the problem was noticeable only on production).. I remember that original problem was worse on xfs than on ext4, though (every fragment was 4K or 8K, but fragments were somewhat bigger for ext4).

Got it. I will build the test environment with xfs and do the test in my spare time.

> Is this change compatible with Solaris and FreeBSD, btw?

I've kept the same behavior (calling ftruncate) on Solaris and FreeBSD instead of calling posix_allocate as we can't ensure the enough bandwidth to test this change on those environments. So if any PR comes from the community with enough tests, we are willing to merge it :)

**Comment by mocchira** [comment]
@vstax I built the xfs environments and confirmed the issue has also been fixed on that so will close this issue. feel free to reopen if you find any problems.
